const ACRONYMS_ISSAP = [
  { abbr:"ABAC", full:"Attribute-Based Access Control — access decisions based on attributes of users, resources, and environment" },
  { abbr:"AES", full:"Advanced Encryption Standard — symmetric block cipher using 128/192/256-bit keys; current encryption standard" },
  { abbr:"API", full:"Application Programming Interface — interface enabling software components to communicate" },
  { abbr:"BAS", full:"Breach and Attack Simulation — automated tools continuously testing security control effectiveness" },
  { abbr:"CA", full:"Certificate Authority — trusted entity that issues and manages digital certificates in PKI" },
  { abbr:"CASB", full:"Cloud Access Security Broker — security policy enforcement point between users and cloud services" },
  { abbr:"CI/CD", full:"Continuous Integration/Continuous Delivery" },
  { abbr:"CNAPP", full:"Cloud-Native Application Protection Platform — unified security for cloud-native applications and infrastructure" },
  { abbr:"CRL", full:"Certificate Revocation List — list of digital certificates revoked before their expiration date" },
  { abbr:"CSPM", full:"Cloud Security Posture Management — tools detecting misconfigurations in cloud environments" },
  { abbr:"CWPP", full:"Cloud Workload Protection Platform — security solution protecting cloud workloads" },
  { abbr:"DevSecOps", full:"Development, Security, and Operations" },
  { abbr:"DLP", full:"Data Loss Prevention — controls preventing unauthorized exfiltration of sensitive data" },
  { abbr:"DMZ", full:"Demilitarized Zone — network segment isolating public-facing services from the internal trusted network" },
  { abbr:"EA", full:"Enterprise Architecture — structured representation of an organization's business processes, IT assets, and strategic objectives" },
  { abbr:"ECC", full:"Elliptic Curve Cryptography — asymmetric cryptography using elliptic curves; efficient at shorter key lengths" },
  { abbr:"ECDH", full:"Elliptic Curve Diffie-Hellman — key agreement protocol using elliptic curve cryptography" },
  { abbr:"EDR", full:"Endpoint Detection and Response — security solution monitoring endpoints for threat activity" },
  { abbr:"FIDO2", full:"Fast Identity Online 2 — open authentication standard supporting passwordless and phishing-resistant MFA" },
  { abbr:"GCM", full:"Galois/Counter Mode — authenticated encryption mode providing both confidentiality and integrity" },
  { abbr:"HMAC", full:"Hash-based Message Authentication Code — uses a hash function and secret key to verify message integrity and authenticity" },
  { abbr:"HSM", full:"Hardware Security Module — tamper-resistant hardware device for secure cryptographic key management" },
  { abbr:"IaC", full:"Infrastructure as Code" },
  { abbr:"IAM", full:"Identity and Access Management — processes and technologies for managing digital identities and access" },
  { abbr:"IDS", full:"Intrusion Detection System" },
  { abbr:"IPS", full:"Intrusion Prevention System" },
  { abbr:"IPsec", full:"Internet Protocol Security" },
  { abbr:"ISO 27001", full:"International standard specifying requirements for an Information Security Management System (ISMS)" },
  { abbr:"ISSAP", full:"Information Systems Security Architecture Professional — ISC² concentration for security architects" },
  { abbr:"JIT", full:"Just-In-Time (access) — granting elevated privileges only for the duration required, then revoking them" },
  { abbr:"LDAP", full:"Lightweight Directory Access Protocol — protocol for accessing and maintaining directory information services" },
  { abbr:"MFA", full:"Multi-Factor Authentication" },
  { abbr:"mTLS", full:"Mutual TLS — both client and server authenticate each other via certificates during TLS handshake" },
  { abbr:"NAC", full:"Network Access Control — technology enforcing security policies on devices before granting network access" },
  { abbr:"NIST CSF", full:"NIST Cybersecurity Framework — voluntary framework of standards for managing cybersecurity risk" },
  { abbr:"OAuth", full:"Open Authorization — open standard for access delegation, commonly used for token-based API authorization" },
  { abbr:"OCSP", full:"Online Certificate Status Protocol — real-time protocol for checking certificate revocation status" },
  { abbr:"OIDC", full:"OpenID Connect — identity layer on top of OAuth 2.0 providing user authentication" },
  { abbr:"PAM", full:"Privileged Access Management — solutions controlling, monitoring, and auditing privileged account usage" },
  { abbr:"PKI", full:"Public Key Infrastructure — framework of policies, procedures, and technologies managing digital certificates" },
  { abbr:"RBAC", full:"Role-Based Access Control — access rights assigned by job role rather than individual identity" },
  { abbr:"RSA", full:"Rivest-Shamir-Adleman — asymmetric cryptographic algorithm for encryption and digital signatures" },
  { abbr:"SABSA", full:"Sherwood Applied Business Security Architecture — enterprise security architecture framework aligning security with business objectives" },
  { abbr:"SAML", full:"Security Assertion Markup Language — XML-based standard for federated identity and SSO across organizations" },
  { abbr:"SASE", full:"Secure Access Service Edge — cloud-delivered convergence of network and security services at the edge" },
  { abbr:"SCIM", full:"System for Cross-domain Identity Management" },
  { abbr:"SDN", full:"Software-Defined Networking — separates control plane from data plane for centralized network management" },
  { abbr:"SDP", full:"Software-Defined Perimeter — security architecture making resources invisible until authenticated" },
  { abbr:"SD-WAN", full:"Software-Defined Wide Area Network — virtualized WAN architecture enabling centralized policy management" },
  { abbr:"SIEM", full:"Security Information and Event Management — platform aggregating and correlating logs for threat detection" },
  { abbr:"SOA", full:"Service-Oriented Architecture" },
  { abbr:"SOAR", full:"Security Orchestration, Automation, and Response — platform automating security operations workflows" },
  { abbr:"SOC", full:"Security Operations Center — team providing 24/7 security monitoring, detection, and incident response" },
  { abbr:"SSE", full:"Security Service Edge — security-focused subset of SASE including SWG, CASB, and ZTNA" },
  { abbr:"SSO", full:"Single Sign-On" },
  { abbr:"TLS", full:"Transport Layer Security — cryptographic protocol providing secure communications over networks" },
  { abbr:"TOGAF", full:"The Open Group Architecture Framework — enterprise architecture framework used alongside SABSA for security architecture" },
  { abbr:"TPM", full:"Trusted Platform Module" },
  { abbr:"UEBA", full:"User and Entity Behavior Analytics — detects anomalous behavior patterns indicating insider threats or compromised accounts" },
  { abbr:"VPN", full:"Virtual Private Network" },
  { abbr:"WAF", full:"Web Application Firewall — filters, monitors, and blocks malicious HTTP/S traffic to web applications" },
  { abbr:"XDR", full:"Extended Detection and Response — unified security platform integrating multiple telemetry sources" },
  { abbr:"ZTA", full:"Zero Trust Architecture — security model requiring continuous verification regardless of network location" },
  { abbr:"ZTNA", full:"Zero Trust Network Access — technology implementing zero trust principles for application access" },
  { abbr:"Zachman", full:"Zachman Framework (enterprise architecture ontology)" },
  { abbr:"ESB", full:"Enterprise Service Bus" },
  { abbr:"SPML", full:"Service Provisioning Markup Language" },
  { abbr:"XACML", full:"eXtensible Access Control Markup Language" },
  { abbr:"JWT", full:"JSON Web Token" },
  { abbr:"WebAuthn", full:"Web Authentication (W3C credential API)" },
  { abbr:"IdP", full:"Identity Provider" },
  { abbr:"SP", full:"Service Provider (federation relying party)" },
  { abbr:"STS", full:"Security Token Service" },
  { abbr:"RP", full:"Relying Party" },
  { abbr:"PBAC", full:"Policy-Based Access Control" },
  { abbr:"IGA", full:"Identity Governance and Administration" },
  { abbr:"CARTA", full:"Continuous Adaptive Risk and Trust Assessment" },
  { abbr:"RA", full:"Registration Authority" },
  { abbr:"VA", full:"Validation Authority" },
  { abbr:"SCEP", full:"Simple Certificate Enrollment Protocol" },
  { abbr:"EST", full:"Enrollment over Secure Transport" },
  { abbr:"ACME", full:"Automatic Certificate Management Environment" },
  { abbr:"KMS", full:"Key Management Service" },
  { abbr:"TEE", full:"Trusted Execution Environment" },
  { abbr:"KEK", full:"Key Encryption Key" },
  { abbr:"DEK", full:"Data Encryption Key" },
  { abbr:"PFS", full:"Perfect Forward Secrecy" },
  { abbr:"ECDHE", full:"Elliptic Curve Diffie-Hellman Ephemeral" },
  { abbr:"ECDSA", full:"Elliptic Curve Digital Signature Algorithm" },
  { abbr:"EdDSA", full:"Edwards-curve Digital Signature Algorithm" },
  { abbr:"HKDF", full:"HMAC-based Key Derivation Function" },
  { abbr:"PBKDF2", full:"Password-Based Key Derivation Function 2" },
  { abbr:"AEAD", full:"Authenticated Encryption with Associated Data" },
  { abbr:"PQC", full:"Post-Quantum Cryptography" },
  { abbr:"IKE", full:"Internet Key Exchange" },
  { abbr:"ISAKMP", full:"Internet Security Association and Key Management Protocol" },
  { abbr:"ESP", full:"Encapsulating Security Payload" },
  { abbr:"AH", full:"Authentication Header (IPsec)" },
  { abbr:"VXLAN", full:"Virtual Extensible LAN" },
  { abbr:"NFV", full:"Network Functions Virtualization" },
  { abbr:"TACACS+", full:"Terminal Access Controller Access-Control System Plus" },
  { abbr:"DNSSEC", full:"Domain Name System Security Extensions" },
  { abbr:"DMARC", full:"Domain-based Message Authentication, Reporting and Conformance" },
  { abbr:"IRM", full:"Information Rights Management" }
];
ACRONYMS_ISSAP.sort((a, b) => a.abbr.localeCompare(b.abbr, undefined, { sensitivity: 'base' }));
