const ACRONYMS_CCZT = [
  { abbr:"ABAC", full:"Attribute-Based Access Control" },
  { abbr:"API", full:"Application Programming Interface" },
  { abbr:"BYOD", full:"Bring Your Own Device" },
  { abbr:"CARTA", full:"Continuous Adaptive Risk and Trust Assessment" },
  { abbr:"CASB", full:"Cloud Access Security Broker" },
  { abbr:"CCZT", full:"Certificate of Competence in Zero Trust" },
  { abbr:"CIEM", full:"Cloud Infrastructure Entitlement Management" },
  { abbr:"CISA", full:"Cybersecurity and Infrastructure Security Agency" },
  { abbr:"CSA", full:"Cloud Security Alliance" },
  { abbr:"DAAS", full:"Data, Applications, Assets, and Services (the protect surface)" },
  { abbr:"DLP", full:"Data Loss Prevention" },
  { abbr:"EDR", full:"Endpoint Detection and Response" },
  { abbr:"IAM", full:"Identity and Access Management" },
  { abbr:"IdP", full:"Identity Provider" },
  { abbr:"JIT", full:"Just-In-Time (access)" },
  { abbr:"LPA", full:"Least Privilege Access" },
  { abbr:"MDM", full:"Mobile Device Management" },
  { abbr:"MFA", full:"Multi-Factor Authentication" },
  { abbr:"mTLS", full:"Mutual Transport Layer Security" },
  { abbr:"NGFW", full:"Next-Generation Firewall" },
  { abbr:"NIST", full:"National Institute of Standards and Technology" },
  { abbr:"PA", full:"Policy Administrator" },
  { abbr:"PAM", full:"Privileged Access Management" },
  { abbr:"PBAC", full:"Policy-Based Access Control" },
  { abbr:"PDP", full:"Policy Decision Point" },
  { abbr:"PE", full:"Policy Engine" },
  { abbr:"PEP", full:"Policy Enforcement Point" },
  { abbr:"PKI", full:"Public Key Infrastructure" },
  { abbr:"RBAC", full:"Role-Based Access Control" },
  { abbr:"SASE", full:"Secure Access Service Edge" },
  { abbr:"SDP", full:"Software-Defined Perimeter" },
  { abbr:"SIEM", full:"Security Information and Event Management" },
  { abbr:"SOAR", full:"Security Orchestration, Automation, and Response" },
  { abbr:"SSE", full:"Security Service Edge" },
  { abbr:"SSO", full:"Single Sign-On" },
  { abbr:"UEBA", full:"User and Entity Behavior Analytics" },
  { abbr:"VPN", full:"Virtual Private Network" },
  { abbr:"XDR", full:"Extended Detection and Response" },
  { abbr:"ZT", full:"Zero Trust" },
  { abbr:"ZTA", full:"Zero Trust Architecture" },
  { abbr:"ZTMM", full:"Zero Trust Maturity Model (CISA)" },
  { abbr:"ZTNA", full:"Zero Trust Network Access" },
];
ACRONYMS_CCZT.sort((a, b) => a.abbr.localeCompare(b.abbr, undefined, { sensitivity: 'base' }));
