const ACRONYMS_CISA = [
  { abbr:"ACL", full:"Access Control List" },
  { abbr:"AIS", full:"Automated Information System" },
  { abbr:"API", full:"Application Programming Interface" },
  { abbr:"APT", full:"Advanced Persistent Threat" },
  { abbr:"AUP", full:"Acceptable Use Policy" },
  { abbr:"BCP", full:"Business Continuity Plan" },
  { abbr:"BIA", full:"Business Impact Analysis" },
  { abbr:"CAAT", full:"Computer-Assisted Audit Technique" },
  { abbr:"CAE", full:"Chief Audit Executive" },
  { abbr:"CAPM", full:"Capability and Process Maturity Model" },
  { abbr:"CAS", full:"Complex Adaptive System" },
  { abbr:"CISA", full:"Certified Information Systems Auditor" },
  { abbr:"CMMI", full:"Capability Maturity Model Integration" },
  { abbr:"COBIT", full:"Control Objectives for Information and Related Technologies" },
  { abbr:"COI", full:"Conflict of Interest" },
  { abbr:"COSO", full:"Committee of Sponsoring Organizations of the Treadway Commission" },
  { abbr:"COTS", full:"Commercial Off-the-Shelf" },
  { abbr:"CRM", full:"Customer Relationship Management" },
  { abbr:"CSA", full:"Control Self-Assessment" },
  { abbr:"DLP", full:"Data Loss Prevention" },
  { abbr:"DRP", full:"Disaster Recovery Plan" },
  { abbr:"EA", full:"Enterprise Architecture" },
  { abbr:"EAM", full:"Enterprise Architecture Management" },
  { abbr:"ERP", full:"Enterprise Resource Planning" },
  { abbr:"ESA", full:"Enterprise Security Architecture" },
  { abbr:"FISMA", full:"Federal Information Security Management Act" },
  { abbr:"GAAP", full:"Generally Accepted Accounting Principles" },
  { abbr:"GAS", full:"Generalized Audit Software" },
  { abbr:"GDPR", full:"General Data Protection Regulation" },
  { abbr:"GRC", full:"Governance, Risk, and Compliance" },
  { abbr:"HIPAA", full:"Health Insurance Portability and Accountability Act" },
  { abbr:"IAM", full:"Identity and Access Management" },
  { abbr:"ICS", full:"Industrial Control System" },
  { abbr:"IDS", full:"Intrusion Detection System" },
  { abbr:"IPS", full:"Intrusion Prevention System" },
  { abbr:"IS", full:"Information Systems" },
  { abbr:"ISACA", full:"Information Systems Audit and Control Association" },
  { abbr:"ISMS", full:"Information Security Management System" },
  { abbr:"ISO", full:"International Organization for Standardization" },
  { abbr:"ISO 27001", full:"International Organization for Standardization 27001 (Information Security Management)" },
  { abbr:"ITAF", full:"IT Assurance Framework" },
  { abbr:"ITAM", full:"IT Asset Management" },
  { abbr:"ITGC", full:"IT General Controls" },
  { abbr:"ITIL", full:"Information Technology Infrastructure Library" },
  { abbr:"KPI", full:"Key Performance Indicator" },
  { abbr:"KRI", full:"Key Risk Indicator" },
  { abbr:"MFA", full:"Multi-Factor Authentication" },
  { abbr:"NDA", full:"Non-Disclosure Agreement" },
  { abbr:"NIST", full:"National Institute of Standards and Technology" },
  { abbr:"OLA", full:"Operational Level Agreement" },
  { abbr:"PCAOB", full:"Public Company Accounting Oversight Board" },
  { abbr:"PCI DSS", full:"Payment Card Industry Data Security Standard" },
  { abbr:"PKI", full:"Public Key Infrastructure" },
  { abbr:"RACI", full:"Responsible, Accountable, Consulted, Informed" },
  { abbr:"RBAC", full:"Role-Based Access Control" },
  { abbr:"RFC", full:"Request for Change" },
  { abbr:"RMF", full:"Risk Management Framework" },
  { abbr:"ROI", full:"Return on Investment" },
  { abbr:"RPO", full:"Recovery Point Objective" },
  { abbr:"RTO", full:"Recovery Time Objective" },
  { abbr:"SDLC", full:"Software/Systems Development Life Cycle" },
  { abbr:"SIEM", full:"Security Information and Event Management" },
  { abbr:"SLA", full:"Service Level Agreement" },
  { abbr:"SOC", full:"Service Organization Control (report)" },
  { abbr:"SOD", full:"Segregation of Duties" },
  { abbr:"SOP", full:"Standard Operating Procedure" },
  { abbr:"SOX", full:"Sarbanes-Oxley Act" },
  { abbr:"SSO", full:"Single Sign-On" },
  { abbr:"TCO", full:"Total Cost of Ownership" },
  { abbr:"TOR", full:"Terms of Reference" },
  { abbr:"UAT", full:"User Acceptance Testing" },
  { abbr:"UPS", full:"Uninterruptible Power Supply" },
  { abbr:"VA", full:"Vulnerability Assessment" },
  { abbr:"VPN", full:"Virtual Private Network" },
  { abbr:"WAF", full:"Web Application Firewall" },
  { abbr:"WBS", full:"Work Breakdown Structure" },
  { abbr:"GAAS", full:"Generally Accepted Auditing Standards" },
  { abbr:"GAGAS", full:"Generally Accepted Government Auditing Standards (Yellow Book)" },
  { abbr:"ICFR", full:"Internal Control over Financial Reporting" },
  { abbr:"SSAE 18", full:"Statement on Standards for Attestation Engagements No. 18" },
  { abbr:"ISAE 3402", full:"International Standard on Assurance Engagements 3402" },
  { abbr:"SOC 1", full:"System and Organization Controls 1 (financial reporting controls)" },
  { abbr:"SOC 2", full:"System and Organization Controls 2 (trust services criteria)" },
  { abbr:"TSC", full:"Trust Services Criteria (AICPA)" },
  { abbr:"RCM", full:"Risk Control Matrix" },
  { abbr:"RCSA", full:"Risk and Control Self-Assessment" },
  { abbr:"KGI", full:"Key Goal Indicator" },
  { abbr:"KCI", full:"Key Control Indicator" },
  { abbr:"MTD", full:"Maximum Tolerable Downtime" },
  { abbr:"WRT", full:"Work Recovery Time" },
  { abbr:"SODA", full:"Separation of Duties Analysis" },
  { abbr:"CMDB", full:"Configuration Management Database" },
  { abbr:"CAB", full:"Change Advisory Board" },
  { abbr:"ITAC", full:"Information Technology Application Controls" },
  { abbr:"CI", full:"Configuration Item" },
  { abbr:"SoW", full:"Statement of Work" },
  { abbr:"MoU", full:"Memorandum of Understanding" },
  { abbr:"OLAP", full:"Online Analytical Processing" },
  { abbr:"OLTP", full:"Online Transaction Processing" },
  { abbr:"ETL", full:"Extract, Transform, Load" },
  { abbr:"DW", full:"Data Warehouse" },
  { abbr:"RDBMS", full:"Relational Database Management System" },
  { abbr:"EDI", full:"Electronic Data Interchange" },
  { abbr:"ESB", full:"Enterprise Service Bus" },
  { abbr:"SOA", full:"Service-Oriented Architecture" },
  { abbr:"PAM", full:"Privileged Access Management" },
  { abbr:"CRL", full:"Certificate Revocation List" },
  { abbr:"OCSP", full:"Online Certificate Status Protocol" },
  { abbr:"NAC", full:"Network Access Control" },
  { abbr:"CVSS", full:"Common Vulnerability Scoring System" },
  { abbr:"CVE", full:"Common Vulnerabilities and Exposures" },
  { abbr:"GLBA", full:"Gramm-Leach-Bliley Act" },
  { abbr:"FedRAMP", full:"Federal Risk and Authorization Management Program" },
  { abbr:"ISO 22301", full:"ISO Standard for Business Continuity Management Systems" },
  { abbr:"ISO 31000", full:"ISO Standard for Risk Management" },
  { abbr:"ISO 38500", full:"ISO Standard for Corporate Governance of Information Technology" },
  { abbr:"CGEIT", full:"Certified in the Governance of Enterprise IT (ISACA)" },
  { abbr:"CRISC", full:"Certified in Risk and Information Systems Control (ISACA)" }
];
ACRONYMS_CISA.sort((a, b) => a.abbr.localeCompare(b.abbr, undefined, { sensitivity: 'base' }));
