const ACRONYMS_CHFI = [
  { term:"CHFI", definition:"Computer Hacking Forensic Investigator — EC-Council certification for digital forensics professionals" },
  { term:"EC-Council", definition:"International Council of E-Commerce Consultants — organization behind CHFI, CEH, CPENT, and ECIH certifications" },
  { term:"DFIR", definition:"Digital Forensics and Incident Response — combined discipline covering investigation and active incident management" },
  { term:"FTK", definition:"Forensic Toolkit — commercial digital forensics software suite by AccessData/Exterro" },
  { term:"EnCase", definition:"Commercial digital forensics software by OpenText, widely used in law enforcement" },
  { term:"IOC", definition:"Indicator of Compromise — artifact observed on a system indicating probable intrusion" },
  { term:"PCAP", definition:"Packet Capture — raw network traffic data captured for analysis" },
  { term:"MFT", definition:"Master File Table — NTFS structure recording metadata for every file on a volume" },
  { term:"FAT", definition:"File Allocation Table — legacy Windows filesystem storing file location data" },
  { term:"NTFS", definition:"New Technology File System — primary Windows filesystem supporting journaling and advanced metadata" },
  { term:"EXT4", definition:"Fourth Extended Filesystem — primary Linux filesystem with journaling support" },
  { term:"APFS", definition:"Apple File System — macOS and iOS filesystem replacing HFS+, supporting encryption and snapshots" },
  { term:"HFS+", definition:"Hierarchical File System Plus — legacy Apple filesystem replaced by APFS" },
  { term:"ADS", definition:"Alternate Data Streams — NTFS feature allowing data to be hidden within another file's metadata" },
  { term:"MBR", definition:"Master Boot Record — first sector of a storage device containing partition table and bootloader" },
  { term:"GPT", definition:"GUID Partition Table — modern partitioning standard replacing MBR, part of UEFI specification" },
  { term:"UEFI", definition:"Unified Extensible Firmware Interface — modern firmware interface replacing BIOS" },
  { term:"RAM", definition:"Random Access Memory — volatile memory losing contents when power is removed; priority for live forensics" },
  { term:"VSS", definition:"Volume Shadow Copy Service — Windows feature creating point-in-time snapshots of volumes" },
  { term:"LNK", definition:"Windows shortcut file — contains metadata about recently accessed files including timestamps and path" },
  { term:"USN", definition:"Update Sequence Number Journal — NTFS journal recording file system changes" },
  { term:"SAM", definition:"Security Account Manager — Windows database storing local user account credentials" },
  { term:"NTLM", definition:"NT LAN Manager — Windows challenge-response authentication protocol" },
  { term:"MD5", definition:"Message Digest 5 — 128-bit hash algorithm used for file integrity verification in forensics" },
  { term:"SHA-1", definition:"Secure Hash Algorithm 1 — 160-bit hash; used in forensics though cryptographically deprecated" },
  { term:"SHA-256", definition:"Secure Hash Algorithm 256-bit — current standard hash algorithm for forensic file integrity" },
  { term:"WMI", definition:"Windows Management Instrumentation — Windows infrastructure for management and scripting; abused by attackers" },
  { term:"PST", definition:"Personal Storage Table — Outlook email archive file format containing messages, contacts, and calendar items" },
  { term:"OST", definition:"Offline Storage Table — local copy of Exchange mailbox data in Outlook" },
  { term:"SMTP", definition:"Simple Mail Transfer Protocol — standard protocol for sending email" },
  { term:"IMAP", definition:"Internet Message Access Protocol — email retrieval protocol leaving messages on server" },
  { term:"IP", definition:"Internet Protocol — fundamental network protocol providing addressing and routing" },
  { term:"MAC", definition:"Media Access Control — unique hardware identifier assigned to network interface cards" },
  { term:"ARP", definition:"Address Resolution Protocol — maps IP addresses to MAC addresses on local networks" },
  { term:"DNS", definition:"Domain Name System — translates domain names to IP addresses" },
  { term:"DHCP", definition:"Dynamic Host Configuration Protocol — automatically assigns IP addresses to network devices" },
  { term:"HTTP/S", definition:"HyperText Transfer Protocol (Secure) — protocol for web communication, HTTPS adds TLS encryption" },
  { term:"TOR", definition:"The Onion Router — anonymity network routing traffic through multiple encrypted relay nodes" },
  { term:"VPN", definition:"Virtual Private Network — encrypted tunnel for secure remote network connectivity" },
  { term:"OSINT", definition:"Open-Source Intelligence — intelligence gathered from publicly available sources" },
  { term:"CVE", definition:"Common Vulnerabilities and Exposures — standardized identifiers for known security vulnerabilities" },
  { term:"APT", definition:"Advanced Persistent Threat — sophisticated, long-term targeted attack by skilled adversaries" },
  { term:"C2", definition:"Command and Control — infrastructure attackers use to communicate with compromised systems" },
  { term:"RAT", definition:"Remote Access Trojan — malware providing covert remote access to a compromised system" },
  { term:"SIEM", definition:"Security Information and Event Management — log aggregation and correlation platform" },
  { term:"CoC", definition:"Chain of Custody — documented chronological handling of evidence ensuring integrity" },
  { term:"SOP", definition:"Standard Operating Procedure — documented step-by-step process for evidence handling" },
  { term:"RFC", definition:"Request for Comments — IETF documents defining internet standards and protocols" },
  { term:"SQL", definition:"Structured Query Language — language for database management and querying" },
  { term:"XSS", definition:"Cross-Site Scripting — web vulnerability injecting malicious scripts into web pages" },
  { term:"SQLi", definition:"SQL Injection — attack inserting malicious SQL code into application queries" }
];
