const ACRONYMS_CPENT = [
  { abbr:"0-day", full:"Zero-Day Vulnerability — unpatched vulnerability unknown to the vendor at time of exploitation" },
  { abbr:"AD", full:"Active Directory — Microsoft directory service; primary target in Windows network pentests" },
  { abbr:"ARP", full:"Address Resolution Protocol" },
  { abbr:"ASLR", full:"Address Space Layout Randomization" },
  { abbr:"AV", full:"Antivirus — security software detecting and removing malware; must be evaded in pentest" },
  { abbr:"BloodHound", full:"Tool analyzing Active Directory relationships and attack paths to privileged accounts" },
  { abbr:"C2", full:"Command and Control — infrastructure for communicating with compromised systems during an engagement" },
  { abbr:"CPENT", full:"Certified Penetration Testing Professional — EC-Council advanced penetration testing certification" },
  { abbr:"CSRF", full:"Cross-Site Request Forgery — tricking authenticated users into performing unintended actions" },
  { abbr:"CVE", full:"Common Vulnerabilities and Exposures — standardized identifiers for publicly known vulnerabilities" },
  { abbr:"CVSS", full:"Common Vulnerability Scoring System — standardized framework for rating vulnerability severity" },
  { abbr:"DACL", full:"Discretionary Access Control List" },
  { abbr:"DC", full:"Domain Controller — server managing Active Directory authentication and policies" },
  { abbr:"DCSync", full:"Active Directory attack simulating domain controller replication to dump password hashes" },
  { abbr:"DDoS", full:"Distributed Denial of Service" },
  { abbr:"DEP", full:"Data Execution Prevention" },
  { abbr:"DNP3", full:"Distributed Network Protocol 3" },
  { abbr:"DNS", full:"Domain Name System — maps domain names to IP addresses; critical source of recon information" },
  { abbr:"EDR", full:"Endpoint Detection and Response — advanced security platform pentests must evade" },
  { abbr:"FTP", full:"File Transfer Protocol — insecure file transfer protocol transmitting credentials in cleartext" },
  { abbr:"HUMINT", full:"Human Intelligence — intelligence gathered from human sources through social engineering" },
  { abbr:"IDOR", full:"Insecure Direct Object Reference — accessing unauthorized resources by manipulating object identifiers" },
  { abbr:"IoT", full:"Internet of Things — network-connected physical devices; increasing pentest target category" },
  { abbr:"Kerberos", full:"Network authentication protocol used by Active Directory; target of Kerberoasting attacks" },
  { abbr:"LDAP", full:"Lightweight Directory Access Protocol — directory service protocol used in Active Directory" },
  { abbr:"LFI", full:"Local File Inclusion" },
  { abbr:"LOLBAS", full:"Living Off the Land Binaries and Scripts — using native OS tools to avoid detection" },
  { abbr:"LPE", full:"Local Privilege Escalation — technique gaining higher privileges on an already-accessed system" },
  { abbr:"LSASS", full:"Local Security Authority Subsystem Service" },
  { abbr:"Metasploit", full:"Open-source penetration testing framework providing exploit modules and payloads" },
  { abbr:"Mimikatz", full:"Post-exploitation tool extracting credentials from Windows memory" },
  { abbr:"MITM", full:"Man-in-the-Middle" },
  { abbr:"MSF", full:"Metasploit Framework — modular exploitation platform for penetration testers" },
  { abbr:"NIST", full:"National Institute of Standards and Technology" },
  { abbr:"Nmap", full:"Network Mapper — open-source tool for network discovery and security auditing" },
  { abbr:"NTLM", full:"NT LAN Manager — Windows authentication protocol vulnerable to pass-the-hash attacks" },
  { abbr:"OSINT", full:"Open-Source Intelligence — gathering target information from publicly available sources" },
  { abbr:"OSSTMM", full:"Open Source Security Testing Methodology Manual" },
  { abbr:"OT", full:"Operational Technology — industrial control systems and SCADA networks" },
  { abbr:"OWASP", full:"Open Web Application Security Project — organization producing web application security standards" },
  { abbr:"OWASP Top 10", full:"Annually updated list of the most critical web application security risks" },
  { abbr:"PLC", full:"Programmable Logic Controller" },
  { abbr:"PMKID", full:"Pairwise Master Key Identifier" },
  { abbr:"PoC", full:"Proof of Concept — code demonstrating a vulnerability is exploitable" },
  { abbr:"PT", full:"Penetration Testing — authorized simulated attack to evaluate security defenses" },
  { abbr:"PTES", full:"Penetration Testing Execution Standard" },
  { abbr:"PTH", full:"Pass-the-Hash — attack using captured NTLM hash to authenticate without cracking the password" },
  { abbr:"PtT", full:"Pass-the-Ticket — Kerberos attack using captured tickets to authenticate as another user" },
  { abbr:"RAT", full:"Remote Access Trojan — implant providing covert remote access to compromised hosts" },
  { abbr:"RCE", full:"Remote Code Execution — vulnerability allowing arbitrary code execution on a target system" },
  { abbr:"RDP", full:"Remote Desktop Protocol — Windows remote management protocol frequently targeted in pentests" },
  { abbr:"RECON", full:"Reconnaissance — information-gathering phase of a penetration test" },
  { abbr:"RFI", full:"Remote File Inclusion" },
  { abbr:"RoE", full:"Rules of Engagement — agreed scope, boundaries, and permitted actions for a penetration test" },
  { abbr:"ROP", full:"Return-Oriented Programming" },
  { abbr:"SCADA", full:"Supervisory Control and Data Acquisition — industrial control system for monitoring physical infrastructure" },
  { abbr:"SEH", full:"Structured Exception Handler" },
  { abbr:"SIGINT", full:"Signals Intelligence — intelligence gathered by intercepting electronic signals" },
  { abbr:"SMB", full:"Server Message Block — Windows file sharing protocol; target of EternalBlue and similar exploits" },
  { abbr:"SNMP", full:"Simple Network Management Protocol — network device management protocol; v1/v2 community strings are weak" },
  { abbr:"SoW", full:"Statement of Work — contract defining deliverables, scope, timeline, and payment for a pentest engagement" },
  { abbr:"SPN", full:"Service Principal Name" },
  { abbr:"SQLi", full:"SQL Injection — inserting malicious SQL into application input fields to manipulate databases" },
  { abbr:"SSH", full:"Secure Shell — encrypted protocol for remote management; default port 22" },
  { abbr:"SSRF", full:"Server-Side Request Forgery — tricking a server into making requests to internal resources" },
  { abbr:"UAC", full:"User Account Control" },
  { abbr:"WHOIS", full:"Protocol for querying databases storing registered domain name owners and contact information" },
  { abbr:"WiFi", full:"Wireless networking standard; WEP/WPA2-TKIP vulnerable to cracking attacks" },
  { abbr:"WinRM", full:"Windows Remote Management" },
  { abbr:"WMI", full:"Windows Management Instrumentation" },
  { abbr:"WPA", full:"Wi-Fi Protected Access" },
  { abbr:"WPS", full:"Wi-Fi Protected Setup" },
  { abbr:"XSS", full:"Cross-Site Scripting — injecting malicious scripts into web pages viewed by other users" },
  { abbr:"XXE", full:"XML External Entity — attack exploiting XML parsers to access local files or make network requests" },
  { abbr:"JOP", full:"Jump-Oriented Programming (gadget-chaining variant using indirect jumps)" },
  { abbr:"NOP", full:"No Operation (sled used in exploit payloads)" },
  { abbr:"NX", full:"No-eXecute (CPU bit marking pages non-executable)" },
  { abbr:"PIE", full:"Position Independent Executable" },
  { abbr:"RELRO", full:"Relocation Read-Only (GOT hardening mitigation)" },
  { abbr:"GOT", full:"Global Offset Table (dynamic linking overwrite target)" },
  { abbr:"PLT", full:"Procedure Linkage Table" },
  { abbr:"SMEP", full:"Supervisor Mode Execution Prevention" },
  { abbr:"SMAP", full:"Supervisor Mode Access Prevention" },
  { abbr:"CFG", full:"Control Flow Guard (Windows control-flow integrity mitigation)" },
  { abbr:"SSTI", full:"Server-Side Template Injection" },
  { abbr:"CSP", full:"Content Security Policy" },
  { abbr:"SOP", full:"Same-Origin Policy" },
  { abbr:"CORS", full:"Cross-Origin Resource Sharing" },
  { abbr:"JWT", full:"JSON Web Token" },
  { abbr:"SAML", full:"Security Assertion Markup Language" },
  { abbr:"OIDC", full:"OpenID Connect" },
  { abbr:"LLMNR", full:"Link-Local Multicast Name Resolution (poisoning target)" },
  { abbr:"NBT-NS", full:"NetBIOS Name Service (spoofing/poisoning target)" },
  { abbr:"LDAPS", full:"Lightweight Directory Access Protocol over SSL/TLS" },
  { abbr:"AD CS", full:"Active Directory Certificate Services" },
  { abbr:"ADFS", full:"Active Directory Federation Services" },
  { abbr:"GPO", full:"Group Policy Object" },
  { abbr:"GPP", full:"Group Policy Preferences (cpassword credential exposure)" },
  { abbr:"TGT", full:"Ticket Granting Ticket (Kerberos)" },
  { abbr:"TGS", full:"Ticket Granting Service ticket (Kerberos)" },
  { abbr:"PAC", full:"Privilege Attribute Certificate (Kerberos authorization data)" },
  { abbr:"DPAPI", full:"Data Protection API (Windows secret storage)" },
  { abbr:"SAM", full:"Security Account Manager (Windows local hash database)" },
  { abbr:"AMSI", full:"Antimalware Scan Interface" },
  { abbr:"WDAC", full:"Windows Defender Application Control" },
  { abbr:"PPL", full:"Protected Process Light" },
  { abbr:"DCOM", full:"Distributed Component Object Model (lateral movement vector)" },
  { abbr:"EAP", full:"Extensible Authentication Protocol" },
  { abbr:"PEAP", full:"Protected Extensible Authentication Protocol" },
  { abbr:"BSSID", full:"Basic Service Set Identifier (access point MAC address)" },
  { abbr:"UART", full:"Universal Asynchronous Receiver-Transmitter (hardware debug interface)" },
  { abbr:"JTAG", full:"Joint Test Action Group (chip debug/boundary-scan interface)" },
  { abbr:"MQTT", full:"Message Queuing Telemetry Transport (IoT protocol)" },
  { abbr:"CoAP", full:"Constrained Application Protocol (IoT protocol)" },
  { abbr:"HMI", full:"Human-Machine Interface (ICS/SCADA component)" }
];
ACRONYMS_CPENT.sort((a, b) => a.abbr.localeCompare(b.abbr, undefined, { sensitivity: 'base' }));
