const ACRONYMS_ECIH = [
  { term:"ECIH", definition:"EC-Council Certified Incident Handler — certification covering incident response lifecycle management" },
  { term:"IH", definition:"Incident Handler — professional responsible for managing and responding to cybersecurity incidents" },
  { term:"IRT", definition:"Incident Response Team — dedicated group handling security incidents within an organization" },
  { term:"CSIRT", definition:"Computer Security Incident Response Team — organized group responding to cybersecurity incidents" },
  { term:"CERT", definition:"Computer Emergency Response Team — term for incident response teams, originating from Carnegie Mellon CERT/CC" },
  { term:"SOC", definition:"Security Operations Center — 24/7 monitoring team detecting and escalating security events" },
  { term:"IR", definition:"Incident Response — organized approach to addressing and managing security incidents" },
  { term:"IRP", definition:"Incident Response Plan — documented procedures for detecting, containing, and recovering from incidents" },
  { term:"TTX", definition:"Tabletop Exercise — scenario-based discussion exercise testing incident response plans" },
  { term:"PICERL", definition:"Preparation, Identification, Containment, Eradication, Recovery, Lessons Learned — incident response lifecycle model" },
  { term:"OODA", definition:"Observe, Orient, Decide, Act — decision-making loop applied to incident response" },
  { term:"TTP", definition:"Tactics, Techniques, and Procedures — categorization of adversary behavior from MITRE ATT&CK" },
  { term:"IOC", definition:"Indicator of Compromise — forensic artifact indicating a system breach has occurred" },
  { term:"IOA", definition:"Indicator of Attack — real-time evidence suggesting an active attack in progress" },
  { term:"EDR", definition:"Endpoint Detection and Response — security platform detecting and responding to endpoint threats" },
  { term:"XDR", definition:"Extended Detection and Response — unified threat detection across endpoint, network, and cloud" },
  { term:"SOAR", definition:"Security Orchestration, Automation, and Response — automates incident response workflows" },
  { term:"SIEM", definition:"Security Information and Event Management — aggregates logs and generates security alerts" },
  { term:"C2", definition:"Command and Control — attacker infrastructure used to communicate with compromised hosts" },
  { term:"APT", definition:"Advanced Persistent Threat — sophisticated, long-term targeted attack campaign" },
  { term:"DDoS", definition:"Distributed Denial of Service — overwhelming a system with traffic from multiple sources to disrupt availability" },
  { term:"DoS", definition:"Denial of Service — attack making a system or service unavailable to legitimate users" },
  { term:"RAT", definition:"Remote Access Trojan — malware giving attackers covert remote control of a compromised system" },
  { term:"RCE", definition:"Remote Code Execution — vulnerability allowing attackers to run arbitrary code on a target system" },
  { term:"LFI/RFI", definition:"Local/Remote File Inclusion — web vulnerabilities including unauthorized files in application execution" },
  { term:"SQLI", definition:"SQL Injection — attack inserting malicious SQL into database queries" },
  { term:"XSS", definition:"Cross-Site Scripting — attack injecting malicious scripts into web pages viewed by other users" },
  { term:"CSRF", definition:"Cross-Site Request Forgery — tricks authenticated users into performing unintended actions on a web app" },
  { term:"MitM", definition:"Man-in-the-Middle — attack intercepting and potentially modifying communications between two parties" },
  { term:"PCAP", definition:"Packet Capture — raw network traffic data captured for incident investigation" },
  { term:"DFIR", definition:"Digital Forensics and Incident Response — combined discipline for investigating and responding to incidents" },
  { term:"CoC", definition:"Chain of Custody — documented evidence handling record ensuring legal admissibility" },
  { term:"TTL", definition:"Time to Live — network value limiting packet lifetime; also used in threat intelligence feeds" },
  { term:"CVE", definition:"Common Vulnerabilities and Exposures — standard identifier for publicly known vulnerabilities" },
  { term:"CVSS", definition:"Common Vulnerability Scoring System — standardized severity scoring for vulnerabilities" },
  { term:"BEC", definition:"Business Email Compromise — fraud targeting organizations via compromised or spoofed email" },
  { term:"MFA", definition:"Multi-Factor Authentication — requiring multiple factors to verify user identity" },
  { term:"VPN", definition:"Virtual Private Network — encrypted tunnel for secure remote connectivity" },
  { term:"NGFW", definition:"Next-Generation Firewall — advanced firewall with application awareness and intrusion prevention" },
  { term:"IDS", definition:"Intrusion Detection System — monitors for and alerts on suspicious activity" },
  { term:"IPS", definition:"Intrusion Prevention System — monitors and actively blocks malicious activity" },
  { term:"OSINT", definition:"Open-Source Intelligence — intelligence gathered from publicly available sources" },
  { term:"SLA", definition:"Service Level Agreement — defines expected response times and service standards" },
  { term:"RCA", definition:"Root Cause Analysis — process determining underlying cause of an incident" },
  { term:"PIR", definition:"Post-Incident Review — formal review after incident closure to identify improvements" },
  { term:"NIST SP 800-61", definition:"NIST Computer Security Incident Handling Guide — authoritative guidance for incident response" }
];
