const ACRONYMS_CCSP = [
  { abbr:"2FA",      full:"Two Factor Authentication" },
  { abbr:"3DES",     full:"Triple Data Encryption Algorithm" },
  { abbr:"3FA",      full:"Three-Factor Authentication" },
  { abbr:"3GPP",     full:"3rd Generation Partnership Project" },
  { abbr:"3GPP2",    full:"3rd Generation Partnership Project 2" },
  { abbr:"3PAO",     full:"Third Party Assessor Organization" },
  { abbr:"4FA",      full:"Four-Factor Authentication" },
  { abbr:"A&A",      full:"Assessment and Authorization" },
  { abbr:"AAA",      full:"Authentication, Authorization, Accounting" },
  { abbr:"AAL",      full:"Authentication Assurance Level" },
  { abbr:"ABAC",     full:"Attribute Based Access Control" },
  { abbr:"ABB",      full:"Architecture Building Blocks" },
  { abbr:"ACA",      full:"Affordable Care Act" },
  { abbr:"ACCM",     full:"Asset Configuration Compliance Module" },
  { abbr:"ACE",      full:"Access Control Entry" },
  { abbr:"ACHC",     full:"Accreditation of Healthcare Organizations" },
  { abbr:"ACID",     full:"Atomicity, Consistency, Isolation, Durability" },
  { abbr:"ACK",      full:"Acknowledgement" },
  { abbr:"ACL",      full:"Access Control List" },
  { abbr:"ACO",      full:"Accountable Care Organizations" },
  { abbr:"AD",       full:"Active Directory" },
  { abbr:"ADB",      full:"Android Debug Bridge" },
  { abbr:"ADFS",     full:"Active Directory Federation Services" },
  { abbr:"ADH",      full:"Anonymous Diffie-Hellman" },
  { abbr:"ADT",      full:"Admissions Discharge, and Transfer / Android Development Tools" },
  { abbr:"AES",      full:"Advanced Encryption Standard" },
  { abbr:"AES-256",  full:"Advanced Encryption Standard 256" },
  { abbr:"AES-512",  full:"Advanced Encryption Standard 512" },
  { abbr:"AG",       full:"Attorney General" },
  { abbr:"AH",       full:"Authentication Header" },
  { abbr:"AI",       full:"Artificial Intelligence" },
  { abbr:"AICPA",    full:"American Institute of Certified Public Accountants" },
  { abbr:"AIS",      full:"Artificial Intelligence System / Automated Information Systems" },
  { abbr:"AJAX",     full:"Asynchronous Javascript and XML" },
  { abbr:"ALE",      full:"Annualized Loss Expectancy" },
  { abbr:"AMPS",     full:"Advanced Mobile Phone System / Service" },
  { abbr:"ANF",      full:"Application Normative Framework" },
  { abbr:"ANSI",     full:"American National Standards Institute" },
  { abbr:"AO",       full:"Authorizing Official" },
  { abbr:"AoA",      full:"Analysis of Alternatives" },
  { abbr:"AP",       full:"Access Point" },
  { abbr:"APC",      full:"Ambulatory Payment Classification" },
  { abbr:"APEC",     full:"Asia-Pacific Economic Cooperation" },
  { abbr:"API",      full:"Application Programming Interface" },
  { abbr:"APK",      full:"Android Package Kit" },
  { abbr:"APT",      full:"Advanced Persistent Threat" },
  { abbr:"ARO",      full:"Annualized Rate of Occurrence" },
  { abbr:"ARP",      full:"Address Resolution Protocol" },
  { abbr:"ARRA",     full:"American Recovery and Reinvestment Act" },
  { abbr:"ASCII",    full:"American Standard Code for Information Interchange" },
  { abbr:"ASLR",     full:"Address Space Layout Randomization" },
  { abbr:"ASP",      full:"Application Service Provider" },
  { abbr:"AST",      full:"Abstract Syntax Tree" },
  { abbr:"ASV",      full:"Approved Scanning Vendor" },
  { abbr:"ASVS",     full:"Application Security Verification Standards" },
  { abbr:"ATA",      full:"Advanced Technology Attachment" },
  { abbr:"ATM",      full:"Asynchronous Transfer Mode / Automatic Teller Machine" },
  { abbr:"ATO",      full:"Authorization to Operate" },
  { abbr:"AUP",      full:"Acceptable Use Policy / Agreed-Upon Procedures" },
  { abbr:"B2B",      full:"Business-to-Business" },
  { abbr:"BA",       full:"Business Associate" },
  { abbr:"BAA",      full:"Business Associate Agreement" },
  { abbr:"BASE",     full:"Basically Available, Soft-state, Eventually-consistent" },
  { abbr:"BBS",      full:"Bulletin Board System" },
  { abbr:"BC",       full:"Business Continuity" },
  { abbr:"BC/DR",    full:"Business Continuity / Disaster Recovery" },
  { abbr:"BCM",      full:"Business Continuity Management" },
  { abbr:"BCP",      full:"Business Continuity Plan" },
  { abbr:"BGAN",     full:"Broadband Global Area Network" },
  { abbr:"BGP",      full:"Border Gateway Protocol" },
  { abbr:"BI",       full:"Business Intelligence" },
  { abbr:"BIA",      full:"Business Impact Analysis" },
  { abbr:"BIOS",     full:"Basic Input Output System" },
  { abbr:"BLOB",     full:"Binary Large Object" },
  { abbr:"BPEL",     full:"Business Process Execution Language" },
  { abbr:"BRM",      full:"Business Reference Model" },
  { abbr:"BSIMM",    full:"Building Security in Maturity Model" },
  { abbr:"BSS",      full:"Basic Service Set" },
  { abbr:"BT",       full:"Bluetooth" },
  { abbr:"BYOD",     full:"Bring Your Own Device" },
  { abbr:"CaaS",     full:"Compliance as a Service / Content as a Service" },
  { abbr:"CA",       full:"Certificate Authority / Certification Authority" },
  { abbr:"CAB",      full:"Change Advisory Board" },
  { abbr:"CAPEC",    full:"Common Attack Pattern Enumeration and Classification" },
  { abbr:"CAPEX",    full:"Capital Expenditure" },
  { abbr:"CAPTCHA",  full:"Completely Automated Public Turing test to tell Computers and Humans Apart" },
  { abbr:"CARVER",   full:"Criticality, Accessibility, Recuperability, Vulnerability, Effect and Recognizability" },
  { abbr:"CASB",     full:"Cloud Access Security Broker" },
  { abbr:"CAVP",     full:"Cryptographic Algorithm Validation Program" },
  { abbr:"CBA",      full:"Cost-Benefit Analysis" },
  { abbr:"CBAC",     full:"Context Based Access Control" },
  { abbr:"CBC",      full:"Cipher Block Chaining" },
  { abbr:"CC",       full:"Common Criteria" },
  { abbr:"CCA",      full:"Cloud Computing Agreements" },
  { abbr:"CCB",      full:"Configuration / Change Control Board" },
  { abbr:"CCE",      full:"Common Configuration Enumeration" },
  { abbr:"CCM",      full:"Cloud Controls Matrix" },
  { abbr:"CCMP",     full:"Counter Mode with Cipher Block Chaining Message Authentication Code Protocol" },
  { abbr:"CCP",      full:"Common Control Provider" },
  { abbr:"CCRA",     full:"Cloud Computing Reference Architecture" },
  { abbr:"CCTV",     full:"Closed-Circuit Television" },
  { abbr:"CDE",      full:"Cardholder Data Environment" },
  { abbr:"CDMA",     full:"Code Division Multiple Access" },
  { abbr:"CDMI",     full:"Cloud Data Management Interface" },
  { abbr:"CDN",      full:"Content Delivery Network / Content Distribution Network" },
  { abbr:"CDO",      full:"Chief Data Officer" },
  { abbr:"CDR",      full:"Call Detail Records / Critical Design Review" },
  { abbr:"CDS",      full:"Cross-Domain Solution" },
  { abbr:"CDSSO",    full:"Cross Domain Single Sign-On" },
  { abbr:"CE",       full:"Covered Entity" },
  { abbr:"CEO",      full:"Chief Executive Officer" },
  { abbr:"CER",      full:"Crossover Error Rate / Canonical Encoding Rules" },
  { abbr:"CFB",      full:"Cipher Feedback" },
  { abbr:"CFO",      full:"Chief Financial Officer" },
  { abbr:"CFR",      full:"Code of Federal Regulations" },
  { abbr:"CGI",      full:"Common Gateway Interface" },
  { abbr:"CHAP",     full:"Challenge Handshake Authentication Protocol" },
  { abbr:"CI/CD",    full:"Continuous Integration and Continuous Delivery" },
  { abbr:"CIA",      full:"Confidentiality, Integrity, Availability / Central Intelligence Agency" },
  { abbr:"CIDR",     full:"Classless Inter-Domain Routing" },
  { abbr:"CIO",      full:"Chief Information Officer" },
  { abbr:"CIR",      full:"Committed Information Rate" },
  { abbr:"CIRT",     full:"Computer Incident Response Team" },
  { abbr:"CIS",      full:"Center for Internet Security" },
  { abbr:"CISO",     full:"Chief Information Security Officer" },
  { abbr:"CISSP",    full:"Certified Information Systems Security Professional" },
  { abbr:"CLASP",    full:"Comprehensive, Lightweight Application Security Process" },
  { abbr:"CLOUD",    full:"Clarifying Lawful Overseas Use of Data" },
  { abbr:"CLR",      full:"Common Language Runtime" },
  { abbr:"CMDB",     full:"Configuration Management Database" },
  { abbr:"CMM",      full:"Capability Maturity Model" },
  { abbr:"CMMI",     full:"Capability Maturity Model Integration" },
  { abbr:"CMS",      full:"Configuration Management System / Content Management System / Centers for Medicare & Medicaid Services" },
  { abbr:"CNSS",     full:"Committee on National Security Systems" },
  { abbr:"COBIT",    full:"Control Objectives for Information and Related Technologies" },
  { abbr:"CompaaS",  full:"Compute as a Service" },
  { abbr:"CONOPS",   full:"Concept of Operations" },
  { abbr:"COO",      full:"Chief Operating Officer" },
  { abbr:"COOP",     full:"Continuity of Operations Plan" },
  { abbr:"COPPA",    full:"Children's Online Privacy Protection Act" },
  { abbr:"CORS",     full:"Cross Origin Resource Sharing" },
  { abbr:"COSO",     full:"Committee of Sponsoring Organizations of the Treadway Commission" },
  { abbr:"COTS",     full:"Commercial Off-The-Shelf" },
  { abbr:"CPA",      full:"Certified Public Accountant" },
  { abbr:"CPE",      full:"Common Platform Enumeration" },
  { abbr:"CPO",      full:"Chief Privacy Officer" },
  { abbr:"CPS",      full:"Certificate Practice Statement / Cyber-Physical System" },
  { abbr:"CPU",      full:"Central Processing Unit" },
  { abbr:"CRC",      full:"Cyclic Redundancy Check" },
  { abbr:"CRL",      full:"Certificate Revocation List" },
  { abbr:"CRM",      full:"Customer Relationship Management" },
  { abbr:"CRO",      full:"Chief Risk Officer" },
  { abbr:"CSA",      full:"Cloud Security Alliance / Cloud Services Agreement" },
  { abbr:"CSIRT",    full:"Computer Security Incident Response Team" },
  { abbr:"CSO",      full:"Chief Security Officer" },
  { abbr:"CSP",      full:"Cloud Service Provider / Content Security Policy" },
  { abbr:"CSRF",     full:"Cross-Site Request Forgery" },
  { abbr:"CTO",      full:"Chief Technology Officer" },
  { abbr:"CVE",      full:"Common Vulnerabilities and Exposures" },
  { abbr:"CVSS",     full:"Common Vulnerability Scoring System" },
  { abbr:"CWE",      full:"Common Weakness Enumeration" },
  { abbr:"CYBEX",    full:"Cybersecurity Information Exchange" },
  { abbr:"CYOD",     full:"Choose Your Own Device" },
  { abbr:"DaaS",     full:"Desktop as a Service" },
  { abbr:"DAC",      full:"Discretionary Access Control" },
  { abbr:"DAM",      full:"Database Activity Monitoring / Digital Asset Management" },
  { abbr:"DAMP",     full:"Database Activity Monitoring and Prevention" },
  { abbr:"DAS",      full:"Direct Attached Storage" },
  { abbr:"DAST",     full:"Dynamic Application Security Testing" },
  { abbr:"DATO",     full:"Denial of Authorization to Operate" },
  { abbr:"DBA",      full:"Database Administrator" },
  { abbr:"DBaaS",    full:"Database as a Service" },
  { abbr:"DBMS",     full:"Database Management System" },
  { abbr:"DDNS",     full:"Dynamic Domain Name Services" },
  { abbr:"DDoS",     full:"Distributed Denial of Service" },
  { abbr:"DEK",      full:"Data Encryption Key" },
  { abbr:"DEP",      full:"Data Execution Prevention" },
  { abbr:"DES",      full:"Data Encryption Standard" },
  { abbr:"DH",       full:"Diffie-Hellman" },
  { abbr:"DHCP",     full:"Dynamic Host Configuration Protocol" },
  { abbr:"DHS",      full:"Department of Homeland Security" },
  { abbr:"DICOM",    full:"Digital Imaging and Communications in Medicine" },
  { abbr:"DISA",     full:"Defense Information Systems Agency" },
  { abbr:"DKIM",     full:"DomainKeys Identified Mail" },
  { abbr:"DLL",      full:"Dynamic Link Library" },
  { abbr:"DLP",      full:"Data Loss Prevention" },
  { abbr:"DLT",      full:"Distributed Ledger Technology" },
  { abbr:"DMARC",    full:"Domain Message Authentication Reporting and Conformance" },
  { abbr:"DMZ",      full:"Demilitarized Zone" },
  { abbr:"DNS",      full:"Domain Name System / Domain Name Server" },
  { abbr:"DNSSEC",   full:"Domain Name System Security Extensions" },
  { abbr:"DoD",      full:"Department of Defense" },
  { abbr:"DOM",      full:"Document Object Model" },
  { abbr:"DoS",      full:"Denial of Service" },
  { abbr:"DPA",      full:"Data Protection Act / Differential Power Analysis" },
  { abbr:"DPIA",     full:"Data Protection Impact Assessment" },
  { abbr:"DPO",      full:"Data Protection Officer" },
  { abbr:"DR",       full:"Disaster Recovery" },
  { abbr:"DREAD",    full:"Damage, Reproducibility, Exploitability, Affected Users, and Discoverability" },
  { abbr:"DRM",      full:"Digital Rights Management" },
  { abbr:"DRP",      full:"Disaster Recovery Plan" },
  { abbr:"DSA",      full:"Digital Signature Algorithm / Data Sharing Agreement" },
  { abbr:"DSL",      full:"Digital Subscriber Line" },
  { abbr:"DSS",      full:"Digital Signature Standard" },
  { abbr:"DTLS",     full:"Datagram Transport Layer Security" },
  { abbr:"DUA",      full:"Data Use Agreement" },
  { abbr:"EAL",      full:"Evaluation Assurance Level" },
  { abbr:"EAP",      full:"Extensible Authentication Protocol" },
  { abbr:"ECC",      full:"Elliptic Curve Cryptography" },
  { abbr:"ECDSA",    full:"Elliptic Curve Digital Signature Algorithm" },
  { abbr:"EDI",      full:"Electronic Data Interchange" },
  { abbr:"EDR",      full:"Endpoint Detection and Response" },
  { abbr:"EF",       full:"Exposure Factor" },
  { abbr:"EHR",      full:"Electronic Health Record" },
  { abbr:"EMR",      full:"Electronic Medical Record" },
  { abbr:"ENISA",    full:"European Network and Information Security Agency" },
  { abbr:"ePHI",     full:"Electronic Protected Health Information" },
  { abbr:"ERM",      full:"Enterprise Risk Management" },
  { abbr:"ERP",      full:"Enterprise Resource Planning" },
  { abbr:"ESP",      full:"Encapsulating Security Payload" },
  { abbr:"EU",       full:"European Union" },
  { abbr:"EULA",     full:"End-User License Agreement" },
  { abbr:"EV",       full:"Extended Validation" },
  { abbr:"EVM",      full:"Earned Value Management" },
  { abbr:"FaaS",     full:"Function as a Service" },
  { abbr:"FAIR",     full:"Factor Analysis of Information Risk" },
  { abbr:"FAR",      full:"False Acceptance Rate" },
  { abbr:"FBI",      full:"Federal Bureau of Investigation" },
  { abbr:"FCC",      full:"Federal Communications Commission" },
  { abbr:"FDA",      full:"Food and Drug Administration" },
  { abbr:"FDE",      full:"Full Disk Encryption" },
  { abbr:"FedRAMP",  full:"Federal Risk and Authorization Management Program" },
  { abbr:"FFIEC",    full:"Federal Financial Institutions Examination Council" },
  { abbr:"FHIR",     full:"Fast Healthcare Interoperability Resources" },
  { abbr:"FIM",      full:"Federated Identity Management / File Integrity Monitoring" },
  { abbr:"FIPS",     full:"Federal Information Processing Standard" },
  { abbr:"FISMA",    full:"Federal Information Security Management Act" },
  { abbr:"FOIA",     full:"Freedom of Information Act" },
  { abbr:"FPE",      full:"Format-Preserving Encryption" },
  { abbr:"FRAP",     full:"Facilitated Risk Analysis Process" },
  { abbr:"FRCP",     full:"Federal Rules of Civil Procedure" },
  { abbr:"FRR",      full:"False Rejection Rate" },
  { abbr:"FTC",      full:"Federal Trade Commission" },
  { abbr:"FTP",      full:"File Transfer Protocol" },
  { abbr:"FTPS",     full:"File Transfer Protocol Secure" },
  { abbr:"GAAP",     full:"Generally Accepted Accounting Principles" },
  { abbr:"GAPP",     full:"Generally Accepted Privacy Principles" },
  { abbr:"GDPR",     full:"General Data Protection Regulation" },
  { abbr:"GCM",      full:"Galois/Counter Mode" },
  { abbr:"GLBA",     full:"Gramm-Leach-Bliley Act" },
  { abbr:"GPO",      full:"Group Policy Object" },
  { abbr:"GPRS",     full:"General Packet Radio Service" },
  { abbr:"GPS",      full:"Global Positioning System" },
  { abbr:"GRC",      full:"Governance, Risk Management, and Compliance" },
  { abbr:"GRE",      full:"Generic Routing Encapsulation" },
  { abbr:"GSM",      full:"Global System for Mobile Communications" },
  { abbr:"GUID",     full:"Globally Unique Identifier" },
  { abbr:"HA",       full:"High Availability" },
  { abbr:"HDD",      full:"Hard Disk Drive" },
  { abbr:"HDFS",     full:"Hadoop Distributed File System" },
  { abbr:"HHS",      full:"Health and Human Services" },
  { abbr:"HIDS",     full:"Host-based Intrusion Detection System" },
  { abbr:"HIE",      full:"Health Information Exchange" },
  { abbr:"HIPAA",    full:"Health Insurance Portability and Accountability Act" },
  { abbr:"HIPS",     full:"Host-based Intrusion Prevention System" },
  { abbr:"HITECH",   full:"Health Information Technology for Economic and Clinical Health" },
  { abbr:"HITRUST",  full:"Health Information Trust Alliance" },
  { abbr:"HL7",      full:"Health Level 7" },
  { abbr:"HMAC",     full:"Hash Message Authentication Code" },
  { abbr:"HSM",      full:"Hardware Security Module" },
  { abbr:"HTML",     full:"HyperText Markup Language" },
  { abbr:"HTTP",     full:"HyperText Transfer Protocol" },
  { abbr:"HTTPS",    full:"HyperText Transfer Protocol Secure" },
  { abbr:"HVAC",     full:"Heating, Ventilation, and Air Conditioning" },
  { abbr:"IaaS",     full:"Infrastructure as a Service" },
  { abbr:"IaC",      full:"Infrastructure as Code" },
  { abbr:"IAM",      full:"Identity and Access Management" },
  { abbr:"IAST",     full:"Interactive Application Security Testing" },
  { abbr:"ICMP",     full:"Internet Control Message Protocol" },
  { abbr:"ICS",      full:"Industrial Control System" },
  { abbr:"IDaaS",    full:"Identity as a Service" },
  { abbr:"IDE",      full:"Integrated Development Environment" },
  { abbr:"IdM",      full:"Identity Management" },
  { abbr:"IdP",      full:"Identity Provider" },
  { abbr:"IDPS",     full:"Intrusion Detection and Prevention System" },
  { abbr:"IDS",      full:"Intrusion Detection System" },
  { abbr:"IEC",      full:"International Electrotechnical Commission" },
  { abbr:"IEEE",     full:"Institute of Electrical and Electronics Engineers" },
  { abbr:"IETF",     full:"Internet Engineering Task Force" },
  { abbr:"IKE",      full:"Internet Key Exchange" },
  { abbr:"ILM",      full:"Information Lifecycle Management" },
  { abbr:"IMAP",     full:"Internet Message Access Protocol" },
  { abbr:"IMEI",     full:"International Mobile Equipment Identity" },
  { abbr:"IOC",      full:"Indicators of Compromise" },
  { abbr:"IOPS",     full:"Input/Output Operations Per Second" },
  { abbr:"IoT",      full:"Internet of Things" },
  { abbr:"IP",       full:"Internet Protocol / Intellectual Property" },
  { abbr:"IPS",      full:"Intrusion Prevention System" },
  { abbr:"IPSec",    full:"Internet Protocol Security" },
  { abbr:"IR",       full:"Incident Response" },
  { abbr:"IRM",      full:"Information Rights Management" },
  { abbr:"IRP",      full:"Incident Response Plan" },
  { abbr:"IRT",      full:"Incident Response Team" },
  { abbr:"ISAC",     full:"Information Sharing & Analysis Centers" },
  { abbr:"ISMS",     full:"Information Security Management System" },
  { abbr:"ISO",      full:"International Organization for Standardization" },
  { abbr:"ISSE",     full:"Information Systems Security Engineer" },
  { abbr:"ISSO",     full:"Information System Security Officer" },
  { abbr:"IT",       full:"Information Technology" },
  { abbr:"ITAM",     full:"Information Technology Asset Management" },
  { abbr:"ITIL",     full:"Information Technology Infrastructure Library" },
  { abbr:"ITU",      full:"International Telecommunications Union" },
  { abbr:"IV",       full:"Initialization Vector" },
  { abbr:"JAD",      full:"Joint Analysis Development" },
  { abbr:"JSON",     full:"JavaScript Object Notation" },
  { abbr:"JWT",      full:"JSON Web Token" },
  { abbr:"KDC",      full:"Key Distribution Center" },
  { abbr:"KEK",      full:"Key Encryption Key" },
  { abbr:"KMIP",     full:"Key Management Interoperability Protocol" },
  { abbr:"KMS",      full:"Key Management System" },
  { abbr:"KPI",      full:"Key Performance Indicator" },
  { abbr:"KRI",      full:"Key Risk Indicator" },
  { abbr:"L2TP",     full:"Layer 2 Tunneling Protocol" },
  { abbr:"LAN",      full:"Local Area Network" },
  { abbr:"LBAC",     full:"Lattice-Based Access Control" },
  { abbr:"LDAP",     full:"Lightweight Directory Access Protocol" },
  { abbr:"LDAPS",    full:"Lightweight Directory Access Protocol over SSL" },
  { abbr:"LTE",      full:"Long-Term Evolution" },
  { abbr:"LUN",      full:"Logical Unit Number" },
  { abbr:"MAC",      full:"Message Authentication Code / Media Access Control / Mandatory Access Control" },
  { abbr:"MAM",      full:"Mobile Application Management" },
  { abbr:"MAN",      full:"Metropolitan Area Network" },
  { abbr:"MBR",      full:"Master Boot Record" },
  { abbr:"MD5",      full:"Message Digest 5" },
  { abbr:"MDM",      full:"Mobile Device Management" },
  { abbr:"MFA",      full:"Multi-Factor Authentication" },
  { abbr:"MFT",      full:"Master File Table" },
  { abbr:"MITM",     full:"Man-in-the-Middle" },
  { abbr:"MLS",      full:"Multilevel Security" },
  { abbr:"MMS",      full:"Multimedia Message Service" },
  { abbr:"MOA",      full:"Memorandum of Agreement" },
  { abbr:"MOU",      full:"Memorandum of Understanding" },
  { abbr:"MPLS",     full:"Multiprotocol Label Switching" },
  { abbr:"MSA",      full:"Master Service Agreement" },
  { abbr:"MSP",      full:"Managed Service Provider" },
  { abbr:"MSSP",     full:"Managed Security Service Provider" },
  { abbr:"MTBF",     full:"Mean Time Between Failures" },
  { abbr:"MTD",      full:"Maximum Tolerable Downtime" },
  { abbr:"MTTF",     full:"Mean Time to Failure" },
  { abbr:"MTTR",     full:"Mean Time To Repair" },
  { abbr:"MTU",      full:"Maximum Transmission Unit" },
  { abbr:"NaaS",     full:"Network as a Service" },
  { abbr:"NAC",      full:"Network Access Control" },
  { abbr:"NAS",      full:"Network Attached Storage" },
  { abbr:"NAT",      full:"Network Address Translation" },
  { abbr:"NDA",      full:"Non-Disclosure Agreement" },
  { abbr:"NFC",      full:"Near Field Communication" },
  { abbr:"NFS",      full:"Network File System" },
  { abbr:"NFV",      full:"Network Function Virtualization" },
  { abbr:"NGFW",     full:"Next-Generation Firewall" },
  { abbr:"NIDS",     full:"Network Intrusion Detection System" },
  { abbr:"NIST",     full:"National Institute of Standards and Technology" },
  { abbr:"NOC",      full:"Network Operations Center" },
  { abbr:"NoSQL",    full:"Non Structured Query Language" },
  { abbr:"NSA",      full:"National Security Agency" },
  { abbr:"NTFS",     full:"New Technology File System" },
  { abbr:"NTP",      full:"Network Time Protocol" },
  { abbr:"NVD",      full:"National Vulnerability Database" },
  { abbr:"OAuth",    full:"Open Authorization" },
  { abbr:"OAuth2",   full:"Open Authorization Version 2" },
  { abbr:"OCSP",     full:"Online Certificate Status Protocol" },
  { abbr:"OCTAVE",   full:"Operationally Critical Threat, Asset, and Vulnerability Evaluation" },
  { abbr:"OECD",     full:"Organization for Economic Co-operation and Development" },
  { abbr:"OFB",      full:"Output Feedback" },
  { abbr:"OIDC",     full:"OpenID Connect" },
  { abbr:"OLA",      full:"Operational Level Agreement" },
  { abbr:"OPEX",     full:"Operational Expenditure" },
  { abbr:"OS",       full:"Operating System" },
  { abbr:"OSI",      full:"Open System Interconnection" },
  { abbr:"OSPF",     full:"Open Shortest Path First" },
  { abbr:"OSSTMM",   full:"Open Source Security Testing Methodology Manual" },
  { abbr:"OTP",      full:"One-time Password" },
  { abbr:"OVAL",     full:"Open Vulnerability and Assessment Language" },
  { abbr:"OWASP",    full:"Open Web Application Security Project" },
  { abbr:"P2P",      full:"Peer-to-Peer" },
  { abbr:"P2PE",     full:"Point-to-Point Encryption" },
  { abbr:"PaaS",     full:"Platform as a Service" },
  { abbr:"PACS",     full:"Physical Access Control Systems / Picture Archiving and Communication System" },
  { abbr:"PAM",      full:"Privileged Access Management / Pluggable Authentication Module" },
  { abbr:"PAN",      full:"Personal Area Network / Primary Account Number" },
  { abbr:"PAP",      full:"Password Authentication Protocol" },
  { abbr:"PASTA",    full:"Process for Attack Simulation and Threat Analysis" },
  { abbr:"PBKDF2",   full:"Password-Based Key Derivation Function 2" },
  { abbr:"PCI",      full:"Payment Card Industry" },
  { abbr:"PCI-DSS",  full:"Payment Card Industry Data Security Standard" },
  { abbr:"PEAP",     full:"Protected Extensible Authentication Protocol" },
  { abbr:"PEM",      full:"Privacy-Enhanced Mail" },
  { abbr:"PGP",      full:"Pretty Good Privacy" },
  { abbr:"PHI",      full:"Protected Health Information" },
  { abbr:"PHR",      full:"Personal Health Record" },
  { abbr:"PIA",      full:"Privacy Impact Assessment" },
  { abbr:"PII",      full:"Personally Identifiable Information" },
  { abbr:"PIN",      full:"Personal Identification Number" },
  { abbr:"PIPEDA",   full:"Personal Information Protection and Electronic Documents Act" },
  { abbr:"PIV",      full:"Personal Identity Verification" },
  { abbr:"PKCS",     full:"Public Key Cryptography Standards" },
  { abbr:"PKI",      full:"Public-Key Infrastructure" },
  { abbr:"PLC",      full:"Programmable Logic Controller" },
  { abbr:"POA&M",    full:"Plan of Action and Milestones" },
  { abbr:"PoC",      full:"Proof of Concept" },
  { abbr:"POODLE",   full:"Padding Oracle On Downgraded Legacy Encryption" },
  { abbr:"POP",      full:"Post Office Protocol" },
  { abbr:"POS",      full:"Point of Sale" },
  { abbr:"PPTP",     full:"Point-to-Point Tunneling Protocol" },
  { abbr:"PRNG",     full:"Pseudo-Random Number Generator" },
  { abbr:"PSK",      full:"Pre-shared Key" },
  { abbr:"PSTN",     full:"Public Switched Telephone Network" },
  { abbr:"PTA",      full:"Privacy Threshold Analysis" },
  { abbr:"PUE",      full:"Power Usage Effectiveness" },
  { abbr:"PVC",      full:"Permanent Virtual Circuit" },
  { abbr:"QA",       full:"Quality Assurance" },
  { abbr:"QoS",      full:"Quality of Service" },
  { abbr:"QRA",      full:"Quantitative Risk Analysis" },
  { abbr:"QSA",      full:"Qualified Security Assessor" },
  { abbr:"RA",       full:"Registration Authority" },
  { abbr:"RADIUS",   full:"Remote Authentication Dial-In User Service" },
  { abbr:"RAID",     full:"Redundant Array of Independent Disks" },
  { abbr:"RAM",      full:"Random Access Memory" },
  { abbr:"RASP",     full:"Runtime Application Self-Protection" },
  { abbr:"RAT",      full:"Remote Access Tools" },
  { abbr:"RBAC",     full:"Role Based Access Control" },
  { abbr:"RC4",      full:"Rivest Cipher 4" },
  { abbr:"RC5",      full:"Rivest Cipher 5" },
  { abbr:"RCA",      full:"Root Cause Analysis" },
  { abbr:"RDBMS",    full:"Relational Database Management System" },
  { abbr:"RDP",      full:"Remote Desktop Protocol" },
  { abbr:"REST",     full:"Representational State Transfer" },
  { abbr:"RFC",      full:"Request for Comments" },
  { abbr:"RFID",     full:"Radio-Frequency Identification" },
  { abbr:"RMF",      full:"Risk Management Framework" },
  { abbr:"ROI",      full:"Return On Investment" },
  { abbr:"RPA",      full:"Robotic Process Automation" },
  { abbr:"RPC",      full:"Remote Procedure Call" },
  { abbr:"RPO",      full:"Recovery Point Objective" },
  { abbr:"RSA",      full:"Rivest-Shamir-Adleman" },
  { abbr:"RTO",      full:"Recovery Time Objective" },
  { abbr:"S/MIME",   full:"Secure/Multipurpose Internet Mail Extensions" },
  { abbr:"SaaS",     full:"Software as a Service" },
  { abbr:"SABSA",    full:"Sherwood Applied Business Security Architecture" },
  { abbr:"SAML",     full:"Security Assertion Markup Language" },
  { abbr:"SAMM",     full:"Software Assurance Maturity Model" },
  { abbr:"SAN",      full:"Storage Area Network" },
  { abbr:"SAQ",      full:"Self Assessment Questionnaire" },
  { abbr:"SAST",     full:"Static Application Security Testing" },
  { abbr:"SCADA",    full:"Supervisory Control and Data Acquisition" },
  { abbr:"SCAP",     full:"Security Content Automation Protocol" },
  { abbr:"SCIM",     full:"System for Cross-domain Identity Management" },
  { abbr:"SCM",      full:"Software Configuration Management" },
  { abbr:"SCRM",     full:"Supply Chain Risk Management" },
  { abbr:"SDK",      full:"Software Development Kit" },
  { abbr:"SDL",      full:"Security Development Lifecycle" },
  { abbr:"SDLC",     full:"Software Development Life Cycle" },
  { abbr:"SDN",      full:"Software Defined Networking" },
  { abbr:"SECaaS",   full:"Security as a Service" },
  { abbr:"SED",      full:"Self-Encrypting Drive" },
  { abbr:"SFTP",     full:"Secure File Transfer Protocol" },
  { abbr:"SHA",      full:"Secure Hash Algorithm" },
  { abbr:"SHA-1",    full:"Secure Hash Algorithm 1" },
  { abbr:"SHA-2",    full:"Secure Hash Algorithm 2" },
  { abbr:"SHA-256",  full:"Secure Hash Algorithm 256" },
  { abbr:"SIEM",     full:"Security Information and Event Management" },
  { abbr:"SIM",      full:"Subscriber Identity Module / Security Information Management" },
  { abbr:"SIP",      full:"Session Initiation Protocol" },
  { abbr:"SLA",      full:"Service Level Agreement" },
  { abbr:"SLE",      full:"Single Loss Expectancy" },
  { abbr:"SLO",      full:"Service Level Objective" },
  { abbr:"SMB",      full:"Server Message Block" },
  { abbr:"SMS",      full:"Short Message Service" },
  { abbr:"SMTP",     full:"Simple Mail Transfer Protocol" },
  { abbr:"SNMP",     full:"Simple Network Management Protocol" },
  { abbr:"SOA",      full:"Service-Oriented Architecture" },
  { abbr:"SOAP",     full:"Simple Object Access Protocol" },
  { abbr:"SOC",      full:"Security Operations Center / Service Organization Control" },
  { abbr:"SoD",      full:"Separation of Duties" },
  { abbr:"SOHO",     full:"Small Office/Home Office" },
  { abbr:"SOP",      full:"Standard Operating Procedure" },
  { abbr:"SOW",      full:"Statement of Work" },
  { abbr:"SOX",      full:"Sarbanes-Oxley" },
  { abbr:"SPF",      full:"Sender Policy Framework" },
  { abbr:"SPOF",     full:"Single Point of Failure" },
  { abbr:"SQL",      full:"Structured Query Language" },
  { abbr:"SRAM",     full:"Static Random Access Memory" },
  { abbr:"SSD",      full:"Solid State Drive" },
  { abbr:"SSH",      full:"Secure Shell" },
  { abbr:"SSID",     full:"Service Set Identifier" },
  { abbr:"SSL",      full:"Secure Sockets Layer" },
  { abbr:"SSO",      full:"Single Sign-On" },
  { abbr:"SSRF",     full:"Server-Side Request Forgery" },
  { abbr:"STAR",     full:"Security, Trust & Assurance Registry (CSA)" },
  { abbr:"STIG",     full:"Security Technical Implementation Guide" },
  { abbr:"STIX",     full:"Structured Threat Information eXpression" },
  { abbr:"STRIDE",   full:"Spoofing, Tampering, Repudiation, Information disclosure, Denial of service, Elevation of privilege" },
  { abbr:"STS",      full:"Security Token Service" },
  { abbr:"TaaS",     full:"Testing as a Service" },
  { abbr:"TACACS",   full:"Terminal Access Controller Access Control System" },
  { abbr:"TACACS+",  full:"Terminal Access Controller Access Control System Plus" },
  { abbr:"TARA",     full:"Threat Agent Risk Assessment / Threat Assessment and Remediation Analysis" },
  { abbr:"TCB",      full:"Trusted Computing Base" },
  { abbr:"TCP",      full:"Transmission Control Protocol" },
  { abbr:"TCP/IP",   full:"Transmission Control Protocol/Internet Protocol" },
  { abbr:"TDE",      full:"Transparent Data Encryption" },
  { abbr:"TFTP",     full:"Trivial File Transfer Protocol" },
  { abbr:"TKIP",     full:"Temporal Key Integrity Protocol" },
  { abbr:"TLS",      full:"Transport Layer Security" },
  { abbr:"TOGAF",    full:"The Open Group Architecture Framework" },
  { abbr:"Tor",      full:"The Onion Router" },
  { abbr:"TPM",      full:"Trusted Platform Module" },
  { abbr:"UAT",      full:"User Acceptance Testing" },
  { abbr:"UDP",      full:"User Datagram Protocol" },
  { abbr:"UEFI",     full:"Unified Extensible Firmware Interface" },
  { abbr:"UML",      full:"Unified Modeling Language" },
  { abbr:"UPS",      full:"Uninterruptible Power Supply" },
  { abbr:"URL",      full:"Uniform Resource Locator" },
  { abbr:"USB",      full:"Universal Serial Bus" },
  { abbr:"UTM",      full:"Unified Threat Management" },
  { abbr:"VDI",      full:"Virtual Desktop Infrastructure" },
  { abbr:"VLAN",     full:"Virtual Local Area Network" },
  { abbr:"VM",       full:"Virtual Machine" },
  { abbr:"VoIP",     full:"Voice over Internet Protocol" },
  { abbr:"VPC",      full:"Virtual Private Cloud" },
  { abbr:"VPN",      full:"Virtual Private Network" },
  { abbr:"WAF",      full:"Web Application Firewall" },
  { abbr:"WAN",      full:"Wide Area Network" },
  { abbr:"WAP",      full:"Wireless Access Point / Wireless Application Protocol" },
  { abbr:"WEP",      full:"Wired Equivalent Privacy" },
  { abbr:"WiMAX",    full:"Worldwide Interoperability for Microwave Access" },
  { abbr:"WLAN",     full:"Wireless Local Area Network" },
  { abbr:"WORM",     full:"Write Once, Read Many" },
  { abbr:"WPA",      full:"WiFi Protected Access" },
  { abbr:"WPA2",     full:"WiFi Protected Access 2" },
  { abbr:"WSDL",     full:"Web Services Description Language" },
  { abbr:"XaaS",     full:"Anything as a Service" },
  { abbr:"XACML",    full:"Extensible Access Control Markup Language" },
  { abbr:"XCCDF",    full:"Extensible Configuration Checklist Description Format" },
  { abbr:"XDR",      full:"Extended Detection and Response" },
  { abbr:"XML",      full:"Extensible Markup Language" },
  { abbr:"XSS",      full:"Cross-Site Scripting" },
  { abbr:"YAML",     full:"YAML Ain't Markup Language" },
  { abbr:"ZTNA",     full:"Zero Trust Network Access" },
  { abbr:"ZTA",      full:"Zero Trust Architecture" },
];
// Sort alphabetically (case-insensitive)
ACRONYMS.sort((a, b) => a.abbr.localeCompare(b.abbr, undefined, { sensitivity: 'base' }));
