const ACRONYMS_ECIH = [
  { abbr:"ECIH", full:"EC-Council Certified Incident Handler — certification covering incident response lifecycle management" },
  { abbr:"IH", full:"Incident Handler — professional responsible for managing and responding to cybersecurity incidents" },
  { abbr:"IRT", full:"Incident Response Team — dedicated group handling security incidents within an organization" },
  { abbr:"CSIRT", full:"Computer Security Incident Response Team — organized group responding to cybersecurity incidents" },
  { abbr:"CERT", full:"Computer Emergency Response Team — term for incident response teams, originating from Carnegie Mellon CERT/CC" },
  { abbr:"SOC", full:"Security Operations Center — 24/7 monitoring team detecting and escalating security events" },
  { abbr:"IR", full:"Incident Response — organized approach to addressing and managing security incidents" },
  { abbr:"IRP", full:"Incident Response Plan — documented procedures for detecting, containing, and recovering from incidents" },
  { abbr:"TTX", full:"Tabletop Exercise — scenario-based discussion exercise testing incident response plans" },
  { abbr:"PICERL", full:"Preparation, Identification, Containment, Eradication, Recovery, Lessons Learned — incident response lifecycle model" },
  { abbr:"OODA", full:"Observe, Orient, Decide, Act — decision-making loop applied to incident response" },
  { abbr:"TTP", full:"Tactics, Techniques, and Procedures — categorization of adversary behavior from MITRE ATT&CK" },
  { abbr:"IOC", full:"Indicator of Compromise — forensic artifact indicating a system breach has occurred" },
  { abbr:"IOA", full:"Indicator of Attack — real-time evidence suggesting an active attack in progress" },
  { abbr:"EDR", full:"Endpoint Detection and Response — security platform detecting and responding to endpoint threats" },
  { abbr:"XDR", full:"Extended Detection and Response — unified threat detection across endpoint, network, and cloud" },
  { abbr:"SOAR", full:"Security Orchestration, Automation, and Response — automates incident response workflows" },
  { abbr:"SIEM", full:"Security Information and Event Management — aggregates logs and generates security alerts" },
  { abbr:"C2", full:"Command and Control — attacker infrastructure used to communicate with compromised hosts" },
  { abbr:"APT", full:"Advanced Persistent Threat — sophisticated, long-term targeted attack campaign" },
  { abbr:"DDoS", full:"Distributed Denial of Service — overwhelming a system with traffic from multiple sources to disrupt availability" },
  { abbr:"DoS", full:"Denial of Service — attack making a system or service unavailable to legitimate users" },
  { abbr:"RAT", full:"Remote Access Trojan — malware giving attackers covert remote control of a compromised system" },
  { abbr:"RCE", full:"Remote Code Execution — vulnerability allowing attackers to run arbitrary code on a target system" },
  { abbr:"LFI/RFI", full:"Local/Remote File Inclusion — web vulnerabilities including unauthorized files in application execution" },
  { abbr:"SQLI", full:"SQL Injection — attack inserting malicious SQL into database queries" },
  { abbr:"XSS", full:"Cross-Site Scripting — attack injecting malicious scripts into web pages viewed by other users" },
  { abbr:"CSRF", full:"Cross-Site Request Forgery — tricks authenticated users into performing unintended actions on a web app" },
  { abbr:"MitM", full:"Man-in-the-Middle — attack intercepting and potentially modifying communications between two parties" },
  { abbr:"PCAP", full:"Packet Capture — raw network traffic data captured for incident investigation" },
  { abbr:"DFIR", full:"Digital Forensics and Incident Response — combined discipline for investigating and responding to incidents" },
  { abbr:"CoC", full:"Chain of Custody — documented evidence handling record ensuring legal admissibility" },
  { abbr:"TTL", full:"Time to Live — network value limiting packet lifetime; also used in threat intelligence feeds" },
  { abbr:"CVE", full:"Common Vulnerabilities and Exposures — standard identifier for publicly known vulnerabilities" },
  { abbr:"CVSS", full:"Common Vulnerability Scoring System — standardized severity scoring for vulnerabilities" },
  { abbr:"BEC", full:"Business Email Compromise — fraud targeting organizations via compromised or spoofed email" },
  { abbr:"MFA", full:"Multi-Factor Authentication — requiring multiple factors to verify user identity" },
  { abbr:"VPN", full:"Virtual Private Network — encrypted tunnel for secure remote connectivity" },
  { abbr:"NGFW", full:"Next-Generation Firewall — advanced firewall with application awareness and intrusion prevention" },
  { abbr:"IDS", full:"Intrusion Detection System — monitors for and alerts on suspicious activity" },
  { abbr:"IPS", full:"Intrusion Prevention System — monitors and actively blocks malicious activity" },
  { abbr:"OSINT", full:"Open-Source Intelligence — intelligence gathered from publicly available sources" },
  { abbr:"SLA", full:"Service Level Agreement — defines expected response times and service standards" },
  { abbr:"RCA", full:"Root Cause Analysis — process determining underlying cause of an incident" },
  { abbr:"PIR", full:"Post-Incident Review — formal review after incident closure to identify improvements" },
  { abbr:"NIST SP 800-61", full:"NIST Computer Security Incident Handling Guide — authoritative guidance for incident response" },
  { abbr:"IH&R", full:"Incident Handling and Response" },
  { abbr:"ISAC", full:"Information Sharing and Analysis Center" },
  { abbr:"DLP", full:"Data Loss Prevention" },
  { abbr:"RTO", full:"Recovery Time Objective" },
  { abbr:"RPO", full:"Recovery Point Objective" },
  { abbr:"MTD", full:"Maximum Tolerable Downtime" },
  { abbr:"BCP", full:"Business Continuity Plan" },
  { abbr:"DRP", full:"Disaster Recovery Plan" },
  { abbr:"BIA", full:"Business Impact Analysis" },
  { abbr:"WAF", full:"Web Application Firewall" },
  { abbr:"PII", full:"Personally Identifiable Information" },
  { abbr:"DNS", full:"Domain Name System" },
  { abbr:"SMTP", full:"Simple Mail Transfer Protocol" }
];
ACRONYMS_ECIH.sort((a, b) => a.abbr.localeCompare(b.abbr, undefined, { sensitivity: 'base' }));
