const ACRONYMS_CCZT = [
  { abbr:"ABAC", full:"Attribute-Based Access Control" },
  { abbr:"AH", full:"Accepting Host" },
  { abbr:"API", full:"Application Programming Interface" },
  { abbr:"BYOD", full:"Bring Your Own Device" },
  { abbr:"CARTA", full:"Continuous Adaptive Risk and Trust Assessment" },
  { abbr:"CASB", full:"Cloud Access Security Broker" },
  { abbr:"CCZT", full:"Certificate of Competence in Zero Trust" },
  { abbr:"CDM", full:"Continuous Diagnostics and Mitigation" },
  { abbr:"CIEM", full:"Cloud Infrastructure Entitlement Management" },
  { abbr:"CISA", full:"Cybersecurity and Infrastructure Security Agency" },
  { abbr:"CNAPP", full:"Cloud-Native Application Protection Platform" },
  { abbr:"CSA", full:"Cloud Security Alliance" },
  { abbr:"CSPM", full:"Cloud Security Posture Management" },
  { abbr:"CWPP", full:"Cloud Workload Protection Platform" },
  { abbr:"DAAS", full:"Data, Applications, Assets, and Services (the protect surface)" },
  { abbr:"DLP", full:"Data Loss Prevention" },
  { abbr:"EDR", full:"Endpoint Detection and Response" },
  { abbr:"FIDO2", full:"Fast Identity Online 2" },
  { abbr:"FWaaS", full:"Firewall as a Service" },
  { abbr:"HSM", full:"Hardware Security Module" },
  { abbr:"IAM", full:"Identity and Access Management" },
  { abbr:"IdP", full:"Identity Provider" },
  { abbr:"IH", full:"Initiating Host" },
  { abbr:"JEA", full:"Just Enough Access" },
  { abbr:"JIT", full:"Just-In-Time (access)" },
  { abbr:"LPA", full:"Least Privilege Access" },
  { abbr:"MDM", full:"Mobile Device Management" },
  { abbr:"MFA", full:"Multi-Factor Authentication" },
  { abbr:"mTLS", full:"Mutual Transport Layer Security" },
  { abbr:"NAC", full:"Network Access Control" },
  { abbr:"NGFW", full:"Next-Generation Firewall" },
  { abbr:"NIST", full:"National Institute of Standards and Technology" },
  { abbr:"OIDC", full:"OpenID Connect" },
  { abbr:"PA", full:"Policy Administrator" },
  { abbr:"PAM", full:"Privileged Access Management" },
  { abbr:"PBAC", full:"Policy-Based Access Control" },
  { abbr:"PDP", full:"Policy Decision Point" },
  { abbr:"PE", full:"Policy Engine" },
  { abbr:"PEP", full:"Policy Enforcement Point" },
  { abbr:"PKI", full:"Public Key Infrastructure" },
  { abbr:"RBAC", full:"Role-Based Access Control" },
  { abbr:"SASE", full:"Secure Access Service Edge" },
  { abbr:"SCIM", full:"System for Cross-domain Identity Management" },
  { abbr:"SDN", full:"Software-Defined Networking" },
  { abbr:"SDP", full:"Software-Defined Perimeter" },
  { abbr:"SD-WAN", full:"Software-Defined Wide Area Network" },
  { abbr:"SIEM", full:"Security Information and Event Management" },
  { abbr:"SOAR", full:"Security Orchestration, Automation, and Response" },
  { abbr:"SPA", full:"Single Packet Authorization" },
  { abbr:"SSE", full:"Security Service Edge" },
  { abbr:"SSO", full:"Single Sign-On" },
  { abbr:"SWG", full:"Secure Web Gateway" },
  { abbr:"TEE", full:"Trusted Execution Environment" },
  { abbr:"UEBA", full:"User and Entity Behavior Analytics" },
  { abbr:"VPN", full:"Virtual Private Network" },
  { abbr:"XDR", full:"Extended Detection and Response" },
  { abbr:"ZT", full:"Zero Trust" },
  { abbr:"ZTA", full:"Zero Trust Architecture" },
  { abbr:"ZTMM", full:"Zero Trust Maturity Model (CISA)" },
  { abbr:"ZTNA", full:"Zero Trust Network Access" },
  { abbr:"SAML", full:"Security Assertion Markup Language" },
  { abbr:"OAuth", full:"Open Authorization (delegated access framework)" },
  { abbr:"JWT", full:"JSON Web Token" },
  { abbr:"WebAuthn", full:"Web Authentication (W3C API)" },
  { abbr:"SPIFFE", full:"Secure Production Identity Framework For Everyone" },
  { abbr:"SPIRE", full:"SPIFFE Runtime Environment" },
  { abbr:"SVID", full:"SPIFFE Verifiable Identity Document" },
  { abbr:"IGA", full:"Identity Governance and Administration" },
  { abbr:"PIM", full:"Privileged Identity Management" },
  { abbr:"CIAM", full:"Customer Identity and Access Management" },
  { abbr:"RP", full:"Relying Party (identity federation)" },
  { abbr:"STS", full:"Security Token Service" },
  { abbr:"IdM", full:"Identity Management" },
  { abbr:"TPM", full:"Trusted Platform Module" },
  { abbr:"KMS", full:"Key Management Service" },
  { abbr:"BYOK", full:"Bring Your Own Key" },
  { abbr:"HYOK", full:"Hold Your Own Key" },
  { abbr:"DEK", full:"Data Encryption Key" },
  { abbr:"KEK", full:"Key Encryption Key" },
  { abbr:"OCSP", full:"Online Certificate Status Protocol" },
  { abbr:"CRL", full:"Certificate Revocation List" },
  { abbr:"CA", full:"Certificate Authority" },
  { abbr:"RA", full:"Registration Authority" },
  { abbr:"CT", full:"Certificate Transparency" },
  { abbr:"SBOM", full:"Software Bill of Materials" },
  { abbr:"RASP", full:"Runtime Application Self-Protection" },
  { abbr:"SAST", full:"Static Application Security Testing" },
  { abbr:"DAST", full:"Dynamic Application Security Testing" },
  { abbr:"CI/CD", full:"Continuous Integration / Continuous Delivery" },
  { abbr:"IaC", full:"Infrastructure as Code" },
  { abbr:"NDR", full:"Network Detection and Response" },
  { abbr:"MDR", full:"Managed Detection and Response" },
  { abbr:"SOC", full:"Security Operations Center" },
  { abbr:"TIP", full:"Threat Intelligence Platform" },
  { abbr:"STIX", full:"Structured Threat Information eXpression" },
  { abbr:"TAXII", full:"Trusted Automated eXchange of Intelligence Information" },
  { abbr:"IOC", full:"Indicator of Compromise" },
  { abbr:"IOA", full:"Indicator of Attack" },
  { abbr:"TTP", full:"Tactics, Techniques, and Procedures" },
  { abbr:"CAASM", full:"Cyber Asset Attack Surface Management" },
  { abbr:"EASM", full:"External Attack Surface Management" },
  { abbr:"UEM", full:"Unified Endpoint Management" },
  { abbr:"MTD", full:"Mobile Threat Defense" },
  { abbr:"MAM", full:"Mobile Application Management" },
  { abbr:"DoH", full:"DNS over HTTPS" },
  { abbr:"DoT", full:"DNS over TLS" },
  { abbr:"DNSSEC", full:"Domain Name System Security Extensions" },
  { abbr:"802.1X", full:"IEEE 802.1X Port-Based Network Access Control" },
  { abbr:"RADIUS", full:"Remote Authentication Dial-In User Service" },
  { abbr:"TACACS+", full:"Terminal Access Controller Access-Control System Plus" },
  { abbr:"IPsec", full:"Internet Protocol Security" },
  { abbr:"IKE", full:"Internet Key Exchange" },
  { abbr:"VXLAN", full:"Virtual Extensible LAN" },
  { abbr:"NFV", full:"Network Functions Virtualization" },
  { abbr:"K8s", full:"Kubernetes (container orchestration)" },
  { abbr:"CNCF", full:"Cloud Native Computing Foundation" },
  { abbr:"OPA", full:"Open Policy Agent" },
  { abbr:"ZSP", full:"Zero Standing Privileges" },
  { abbr:"CCM", full:"Cloud Controls Matrix (CSA)" },
  { abbr:"FedRAMP", full:"Federal Risk and Authorization Management Program" }
];
ACRONYMS_CCZT.sort((a, b) => a.abbr.localeCompare(b.abbr, undefined, { sensitivity: 'base' }));
