const ACRONYMS_CISM = [
  { abbr:"3LOD",    full:"Three Lines of Defense" },
  { abbr:"ALE",     full:"Annualized Loss Expectancy" },
  { abbr:"ARO",     full:"Annualized Rate of Occurrence" },
  { abbr:"BAU",     full:"Business As Usual" },
  { abbr:"BCP",     full:"Business Continuity Plan" },
  { abbr:"BIA",     full:"Business Impact Analysis" },
  { abbr:"BPM",     full:"Business Process Management" },
  { abbr:"BSC",     full:"Balanced Scorecard" },
  { abbr:"C&A",     full:"Certification and Accreditation" },
  { abbr:"CAB",     full:"Change Advisory Board" },
  { abbr:"CCB",     full:"Change Control Board" },
  { abbr:"CERT",    full:"Computer Emergency Response Team" },
  { abbr:"CI",      full:"Configuration Item" },
  { abbr:"CISA",    full:"Certified Information Systems Auditor" },
  { abbr:"CISO",    full:"Chief Information Security Officer" },
  { abbr:"CISM",    full:"Certified Information Security Manager" },
  { abbr:"CMDB",    full:"Configuration Management Database" },
  { abbr:"COBIT",   full:"Control Objectives for Information and Related Technologies" },
  { abbr:"CPE",     full:"Continuing Professional Education" },
  { abbr:"CSIRT",   full:"Computer Security Incident Response Team" },
  { abbr:"CVE",     full:"Common Vulnerabilities and Exposures" },
  { abbr:"CVSS",    full:"Common Vulnerability Scoring System" },
  { abbr:"CWE",     full:"Common Weakness Enumeration" },
  { abbr:"DRP",     full:"Disaster Recovery Plan" },
  { abbr:"EF",      full:"Exposure Factor" },
  { abbr:"ERM",     full:"Enterprise Risk Management" },
  { abbr:"GRC",     full:"Governance, Risk, and Compliance" },
  { abbr:"IAM",     full:"Identity and Access Management" },
  { abbr:"IDS",     full:"Intrusion Detection System" },
  { abbr:"IPS",     full:"Intrusion Prevention System" },
  { abbr:"IR",      full:"Incident Response" },
  { abbr:"IRP",     full:"Incident Response Plan" },
  { abbr:"IS",      full:"Information Security" },
  { abbr:"ISMS",    full:"Information Security Management System" },
  { abbr:"ISO",     full:"International Organization for Standardization" },
  { abbr:"ISACA",   full:"Information Systems Audit and Control Association" },
  { abbr:"ISC²",    full:"International Information System Security Certification Consortium" },
  { abbr:"IT",      full:"Information Technology" },
  { abbr:"ITIL",    full:"Information Technology Infrastructure Library" },
  { abbr:"KGI",     full:"Key Goal Indicator" },
  { abbr:"KPI",     full:"Key Performance Indicator" },
  { abbr:"KRI",     full:"Key Risk Indicator" },
  { abbr:"MFA",     full:"Multi-Factor Authentication" },
  { abbr:"MTBF",    full:"Mean Time Between Failures" },
  { abbr:"MTTD",    full:"Mean Time to Detect" },
  { abbr:"MTTR",    full:"Mean Time to Respond/Recover" },
  { abbr:"NIST",    full:"National Institute of Standards and Technology" },
  { abbr:"OLA",     full:"Operational Level Agreement" },
  { abbr:"PCI DSS", full:"Payment Card Industry Data Security Standard" },
  { abbr:"PDCA",    full:"Plan-Do-Check-Act" },
  { abbr:"PIV",     full:"Personal Identity Verification" },
  { abbr:"POA&M",   full:"Plan of Action and Milestones" },
  { abbr:"PPT",     full:"People, Process, Technology" },
  { abbr:"RACI",    full:"Responsible, Accountable, Consulted, Informed" },
  { abbr:"RAD",     full:"Risk Acceptance Documentation" },
  { abbr:"RBAC",    full:"Role-Based Access Control" },
  { abbr:"RCA",     full:"Root Cause Analysis" },
  { abbr:"RF",      full:"Risk Factor" },
  { abbr:"RMF",     full:"Risk Management Framework" },
  { abbr:"ROI",     full:"Return on Investment" },
  { abbr:"RPO",     full:"Recovery Point Objective" },
  { abbr:"RTO",     full:"Recovery Time Objective" },
  { abbr:"SLA",     full:"Service Level Agreement" },
  { abbr:"SLE",     full:"Single Loss Expectancy" },
  { abbr:"SME",     full:"Subject Matter Expert" },
  { abbr:"SOC",     full:"Security Operations Center" },
  { abbr:"SOD",     full:"Segregation of Duties" },
  { abbr:"SOX",     full:"Sarbanes-Oxley Act" },
  { abbr:"SIEM",    full:"Security Information and Event Management" },
  { abbr:"TCO",     full:"Total Cost of Ownership" },
  { abbr:"TTP",     full:"Tactics, Techniques, and Procedures" },
  { abbr:"VA",      full:"Vulnerability Assessment" },
  { abbr:"VAPT",    full:"Vulnerability Assessment and Penetration Testing" },
  { abbr:"VPN",     full:"Virtual Private Network" }
];
