const ACRONYMS_CRISC = [
  { term:"CRISC", definition:"Certified in Risk and Information Systems Control — ISACA certification for IT risk professionals" },
  { term:"ERM", definition:"Enterprise Risk Management — organization-wide framework for identifying, assessing, and managing all risks" },
  { term:"IRM", definition:"Information Risk Management — discipline focused on managing risks to information assets" },
  { term:"KRI", definition:"Key Risk Indicator — metric used to signal increasing risk exposure before it materializes" },
  { term:"KPI", definition:"Key Performance Indicator — measurable value demonstrating how effectively an objective is being achieved" },
  { term:"KCI", definition:"Key Control Indicator — metric measuring the effectiveness of a risk control" },
  { term:"RTO", definition:"Recovery Time Objective — maximum acceptable downtime after a disruption" },
  { term:"RPO", definition:"Recovery Point Objective — maximum acceptable data loss measured in time" },
  { term:"BIA", definition:"Business Impact Analysis — process identifying critical business functions and quantifying disruption impacts" },
  { term:"BCP", definition:"Business Continuity Plan — documented procedures for maintaining operations during disruption" },
  { term:"DRP", definition:"Disaster Recovery Plan — documented plan for restoring IT systems after a disaster" },
  { term:"RCSA", definition:"Risk and Control Self-Assessment — process where business units evaluate their own risks and controls" },
  { term:"RACI", definition:"Responsible, Accountable, Consulted, Informed — matrix defining roles in risk management processes" },
  { term:"RMF", definition:"Risk Management Framework — structured approach for managing information security risk (NIST)" },
  { term:"ROI", definition:"Return on Investment — financial measure comparing benefit of a control against its cost" },
  { term:"TCO", definition:"Total Cost of Ownership — full lifecycle cost including implementation, operation, and maintenance" },
  { term:"ALE", definition:"Annualized Loss Expectancy — expected monetary loss per year: ALE = SLE × ARO" },
  { term:"SLE", definition:"Single Loss Expectancy — expected monetary loss from a single threat event" },
  { term:"ARO", definition:"Annualized Rate of Occurrence — estimated frequency of a threat occurring per year" },
  { term:"AV", definition:"Asset Value — monetary worth of an information asset used in risk calculations" },
  { term:"EF", definition:"Exposure Factor — percentage of asset value lost in a single threat event" },
  { term:"COSO", definition:"Committee of Sponsoring Organizations — framework for internal control and enterprise risk management" },
  { term:"ISO", definition:"International Organization for Standardization — body publishing international standards including ISO 31000 for risk" },
  { term:"ISACA", definition:"Information Systems Audit and Control Association — professional body governing CRISC, CISM, CISA, CGEIT" },
  { term:"COBIT", definition:"Control Objectives for Information and Related Technologies — ISACA governance and management framework" },
  { term:"CGEIT", definition:"Certified in the Governance of Enterprise IT — ISACA certification for IT governance professionals" },
  { term:"ITIL", definition:"IT Infrastructure Library — framework of best practices for IT service management" },
  { term:"NIST", definition:"National Institute of Standards and Technology — US agency publishing security frameworks and guidelines" },
  { term:"SP", definition:"Special Publication — NIST document series covering cybersecurity guidance (e.g., SP 800-30 for risk assessment)" },
  { term:"CVE", definition:"Common Vulnerabilities and Exposures — public dictionary of known information security vulnerabilities" },
  { term:"CVSS", definition:"Common Vulnerability Scoring System — standardized framework for rating vulnerability severity" },
  { term:"NVD", definition:"National Vulnerability Database — US government repository of CVE vulnerability data" },
  { term:"SIEM", definition:"Security Information and Event Management — platform for real-time security monitoring and analysis" },
  { term:"GRC", definition:"Governance, Risk, and Compliance — integrated approach to organizational governance and risk oversight" },
  { term:"SoD", definition:"Separation of Duties — control dividing critical tasks among multiple people to reduce fraud risk" },
  { term:"MFA", definition:"Multi-Factor Authentication — requiring two or more verification factors to authenticate users" },
  { term:"IAM", definition:"Identity and Access Management — framework for managing digital identities and access rights" },
  { term:"RBAC", definition:"Role-Based Access Control — access permissions assigned based on job role rather than individual" },
  { term:"DAC", definition:"Discretionary Access Control — resource owners set access permissions at their own discretion" },
  { term:"MAC", definition:"Mandatory Access Control — system-enforced access based on classification labels" },
  { term:"PII", definition:"Personally Identifiable Information — data that can identify an individual person" },
  { term:"PHI", definition:"Protected Health Information — health information protected under HIPAA" },
  { term:"GDPR", definition:"General Data Protection Regulation — EU regulation governing personal data protection and privacy" },
  { term:"SOX", definition:"Sarbanes-Oxley Act — US law requiring internal controls over financial reporting" },
  { term:"HIPAA", definition:"Health Insurance Portability and Accountability Act — US law protecting health information privacy" },
  { term:"PCI DSS", definition:"Payment Card Industry Data Security Standard — requirements for protecting cardholder data" },
  { term:"FISMA", definition:"Federal Information Security Modernization Act — US law governing federal agency information security" },
  { term:"FedRAMP", definition:"Federal Risk and Authorization Management Program — US government cloud security authorization program" },
  { term:"SLA", definition:"Service Level Agreement — contract specifying expected service performance levels" },
  { term:"OLA", definition:"Operational Level Agreement — internal agreement supporting SLA commitments" },
  { term:"TPM", definition:"Third-Party Management — oversight processes for vendors, suppliers, and external service providers" },
  { term:"BCM", definition:"Business Continuity Management — management of systems to prevent and recover from business disruptions" },
  { term:"MTD", definition:"Maximum Tolerable Downtime — longest period a business process can be unavailable" },
  { term:"MTBF", definition:"Mean Time Between Failures — average time between system failures" },
  { term:"MTTR", definition:"Mean Time to Repair/Recover — average time to restore a failed system" },
  { term:"RA", definition:"Risk Assessment — process of identifying, analyzing, and evaluating risks" },
  { term:"RT", definition:"Risk Tolerance — level of risk an organization is willing to accept" },
  { term:"RA-F", definition:"Risk Appetite Framework — documented boundaries defining acceptable risk levels" },
  { term:"RTP", definition:"Risk Treatment Plan — documented actions to modify risk to acceptable levels" },
  { term:"VA", definition:"Vulnerability Assessment — process of identifying and classifying security weaknesses" },
  { term:"PT", definition:"Penetration Test — authorized simulated attack to evaluate security controls" },
  { term:"SDLC", definition:"Software Development Life Cycle — structured process for planning, creating, and maintaining software" },
  { term:"DevSecOps", definition:"Development, Security, Operations — integrating security practices throughout the DevOps pipeline" },
  { term:"CI/CD", definition:"Continuous Integration/Continuous Delivery — automated software build, test, and deployment pipelines" },
  { term:"IDS", definition:"Intrusion Detection System — monitors network/system activity for malicious actions" },
  { term:"IPS", definition:"Intrusion Prevention System — monitors and actively blocks malicious network activity" }
];
