const ACRONYMS_CPENT = [
  { abbr:"CPENT", full:"Certified Penetration Testing Professional — EC-Council advanced penetration testing certification" },
  { abbr:"PT", full:"Penetration Testing — authorized simulated attack to evaluate security defenses" },
  { abbr:"RoE", full:"Rules of Engagement — agreed scope, boundaries, and permitted actions for a penetration test" },
  { abbr:"SoW", full:"Statement of Work — contract defining deliverables, scope, timeline, and payment for a pentest engagement" },
  { abbr:"OSINT", full:"Open-Source Intelligence — gathering target information from publicly available sources" },
  { abbr:"RECON", full:"Reconnaissance — information-gathering phase of a penetration test" },
  { abbr:"HUMINT", full:"Human Intelligence — intelligence gathered from human sources through social engineering" },
  { abbr:"SIGINT", full:"Signals Intelligence — intelligence gathered by intercepting electronic signals" },
  { abbr:"DNS", full:"Domain Name System — maps domain names to IP addresses; critical source of recon information" },
  { abbr:"WHOIS", full:"Protocol for querying databases storing registered domain name owners and contact information" },
  { abbr:"Nmap", full:"Network Mapper — open-source tool for network discovery and security auditing" },
  { abbr:"Metasploit", full:"Open-source penetration testing framework providing exploit modules and payloads" },
  { abbr:"MSF", full:"Metasploit Framework — modular exploitation platform for penetration testers" },
  { abbr:"CVE", full:"Common Vulnerabilities and Exposures — standardized identifiers for publicly known vulnerabilities" },
  { abbr:"CVSS", full:"Common Vulnerability Scoring System — standardized framework for rating vulnerability severity" },
  { abbr:"RCE", full:"Remote Code Execution — vulnerability allowing arbitrary code execution on a target system" },
  { abbr:"LPE", full:"Local Privilege Escalation — technique gaining higher privileges on an already-accessed system" },
  { abbr:"PoC", full:"Proof of Concept — code demonstrating a vulnerability is exploitable" },
  { abbr:"0-day", full:"Zero-Day Vulnerability — unpatched vulnerability unknown to the vendor at time of exploitation" },
  { abbr:"SQLi", full:"SQL Injection — inserting malicious SQL into application input fields to manipulate databases" },
  { abbr:"XSS", full:"Cross-Site Scripting — injecting malicious scripts into web pages viewed by other users" },
  { abbr:"CSRF", full:"Cross-Site Request Forgery — tricking authenticated users into performing unintended actions" },
  { abbr:"SSRF", full:"Server-Side Request Forgery — tricking a server into making requests to internal resources" },
  { abbr:"XXE", full:"XML External Entity — attack exploiting XML parsers to access local files or make network requests" },
  { abbr:"IDOR", full:"Insecure Direct Object Reference — accessing unauthorized resources by manipulating object identifiers" },
  { abbr:"OWASP", full:"Open Web Application Security Project — organization producing web application security standards" },
  { abbr:"OWASP Top 10", full:"Annually updated list of the most critical web application security risks" },
  { abbr:"SMB", full:"Server Message Block — Windows file sharing protocol; target of EternalBlue and similar exploits" },
  { abbr:"RDP", full:"Remote Desktop Protocol — Windows remote management protocol frequently targeted in pentests" },
  { abbr:"SSH", full:"Secure Shell — encrypted protocol for remote management; default port 22" },
  { abbr:"FTP", full:"File Transfer Protocol — insecure file transfer protocol transmitting credentials in cleartext" },
  { abbr:"SNMP", full:"Simple Network Management Protocol — network device management protocol; v1/v2 community strings are weak" },
  { abbr:"LDAP", full:"Lightweight Directory Access Protocol — directory service protocol used in Active Directory" },
  { abbr:"AD", full:"Active Directory — Microsoft directory service; primary target in Windows network pentests" },
  { abbr:"DC", full:"Domain Controller — server managing Active Directory authentication and policies" },
  { abbr:"Kerberos", full:"Network authentication protocol used by Active Directory; target of Kerberoasting attacks" },
  { abbr:"NTLM", full:"NT LAN Manager — Windows authentication protocol vulnerable to pass-the-hash attacks" },
  { abbr:"PTH", full:"Pass-the-Hash — attack using captured NTLM hash to authenticate without cracking the password" },
  { abbr:"PtT", full:"Pass-the-Ticket — Kerberos attack using captured tickets to authenticate as another user" },
  { abbr:"DCSync", full:"Active Directory attack simulating domain controller replication to dump password hashes" },
  { abbr:"BloodHound", full:"Tool analyzing Active Directory relationships and attack paths to privileged accounts" },
  { abbr:"Mimikatz", full:"Post-exploitation tool extracting credentials from Windows memory" },
  { abbr:"C2", full:"Command and Control — infrastructure for communicating with compromised systems during an engagement" },
  { abbr:"RAT", full:"Remote Access Trojan — implant providing covert remote access to compromised hosts" },
  { abbr:"AV", full:"Antivirus — security software detecting and removing malware; must be evaded in pentest" },
  { abbr:"EDR", full:"Endpoint Detection and Response — advanced security platform pentests must evade" },
  { abbr:"LOLBAS", full:"Living Off the Land Binaries and Scripts — using native OS tools to avoid detection" },
  { abbr:"IoT", full:"Internet of Things — network-connected physical devices; increasing pentest target category" },
  { abbr:"OT", full:"Operational Technology — industrial control systems and SCADA networks" },
  { abbr:"SCADA", full:"Supervisory Control and Data Acquisition — industrial control system for monitoring physical infrastructure" },
  { abbr:"WiFi", full:"Wireless networking standard; WEP/WPA2-TKIP vulnerable to cracking attacks" },
  { abbr:"PTES", full:"Penetration Testing Execution Standard" },
  { abbr:"OSSTMM", full:"Open Source Security Testing Methodology Manual" },
  { abbr:"NIST", full:"National Institute of Standards and Technology" },
  { abbr:"LFI", full:"Local File Inclusion" },
  { abbr:"RFI", full:"Remote File Inclusion" },
  { abbr:"WPA", full:"Wi-Fi Protected Access" },
  { abbr:"WPS", full:"Wi-Fi Protected Setup" },
  { abbr:"PMKID", full:"Pairwise Master Key Identifier" },
  { abbr:"ARP", full:"Address Resolution Protocol" },
  { abbr:"MITM", full:"Man-in-the-Middle" },
  { abbr:"DDoS", full:"Distributed Denial of Service" },
  { abbr:"ROP", full:"Return-Oriented Programming" },
  { abbr:"DEP", full:"Data Execution Prevention" },
  { abbr:"ASLR", full:"Address Space Layout Randomization" },
  { abbr:"SEH", full:"Structured Exception Handler" },
  { abbr:"UAC", full:"User Account Control" },
  { abbr:"LSASS", full:"Local Security Authority Subsystem Service" },
  { abbr:"SPN", full:"Service Principal Name" },
  { abbr:"DACL", full:"Discretionary Access Control List" },
  { abbr:"WinRM", full:"Windows Remote Management" },
  { abbr:"WMI", full:"Windows Management Instrumentation" },
  { abbr:"PLC", full:"Programmable Logic Controller" },
  { abbr:"DNP3", full:"Distributed Network Protocol 3" }
];
ACRONYMS_CPENT.sort((a, b) => a.abbr.localeCompare(b.abbr, undefined, { sensitivity: 'base' }));
