const ACRONYMS_CPENT = [
  { term:"CPENT", definition:"Certified Penetration Testing Professional — EC-Council advanced penetration testing certification" },
  { term:"PT", definition:"Penetration Testing — authorized simulated attack to evaluate security defenses" },
  { term:"RoE", definition:"Rules of Engagement — agreed scope, boundaries, and permitted actions for a penetration test" },
  { term:"SoW", definition:"Statement of Work — contract defining deliverables, scope, timeline, and payment for a pentest engagement" },
  { term:"OSINT", definition:"Open-Source Intelligence — gathering target information from publicly available sources" },
  { term:"RECON", definition:"Reconnaissance — information-gathering phase of a penetration test" },
  { term:"HUMINT", definition:"Human Intelligence — intelligence gathered from human sources through social engineering" },
  { term:"SIGINT", definition:"Signals Intelligence — intelligence gathered by intercepting electronic signals" },
  { term:"DNS", definition:"Domain Name System — maps domain names to IP addresses; critical source of recon information" },
  { term:"WHOIS", definition:"Protocol for querying databases storing registered domain name owners and contact information" },
  { term:"Nmap", definition:"Network Mapper — open-source tool for network discovery and security auditing" },
  { term:"Metasploit", definition:"Open-source penetration testing framework providing exploit modules and payloads" },
  { term:"MSF", definition:"Metasploit Framework — modular exploitation platform for penetration testers" },
  { term:"CVE", definition:"Common Vulnerabilities and Exposures — standardized identifiers for publicly known vulnerabilities" },
  { term:"CVSS", definition:"Common Vulnerability Scoring System — standardized framework for rating vulnerability severity" },
  { term:"RCE", definition:"Remote Code Execution — vulnerability allowing arbitrary code execution on a target system" },
  { term:"LPE", definition:"Local Privilege Escalation — technique gaining higher privileges on an already-accessed system" },
  { term:"PoC", definition:"Proof of Concept — code demonstrating a vulnerability is exploitable" },
  { term:"0-day", definition:"Zero-Day Vulnerability — unpatched vulnerability unknown to the vendor at time of exploitation" },
  { term:"SQLi", definition:"SQL Injection — inserting malicious SQL into application input fields to manipulate databases" },
  { term:"XSS", definition:"Cross-Site Scripting — injecting malicious scripts into web pages viewed by other users" },
  { term:"CSRF", definition:"Cross-Site Request Forgery — tricking authenticated users into performing unintended actions" },
  { term:"SSRF", definition:"Server-Side Request Forgery — tricking a server into making requests to internal resources" },
  { term:"XXE", definition:"XML External Entity — attack exploiting XML parsers to access local files or make network requests" },
  { term:"IDOR", definition:"Insecure Direct Object Reference — accessing unauthorized resources by manipulating object identifiers" },
  { term:"OWASP", definition:"Open Web Application Security Project — organization producing web application security standards" },
  { term:"OWASP Top 10", definition:"Annually updated list of the most critical web application security risks" },
  { term:"SMB", definition:"Server Message Block — Windows file sharing protocol; target of EternalBlue and similar exploits" },
  { term:"RDP", definition:"Remote Desktop Protocol — Windows remote management protocol frequently targeted in pentests" },
  { term:"SSH", definition:"Secure Shell — encrypted protocol for remote management; default port 22" },
  { term:"FTP", definition:"File Transfer Protocol — insecure file transfer protocol transmitting credentials in cleartext" },
  { term:"SNMP", definition:"Simple Network Management Protocol — network device management protocol; v1/v2 community strings are weak" },
  { term:"LDAP", definition:"Lightweight Directory Access Protocol — directory service protocol used in Active Directory" },
  { term:"AD", definition:"Active Directory — Microsoft directory service; primary target in Windows network pentests" },
  { term:"DC", definition:"Domain Controller — server managing Active Directory authentication and policies" },
  { term:"Kerberos", definition:"Network authentication protocol used by Active Directory; target of Kerberoasting attacks" },
  { term:"NTLM", definition:"NT LAN Manager — Windows authentication protocol vulnerable to pass-the-hash attacks" },
  { term:"PTH", definition:"Pass-the-Hash — attack using captured NTLM hash to authenticate without cracking the password" },
  { term:"PtT", definition:"Pass-the-Ticket — Kerberos attack using captured tickets to authenticate as another user" },
  { term:"DCSync", definition:"Active Directory attack simulating domain controller replication to dump password hashes" },
  { term:"BloodHound", definition:"Tool analyzing Active Directory relationships and attack paths to privileged accounts" },
  { term:"Mimikatz", definition:"Post-exploitation tool extracting credentials from Windows memory" },
  { term:"C2", definition:"Command and Control — infrastructure for communicating with compromised systems during an engagement" },
  { term:"RAT", definition:"Remote Access Trojan — implant providing covert remote access to compromised hosts" },
  { term:"AV", definition:"Antivirus — security software detecting and removing malware; must be evaded in pentest" },
  { term:"EDR", definition:"Endpoint Detection and Response — advanced security platform pentests must evade" },
  { term:"LOLBAS", definition:"Living Off the Land Binaries and Scripts — using native OS tools to avoid detection" },
  { term:"IoT", definition:"Internet of Things — network-connected physical devices; increasing pentest target category" },
  { term:"OT", definition:"Operational Technology — industrial control systems and SCADA networks" },
  { term:"SCADA", definition:"Supervisory Control and Data Acquisition — industrial control system for monitoring physical infrastructure" },
  { term:"WiFi", definition:"Wireless networking standard; WEP/WPA2-TKIP vulnerable to cracking attacks" }
];
