const ACRONYMS_CHFI = [
  { abbr:"CHFI", full:"Computer Hacking Forensic Investigator — EC-Council certification for digital forensics professionals" },
  { abbr:"EC-Council", full:"International Council of E-Commerce Consultants — organization behind CHFI, CEH, CPENT, and ECIH certifications" },
  { abbr:"DFIR", full:"Digital Forensics and Incident Response — combined discipline covering investigation and active incident management" },
  { abbr:"FTK", full:"Forensic Toolkit — commercial digital forensics software suite by AccessData/Exterro" },
  { abbr:"EnCase", full:"Commercial digital forensics software by OpenText, widely used in law enforcement" },
  { abbr:"IOC", full:"Indicator of Compromise — artifact observed on a system indicating probable intrusion" },
  { abbr:"PCAP", full:"Packet Capture — raw network traffic data captured for analysis" },
  { abbr:"MFT", full:"Master File Table — NTFS structure recording metadata for every file on a volume" },
  { abbr:"FAT", full:"File Allocation Table — legacy Windows filesystem storing file location data" },
  { abbr:"NTFS", full:"New Technology File System — primary Windows filesystem supporting journaling and advanced metadata" },
  { abbr:"EXT4", full:"Fourth Extended Filesystem — primary Linux filesystem with journaling support" },
  { abbr:"APFS", full:"Apple File System — macOS and iOS filesystem replacing HFS+, supporting encryption and snapshots" },
  { abbr:"HFS+", full:"Hierarchical File System Plus — legacy Apple filesystem replaced by APFS" },
  { abbr:"ADS", full:"Alternate Data Streams — NTFS feature allowing data to be hidden within another file's metadata" },
  { abbr:"MBR", full:"Master Boot Record — first sector of a storage device containing partition table and bootloader" },
  { abbr:"GPT", full:"GUID Partition Table — modern partitioning standard replacing MBR, part of UEFI specification" },
  { abbr:"UEFI", full:"Unified Extensible Firmware Interface — modern firmware interface replacing BIOS" },
  { abbr:"RAM", full:"Random Access Memory — volatile memory losing contents when power is removed; priority for live forensics" },
  { abbr:"VSS", full:"Volume Shadow Copy Service — Windows feature creating point-in-time snapshots of volumes" },
  { abbr:"LNK", full:"Windows shortcut file — contains metadata about recently accessed files including timestamps and path" },
  { abbr:"USN", full:"Update Sequence Number Journal — NTFS journal recording file system changes" },
  { abbr:"SAM", full:"Security Account Manager — Windows database storing local user account credentials" },
  { abbr:"NTLM", full:"NT LAN Manager — Windows challenge-response authentication protocol" },
  { abbr:"MD5", full:"Message Digest 5 — 128-bit hash algorithm used for file integrity verification in forensics" },
  { abbr:"SHA-1", full:"Secure Hash Algorithm 1 — 160-bit hash; used in forensics though cryptographically deprecated" },
  { abbr:"SHA-256", full:"Secure Hash Algorithm 256-bit — current standard hash algorithm for forensic file integrity" },
  { abbr:"WMI", full:"Windows Management Instrumentation — Windows infrastructure for management and scripting; abused by attackers" },
  { abbr:"PST", full:"Personal Storage Table — Outlook email archive file format containing messages, contacts, and calendar items" },
  { abbr:"OST", full:"Offline Storage Table — local copy of Exchange mailbox data in Outlook" },
  { abbr:"SMTP", full:"Simple Mail Transfer Protocol — standard protocol for sending email" },
  { abbr:"IMAP", full:"Internet Message Access Protocol — email retrieval protocol leaving messages on server" },
  { abbr:"IP", full:"Internet Protocol — fundamental network protocol providing addressing and routing" },
  { abbr:"MAC", full:"Media Access Control — unique hardware identifier assigned to network interface cards" },
  { abbr:"ARP", full:"Address Resolution Protocol — maps IP addresses to MAC addresses on local networks" },
  { abbr:"DNS", full:"Domain Name System — translates domain names to IP addresses" },
  { abbr:"DHCP", full:"Dynamic Host Configuration Protocol — automatically assigns IP addresses to network devices" },
  { abbr:"HTTP/S", full:"HyperText Transfer Protocol (Secure) — protocol for web communication, HTTPS adds TLS encryption" },
  { abbr:"TOR", full:"The Onion Router — anonymity network routing traffic through multiple encrypted relay nodes" },
  { abbr:"VPN", full:"Virtual Private Network — encrypted tunnel for secure remote network connectivity" },
  { abbr:"OSINT", full:"Open-Source Intelligence — intelligence gathered from publicly available sources" },
  { abbr:"CVE", full:"Common Vulnerabilities and Exposures — standardized identifiers for known security vulnerabilities" },
  { abbr:"APT", full:"Advanced Persistent Threat — sophisticated, long-term targeted attack by skilled adversaries" },
  { abbr:"C2", full:"Command and Control — infrastructure attackers use to communicate with compromised systems" },
  { abbr:"RAT", full:"Remote Access Trojan — malware providing covert remote access to a compromised system" },
  { abbr:"SIEM", full:"Security Information and Event Management — log aggregation and correlation platform" },
  { abbr:"CoC", full:"Chain of Custody — documented chronological handling of evidence ensuring integrity" },
  { abbr:"SOP", full:"Standard Operating Procedure — documented step-by-step process for evidence handling" },
  { abbr:"RFC", full:"Request for Comments — IETF documents defining internet standards and protocols" },
  { abbr:"SQL", full:"Structured Query Language — language for database management and querying" },
  { abbr:"XSS", full:"Cross-Site Scripting — web vulnerability injecting malicious scripts into web pages" },
  { abbr:"SQLi", full:"SQL Injection — attack inserting malicious SQL code into application queries" },
  { abbr:"exFAT", full:"Extensible File Allocation Table" },
  { abbr:"HPA", full:"Host Protected Area (hidden disk region)" },
  { abbr:"DCO", full:"Device Configuration Overlay (hidden disk region)" },
  { abbr:"TRIM", full:"TRIM command (SSD block erase notification)" },
  { abbr:"RAID", full:"Redundant Array of Independent Disks" },
  { abbr:"SHA", full:"Secure Hash Algorithm" },
  { abbr:"E01", full:"EnCase Evidence File (Expert Witness Format)" },
  { abbr:"AFF", full:"Advanced Forensic Format" },
  { abbr:"DD", full:"Data Dump (raw bit-stream disk image)" },
  { abbr:"SRUM", full:"System Resource Usage Monitor" },
  { abbr:"BAM", full:"Background Activity Moderator" },
  { abbr:"YARA", full:"Yet Another Recursive Acronym (malware pattern rules)" },
  { abbr:"TTP", full:"Tactics, Techniques, and Procedures" },
  { abbr:"IDS", full:"Intrusion Detection System" },
  { abbr:"POP3", full:"Post Office Protocol version 3" },
  { abbr:"EML", full:"Electronic Mail message file" },
  { abbr:"MBOX", full:"Mailbox message storage format" },
  { abbr:"JTAG", full:"Joint Test Action Group (chip-level acquisition)" },
  { abbr:"UART", full:"Universal Asynchronous Receiver-Transmitter" },
  { abbr:"TEE", full:"Trusted Execution Environment" }
];
ACRONYMS_CHFI.sort((a, b) => a.abbr.localeCompare(b.abbr, undefined, { sensitivity: 'base' }));
