const ACRONYMS_SECX = [
  { abbr:"ABAC", full:"Attribute-Based Access Control — policies based on attributes of users, resources, and environment" },
  { abbr:"API", full:"Application Programming Interface — defined interface for software component communication" },
  { abbr:"BAS", full:"Breach and Attack Simulation — automated continuous testing of security controls against real-world attack techniques" },
  { abbr:"CASB", full:"Cloud Access Security Broker — security enforcement point between users and cloud service providers" },
  { abbr:"CASP+", full:"CompTIA Advanced Security Practitioner — former name for CompTIA SecurityX certification" },
  { abbr:"CIEM", full:"Cloud Infrastructure Entitlement Management — manages and reduces excessive permissions in cloud environments" },
  { abbr:"CNAPP", full:"Cloud-Native Application Protection Platform — unified cloud security covering CSPM, CWPP, and CIEM" },
  { abbr:"CompTIA", full:"Computing Technology Industry Association — vendor-neutral IT certification body" },
  { abbr:"CSPM", full:"Cloud Security Posture Management — automated detection of cloud infrastructure misconfigurations" },
  { abbr:"CTI", full:"Cyber Threat Intelligence" },
  { abbr:"CVE", full:"Common Vulnerabilities and Exposures — standardized identifiers for publicly known security vulnerabilities" },
  { abbr:"CVSS", full:"Common Vulnerability Scoring System — framework for rating the severity of security vulnerabilities" },
  { abbr:"CWE", full:"Common Weakness Enumeration — community-developed list of software and hardware weaknesses" },
  { abbr:"CWPP", full:"Cloud Workload Protection Platform — security controls for cloud-native workloads and containers" },
  { abbr:"DAST", full:"Dynamic Application Security Testing — testing running applications for vulnerabilities by simulating attacks" },
  { abbr:"DevSecOps", full:"Development, Security, and Operations — integrating security practices throughout the software development lifecycle" },
  { abbr:"DLP", full:"Data Loss Prevention — technology preventing unauthorized movement or exfiltration of sensitive data" },
  { abbr:"eBPF", full:"Extended Berkeley Packet Filter" },
  { abbr:"EDR", full:"Endpoint Detection and Response — security solution providing continuous endpoint monitoring and threat response" },
  { abbr:"FIDO2", full:"Fast Identity Online 2 — open standard for phishing-resistant passwordless authentication" },
  { abbr:"GRC", full:"Governance, Risk, and Compliance — integrated approach managing organizational risk and compliance" },
  { abbr:"HSM", full:"Hardware Security Module — dedicated hardware for secure cryptographic key management" },
  { abbr:"IaC", full:"Infrastructure as Code — managing and provisioning infrastructure through machine-readable configuration files" },
  { abbr:"IAST", full:"Interactive Application Security Testing — combines DAST and SAST techniques within running applications" },
  { abbr:"IOA", full:"Indicator of Attack — real-time evidence suggesting an attack is in progress" },
  { abbr:"IOC", full:"Indicator of Compromise — forensic data indicating a system may have been breached" },
  { abbr:"ISO 27001", full:"International standard for Information Security Management Systems (ISMS)" },
  { abbr:"KMS", full:"Key Management Service" },
  { abbr:"MDR", full:"Managed Detection and Response — outsourced service providing threat detection, investigation, and response" },
  { abbr:"MFA", full:"Multi-Factor Authentication — requiring multiple verification factors for authentication" },
  { abbr:"MITRE ATT&CK", full:"Adversarial Tactics, Techniques, and Common Knowledge — globally-accessible knowledge base of adversary behaviors" },
  { abbr:"mTLS", full:"Mutual TLS — both parties authenticate to each other using certificates during TLS handshake" },
  { abbr:"NAC", full:"Network Access Control" },
  { abbr:"NDR", full:"Network Detection and Response — solution detecting threats through network traffic analysis" },
  { abbr:"NGFW", full:"Next-Generation Firewall" },
  { abbr:"NIST CSF", full:"NIST Cybersecurity Framework — risk-based framework for managing cybersecurity" },
  { abbr:"OCSP", full:"Online Certificate Status Protocol" },
  { abbr:"OIDC", full:"OpenID Connect" },
  { abbr:"OWASP", full:"Open Web Application Security Project — nonprofit producing web application security resources and standards" },
  { abbr:"PAM", full:"Privileged Access Management — controls, monitors, and audits the use of privileged accounts" },
  { abbr:"PFS", full:"Perfect Forward Secrecy" },
  { abbr:"PKI", full:"Public Key Infrastructure — systems and policies for managing digital certificates and public-key encryption" },
  { abbr:"PQC", full:"Post-Quantum Cryptography — cryptographic algorithms resistant to quantum computer attacks" },
  { abbr:"RASP", full:"Runtime Application Self-Protection" },
  { abbr:"RBAC", full:"Role-Based Access Control — granting access based on user roles rather than individuals" },
  { abbr:"SASE", full:"Secure Access Service Edge — cloud-delivered convergence of networking and security capabilities" },
  { abbr:"SAST", full:"Static Application Security Testing — analyzing source code for vulnerabilities without executing the program" },
  { abbr:"SBOM", full:"Software Bill of Materials — formal record of components in a software product for supply chain security" },
  { abbr:"SCA", full:"Software Composition Analysis — identifies open-source components and their known vulnerabilities in applications" },
  { abbr:"SCIM", full:"System for Cross-domain Identity Management" },
  { abbr:"SDP", full:"Software-Defined Perimeter" },
  { abbr:"SD-WAN", full:"Software-Defined Wide Area Network — WAN architecture with software-controlled management" },
  { abbr:"SecurityX", full:"CompTIA SecurityX (formerly CASP+) — advanced-level cybersecurity certification for security architects and senior engineers" },
  { abbr:"SIEM", full:"Security Information and Event Management — aggregates and correlates log data from multiple sources" },
  { abbr:"SLSA", full:"Supply-chain Levels for Software Artifacts" },
  { abbr:"SOAR", full:"Security Orchestration, Automation, and Response — platform automating security workflows and incident response" },
  { abbr:"SPIFFE", full:"Secure Production Identity Framework for Everyone" },
  { abbr:"SSE", full:"Security Service Edge" },
  { abbr:"SWG", full:"Secure Web Gateway" },
  { abbr:"TEE", full:"Trusted Execution Environment" },
  { abbr:"TLS", full:"Transport Layer Security — protocol providing encrypted communications between systems" },
  { abbr:"TTP", full:"Tactics, Techniques, and Procedures — categorization of adversary behavior in threat intelligence (MITRE ATT&CK)" },
  { abbr:"UEBA", full:"User and Entity Behavior Analytics — uses ML to detect anomalous behavior indicating threats" },
  { abbr:"WAF", full:"Web Application Firewall — filters and monitors HTTP traffic to protect web applications" },
  { abbr:"XDR", full:"Extended Detection and Response — unified platform integrating endpoint, network, cloud, and application telemetry for detection" },
  { abbr:"ZTA", full:"Zero Trust Architecture — security model requiring continuous verification for all users and devices" },
  { abbr:"ZTNA", full:"Zero Trust Network Access — technology providing application-level access without network-level trust" },
  { abbr:"SDN", full:"Software-Defined Networking" },
  { abbr:"NFV", full:"Network Functions Virtualization" },
  { abbr:"TIP", full:"Threat Intelligence Platform" },
  { abbr:"STIX", full:"Structured Threat Information Expression" },
  { abbr:"TAXII", full:"Trusted Automated Exchange of Intelligence Information" },
  { abbr:"MISP", full:"Malware Information Sharing Platform" },
  { abbr:"OSINT", full:"Open-Source Intelligence" },
  { abbr:"IRM", full:"Information Rights Management" },
  { abbr:"HSTS", full:"HTTP Strict Transport Security" },
  { abbr:"CRL", full:"Certificate Revocation List" },
  { abbr:"SCEP", full:"Simple Certificate Enrollment Protocol" },
  { abbr:"EST", full:"Enrollment over Secure Transport" },
  { abbr:"ACME", full:"Automated Certificate Management Environment" },
  { abbr:"TPM", full:"Trusted Platform Module" },
  { abbr:"ECDSA", full:"Elliptic Curve Digital Signature Algorithm" },
  { abbr:"ECDH", full:"Elliptic Curve Diffie-Hellman" },
  { abbr:"EdDSA", full:"Edwards-curve Digital Signature Algorithm" },
  { abbr:"AEAD", full:"Authenticated Encryption with Associated Data" },
  { abbr:"HMAC", full:"Hash-based Message Authentication Code" },
  { abbr:"HKDF", full:"HMAC-based Key Derivation Function" },
  { abbr:"PBKDF2", full:"Password-Based Key Derivation Function 2" },
  { abbr:"SCAP", full:"Security Content Automation Protocol" },
  { abbr:"OSCAL", full:"Open Security Controls Assessment Language" },
  { abbr:"CMMC", full:"Cybersecurity Maturity Model Certification" },
  { abbr:"VDP", full:"Vulnerability Disclosure Program" },
  { abbr:"MTTD", full:"Mean Time to Detect" },
  { abbr:"MTTR", full:"Mean Time to Respond" },
  { abbr:"BIA", full:"Business Impact Analysis" }
];
ACRONYMS_SECX.sort((a, b) => a.abbr.localeCompare(b.abbr, undefined, { sensitivity: 'base' }));
