const ACRONYMS_CISSP = [
  { abbr:"2FA",      full:"Two-Factor Authentication" },
  { abbr:"3DES",     full:"Triple Data Encryption Standard" },
  { abbr:"AAA",      full:"Authentication, Authorization, Accounting" },
  { abbr:"ABAC",     full:"Attribute-Based Access Control" },
  { abbr:"ACL",      full:"Access Control List" },
  { abbr:"AES",      full:"Advanced Encryption Standard" },
  { abbr:"APT",      full:"Advanced Persistent Threat" },
  { abbr:"ARO",      full:"Annualized Rate of Occurrence" },
  { abbr:"ARP",      full:"Address Resolution Protocol" },
  { abbr:"ASLR",     full:"Address Space Layout Randomization" },
  { abbr:"BCP",      full:"Business Continuity Plan" },
  { abbr:"BIA",      full:"Business Impact Analysis" },
  { abbr:"CA",       full:"Certificate Authority" },
  { abbr:"CBC",      full:"Cipher Block Chaining" },
  { abbr:"CERT",     full:"Computer Emergency Response Team" },
  { abbr:"CISSP",    full:"Certified Information Systems Security Professional" },
  { abbr:"CMMI",     full:"Capability Maturity Model Integration" },
  { abbr:"CRL",      full:"Certificate Revocation List" },
  { abbr:"CSRF",     full:"Cross-Site Request Forgery" },
  { abbr:"CVE",      full:"Common Vulnerabilities and Exposures" },
  { abbr:"CVSS",     full:"Common Vulnerability Scoring System" },
  { abbr:"DAC",      full:"Discretionary Access Control" },
  { abbr:"DEP",      full:"Data Execution Prevention" },
  { abbr:"DES",      full:"Data Encryption Standard" },
  { abbr:"DHCP",     full:"Dynamic Host Configuration Protocol" },
  { abbr:"DLP",      full:"Data Loss Prevention" },
  { abbr:"DMZ",      full:"Demilitarized Zone" },
  { abbr:"DNS",      full:"Domain Name System" },
  { abbr:"DRP",      full:"Disaster Recovery Plan" },
  { abbr:"DSS",      full:"Digital Signature Standard" },
  { abbr:"EAP",      full:"Extensible Authentication Protocol" },
  { abbr:"ECC",      full:"Elliptic Curve Cryptography" },
  { abbr:"ECDH",     full:"Elliptic Curve Diffie-Hellman" },
  { abbr:"FIPS",     full:"Federal Information Processing Standards" },
  { abbr:"FTP",      full:"File Transfer Protocol" },
  { abbr:"GDPR",     full:"General Data Protection Regulation" },
  { abbr:"HMAC",     full:"Hash-Based Message Authentication Code" },
  { abbr:"HSM",      full:"Hardware Security Module" },
  { abbr:"HTTP",     full:"HyperText Transfer Protocol" },
  { abbr:"HTTPS",    full:"HTTP Secure" },
  { abbr:"IAM",      full:"Identity and Access Management" },
  { abbr:"IDS",      full:"Intrusion Detection System" },
  { abbr:"IPS",      full:"Intrusion Prevention System" },
  { abbr:"IPSec",    full:"Internet Protocol Security" },
  { abbr:"IRM",      full:"Information Rights Management" },
  { abbr:"ISC²",     full:"International Information System Security Certification Consortium" },
  { abbr:"ISMS",     full:"Information Security Management System" },
  { abbr:"IV",       full:"Initialization Vector" },
  { abbr:"LDAP",     full:"Lightweight Directory Access Protocol" },
  { abbr:"MAC",      full:"Mandatory Access Control / Message Authentication Code" },
  { abbr:"MFA",      full:"Multi-Factor Authentication" },
  { abbr:"MITM",     full:"Man-in-the-Middle Attack" },
  { abbr:"NAC",      full:"Network Access Control" },
  { abbr:"NIST",     full:"National Institute of Standards and Technology" },
  { abbr:"OAUTH",    full:"Open Authorization" },
  { abbr:"OCSP",     full:"Online Certificate Status Protocol" },
  { abbr:"OWASP",    full:"Open Web Application Security Project" },
  { abbr:"PAM",      full:"Privileged Access Management" },
  { abbr:"PEM",      full:"Privacy Enhanced Mail (certificate format)" },
  { abbr:"PGP",      full:"Pretty Good Privacy" },
  { abbr:"PKI",      full:"Public Key Infrastructure" },
  { abbr:"PCI DSS",  full:"Payment Card Industry Data Security Standard" },
  { abbr:"RBAC",     full:"Role-Based Access Control" },
  { abbr:"RPO",      full:"Recovery Point Objective" },
  { abbr:"RSA",      full:"Rivest–Shamir–Adleman (asymmetric algorithm)" },
  { abbr:"RTO",      full:"Recovery Time Objective" },
  { abbr:"SAML",     full:"Security Assertion Markup Language" },
  { abbr:"SCAP",     full:"Security Content Automation Protocol" },
  { abbr:"SDLC",     full:"Software/Systems Development Life Cycle" },
  { abbr:"SHA",      full:"Secure Hash Algorithm" },
  { abbr:"SIEM",     full:"Security Information and Event Management" },
  { abbr:"SLA",      full:"Service Level Agreement" },
  { abbr:"SOC",      full:"Security Operations Center" },
  { abbr:"SOD",      full:"Segregation of Duties" },
  { abbr:"SPF",      full:"Sender Policy Framework" },
  { abbr:"SQL",      full:"Structured Query Language" },
  { abbr:"SSH",      full:"Secure Shell" },
  { abbr:"SSL",      full:"Secure Sockets Layer" },
  { abbr:"SSO",      full:"Single Sign-On" },
  { abbr:"TCB",      full:"Trusted Computing Base" },
  { abbr:"TLS",      full:"Transport Layer Security" },
  { abbr:"TPM",      full:"Trusted Platform Module" },
  { abbr:"UAC",      full:"User Account Control" },
  { abbr:"VPN",      full:"Virtual Private Network" },
  { abbr:"WAF",      full:"Web Application Firewall" },
  { abbr:"WPA",      full:"Wi-Fi Protected Access" },
  { abbr:"XSS",      full:"Cross-Site Scripting" },
  { abbr:"ZTNA",     full:"Zero Trust Network Access" }
];
