const ACRONYMS_ISSAP = [
  { term:"ISSAP", definition:"Information Systems Security Architecture Professional — ISC² concentration for security architects" },
  { term:"SABSA", definition:"Sherwood Applied Business Security Architecture — enterprise security architecture framework aligning security with business objectives" },
  { term:"TOGAF", definition:"The Open Group Architecture Framework — enterprise architecture framework used alongside SABSA for security architecture" },
  { term:"EA", definition:"Enterprise Architecture — structured representation of an organization's business processes, IT assets, and strategic objectives" },
  { term:"ZTA", definition:"Zero Trust Architecture — security model requiring continuous verification regardless of network location" },
  { term:"ZTNA", definition:"Zero Trust Network Access — technology implementing zero trust principles for application access" },
  { term:"SASE", definition:"Secure Access Service Edge — cloud-delivered convergence of network and security services at the edge" },
  { term:"SSE", definition:"Security Service Edge — security-focused subset of SASE including SWG, CASB, and ZTNA" },
  { term:"SD-WAN", definition:"Software-Defined Wide Area Network — virtualized WAN architecture enabling centralized policy management" },
  { term:"SDN", definition:"Software-Defined Networking — separates control plane from data plane for centralized network management" },
  { term:"PKI", definition:"Public Key Infrastructure — framework of policies, procedures, and technologies managing digital certificates" },
  { term:"CA", definition:"Certificate Authority — trusted entity that issues and manages digital certificates in PKI" },
  { term:"CRL", definition:"Certificate Revocation List — list of digital certificates revoked before their expiration date" },
  { term:"OCSP", definition:"Online Certificate Status Protocol — real-time protocol for checking certificate revocation status" },
  { term:"HSM", definition:"Hardware Security Module — tamper-resistant hardware device for secure cryptographic key management" },
  { term:"AES", definition:"Advanced Encryption Standard — symmetric block cipher using 128/192/256-bit keys; current encryption standard" },
  { term:"RSA", definition:"Rivest-Shamir-Adleman — asymmetric cryptographic algorithm for encryption and digital signatures" },
  { term:"ECC", definition:"Elliptic Curve Cryptography — asymmetric cryptography using elliptic curves; efficient at shorter key lengths" },
  { term:"ECDH", definition:"Elliptic Curve Diffie-Hellman — key agreement protocol using elliptic curve cryptography" },
  { term:"GCM", definition:"Galois/Counter Mode — authenticated encryption mode providing both confidentiality and integrity" },
  { term:"HMAC", definition:"Hash-based Message Authentication Code — uses a hash function and secret key to verify message integrity and authenticity" },
  { term:"TLS", definition:"Transport Layer Security — cryptographic protocol providing secure communications over networks" },
  { term:"mTLS", definition:"Mutual TLS — both client and server authenticate each other via certificates during TLS handshake" },
  { term:"FIDO2", definition:"Fast Identity Online 2 — open authentication standard supporting passwordless and phishing-resistant MFA" },
  { term:"SAML", definition:"Security Assertion Markup Language — XML-based standard for federated identity and SSO across organizations" },
  { term:"OAuth", definition:"Open Authorization — open standard for access delegation, commonly used for token-based API authorization" },
  { term:"OIDC", definition:"OpenID Connect — identity layer on top of OAuth 2.0 providing user authentication" },
  { term:"LDAP", definition:"Lightweight Directory Access Protocol — protocol for accessing and maintaining directory information services" },
  { term:"PAM", definition:"Privileged Access Management — solutions controlling, monitoring, and auditing privileged account usage" },
  { term:"JIT", definition:"Just-In-Time (access) — granting elevated privileges only for the duration required, then revoking them" },
  { term:"SIEM", definition:"Security Information and Event Management — platform aggregating and correlating logs for threat detection" },
  { term:"SOAR", definition:"Security Orchestration, Automation, and Response — platform automating security operations workflows" },
  { term:"SOC", definition:"Security Operations Center — team providing 24/7 security monitoring, detection, and incident response" },
  { term:"IAM", definition:"Identity and Access Management — processes and technologies for managing digital identities and access" },
  { term:"DMZ", definition:"Demilitarized Zone — network segment isolating public-facing services from the internal trusted network" },
  { term:"NAC", definition:"Network Access Control — technology enforcing security policies on devices before granting network access" },
  { term:"WAF", definition:"Web Application Firewall — filters, monitors, and blocks malicious HTTP/S traffic to web applications" },
  { term:"API", definition:"Application Programming Interface — interface enabling software components to communicate" },
  { term:"NIST CSF", definition:"NIST Cybersecurity Framework — voluntary framework of standards for managing cybersecurity risk" },
  { term:"ISO 27001", definition:"International standard specifying requirements for an Information Security Management System (ISMS)" },
  { term:"RBAC", definition:"Role-Based Access Control — access rights assigned by job role rather than individual identity" },
  { term:"ABAC", definition:"Attribute-Based Access Control — access decisions based on attributes of users, resources, and environment" },
  { term:"SDP", definition:"Software-Defined Perimeter — security architecture making resources invisible until authenticated" },
  { term:"BAS", definition:"Breach and Attack Simulation — automated tools continuously testing security control effectiveness" },
  { term:"CSPM", definition:"Cloud Security Posture Management — tools detecting misconfigurations in cloud environments" },
  { term:"CWPP", definition:"Cloud Workload Protection Platform — security solution protecting cloud workloads" },
  { term:"CNAPP", definition:"Cloud-Native Application Protection Platform — unified security for cloud-native applications and infrastructure" },
  { term:"EDR", definition:"Endpoint Detection and Response — security solution monitoring endpoints for threat activity" },
  { term:"XDR", definition:"Extended Detection and Response — unified security platform integrating multiple telemetry sources" },
  { term:"UEBA", definition:"User and Entity Behavior Analytics — detects anomalous behavior patterns indicating insider threats or compromised accounts" },
  { term:"DLP", definition:"Data Loss Prevention — controls preventing unauthorized exfiltration of sensitive data" },
  { term:"CASB", definition:"Cloud Access Security Broker — security policy enforcement point between users and cloud services" }
];
