const ACRONYMS_CRISC = [
  { abbr:"CRISC", full:"Certified in Risk and Information Systems Control — ISACA certification for IT risk professionals" },
  { abbr:"ERM", full:"Enterprise Risk Management — organization-wide framework for identifying, assessing, and managing all risks" },
  { abbr:"IRM", full:"Information Risk Management — discipline focused on managing risks to information assets" },
  { abbr:"KRI", full:"Key Risk Indicator — metric used to signal increasing risk exposure before it materializes" },
  { abbr:"KPI", full:"Key Performance Indicator — measurable value demonstrating how effectively an objective is being achieved" },
  { abbr:"KCI", full:"Key Control Indicator — metric measuring the effectiveness of a risk control" },
  { abbr:"RTO", full:"Recovery Time Objective — maximum acceptable downtime after a disruption" },
  { abbr:"RPO", full:"Recovery Point Objective — maximum acceptable data loss measured in time" },
  { abbr:"BIA", full:"Business Impact Analysis — process identifying critical business functions and quantifying disruption impacts" },
  { abbr:"BCP", full:"Business Continuity Plan — documented procedures for maintaining operations during disruption" },
  { abbr:"DRP", full:"Disaster Recovery Plan — documented plan for restoring IT systems after a disaster" },
  { abbr:"RCSA", full:"Risk and Control Self-Assessment — process where business units evaluate their own risks and controls" },
  { abbr:"RACI", full:"Responsible, Accountable, Consulted, Informed — matrix defining roles in risk management processes" },
  { abbr:"RMF", full:"Risk Management Framework — structured approach for managing information security risk (NIST)" },
  { abbr:"ROI", full:"Return on Investment — financial measure comparing benefit of a control against its cost" },
  { abbr:"TCO", full:"Total Cost of Ownership — full lifecycle cost including implementation, operation, and maintenance" },
  { abbr:"ALE", full:"Annualized Loss Expectancy — expected monetary loss per year: ALE = SLE × ARO" },
  { abbr:"SLE", full:"Single Loss Expectancy — expected monetary loss from a single threat event" },
  { abbr:"ARO", full:"Annualized Rate of Occurrence — estimated frequency of a threat occurring per year" },
  { abbr:"AV", full:"Asset Value — monetary worth of an information asset used in risk calculations" },
  { abbr:"EF", full:"Exposure Factor — percentage of asset value lost in a single threat event" },
  { abbr:"COSO", full:"Committee of Sponsoring Organizations — framework for internal control and enterprise risk management" },
  { abbr:"ISO", full:"International Organization for Standardization — body publishing international standards including ISO 31000 for risk" },
  { abbr:"ISACA", full:"Information Systems Audit and Control Association — professional body governing CRISC, CISM, CISA, CGEIT" },
  { abbr:"COBIT", full:"Control Objectives for Information and Related Technologies — ISACA governance and management framework" },
  { abbr:"CGEIT", full:"Certified in the Governance of Enterprise IT — ISACA certification for IT governance professionals" },
  { abbr:"ITIL", full:"IT Infrastructure Library — framework of best practices for IT service management" },
  { abbr:"NIST", full:"National Institute of Standards and Technology — US agency publishing security frameworks and guidelines" },
  { abbr:"SP", full:"Special Publication — NIST document series covering cybersecurity guidance (e.g., SP 800-30 for risk assessment)" },
  { abbr:"CVE", full:"Common Vulnerabilities and Exposures — public dictionary of known information security vulnerabilities" },
  { abbr:"CVSS", full:"Common Vulnerability Scoring System — standardized framework for rating vulnerability severity" },
  { abbr:"NVD", full:"National Vulnerability Database — US government repository of CVE vulnerability data" },
  { abbr:"SIEM", full:"Security Information and Event Management — platform for real-time security monitoring and analysis" },
  { abbr:"GRC", full:"Governance, Risk, and Compliance — integrated approach to organizational governance and risk oversight" },
  { abbr:"SoD", full:"Separation of Duties — control dividing critical tasks among multiple people to reduce fraud risk" },
  { abbr:"MFA", full:"Multi-Factor Authentication — requiring two or more verification factors to authenticate users" },
  { abbr:"IAM", full:"Identity and Access Management — framework for managing digital identities and access rights" },
  { abbr:"RBAC", full:"Role-Based Access Control — access permissions assigned based on job role rather than individual" },
  { abbr:"DAC", full:"Discretionary Access Control — resource owners set access permissions at their own discretion" },
  { abbr:"MAC", full:"Mandatory Access Control — system-enforced access based on classification labels" },
  { abbr:"PII", full:"Personally Identifiable Information — data that can identify an individual person" },
  { abbr:"PHI", full:"Protected Health Information — health information protected under HIPAA" },
  { abbr:"GDPR", full:"General Data Protection Regulation — EU regulation governing personal data protection and privacy" },
  { abbr:"SOX", full:"Sarbanes-Oxley Act — US law requiring internal controls over financial reporting" },
  { abbr:"HIPAA", full:"Health Insurance Portability and Accountability Act — US law protecting health information privacy" },
  { abbr:"PCI DSS", full:"Payment Card Industry Data Security Standard — requirements for protecting cardholder data" },
  { abbr:"FISMA", full:"Federal Information Security Modernization Act — US law governing federal agency information security" },
  { abbr:"FedRAMP", full:"Federal Risk and Authorization Management Program — US government cloud security authorization program" },
  { abbr:"SLA", full:"Service Level Agreement — contract specifying expected service performance levels" },
  { abbr:"OLA", full:"Operational Level Agreement — internal agreement supporting SLA commitments" },
  { abbr:"TPM", full:"Third-Party Management — oversight processes for vendors, suppliers, and external service providers" },
  { abbr:"BCM", full:"Business Continuity Management — management of systems to prevent and recover from business disruptions" },
  { abbr:"MTD", full:"Maximum Tolerable Downtime — longest period a business process can be unavailable" },
  { abbr:"MTBF", full:"Mean Time Between Failures — average time between system failures" },
  { abbr:"MTTR", full:"Mean Time to Repair/Recover — average time to restore a failed system" },
  { abbr:"RA", full:"Risk Assessment — process of identifying, analyzing, and evaluating risks" },
  { abbr:"RT", full:"Risk Tolerance — level of risk an organization is willing to accept" },
  { abbr:"RA-F", full:"Risk Appetite Framework — documented boundaries defining acceptable risk levels" },
  { abbr:"RTP", full:"Risk Treatment Plan — documented actions to modify risk to acceptable levels" },
  { abbr:"VA", full:"Vulnerability Assessment — process of identifying and classifying security weaknesses" },
  { abbr:"PT", full:"Penetration Test — authorized simulated attack to evaluate security controls" },
  { abbr:"SDLC", full:"Software Development Life Cycle — structured process for planning, creating, and maintaining software" },
  { abbr:"DevSecOps", full:"Development, Security, Operations — integrating security practices throughout the DevOps pipeline" },
  { abbr:"CI/CD", full:"Continuous Integration/Continuous Delivery — automated software build, test, and deployment pipelines" },
  { abbr:"IDS", full:"Intrusion Detection System — monitors network/system activity for malicious actions" },
  { abbr:"IPS", full:"Intrusion Prevention System — monitors and actively blocks malicious network activity" },
  { abbr:"PAM", full:"Privileged Access Management" },
  { abbr:"ABAC", full:"Attribute-Based Access Control" },
  { abbr:"DLP", full:"Data Loss Prevention" },
  { abbr:"PKI", full:"Public Key Infrastructure" },
  { abbr:"ROSI", full:"Return on Security Investment" },
  { abbr:"VaR", full:"Value at Risk" },
  { abbr:"CIA", full:"Confidentiality, Integrity, and Availability" },
  { abbr:"UAT", full:"User Acceptance Testing" },
  { abbr:"CMDB", full:"Configuration Management Database" }
];
ACRONYMS_CRISC.sort((a, b) => a.abbr.localeCompare(b.abbr, undefined, { sensitivity: 'base' }));
