const ACRONYMS_CISM = [
  { abbr:"3LOD", full:"Three Lines of Defense" },
  { abbr:"ALE", full:"Annualized Loss Expectancy" },
  { abbr:"ARO", full:"Annualized Rate of Occurrence" },
  { abbr:"BAU", full:"Business As Usual" },
  { abbr:"BCP", full:"Business Continuity Plan" },
  { abbr:"BIA", full:"Business Impact Analysis" },
  { abbr:"BPM", full:"Business Process Management" },
  { abbr:"BSC", full:"Balanced Scorecard" },
  { abbr:"C&A", full:"Certification and Accreditation" },
  { abbr:"CAB", full:"Change Advisory Board" },
  { abbr:"CCB", full:"Change Control Board" },
  { abbr:"CERT", full:"Computer Emergency Response Team" },
  { abbr:"CI", full:"Configuration Item" },
  { abbr:"CISA", full:"Certified Information Systems Auditor" },
  { abbr:"CISM", full:"Certified Information Security Manager" },
  { abbr:"CISO", full:"Chief Information Security Officer" },
  { abbr:"CMDB", full:"Configuration Management Database" },
  { abbr:"COBIT", full:"Control Objectives for Information and Related Technologies" },
  { abbr:"CPE", full:"Continuing Professional Education" },
  { abbr:"CSIRT", full:"Computer Security Incident Response Team" },
  { abbr:"CVE", full:"Common Vulnerabilities and Exposures" },
  { abbr:"CVSS", full:"Common Vulnerability Scoring System" },
  { abbr:"CWE", full:"Common Weakness Enumeration" },
  { abbr:"DLP", full:"Data Loss Prevention" },
  { abbr:"DRP", full:"Disaster Recovery Plan" },
  { abbr:"EF", full:"Exposure Factor" },
  { abbr:"ERM", full:"Enterprise Risk Management" },
  { abbr:"GRC", full:"Governance, Risk, and Compliance" },
  { abbr:"IAM", full:"Identity and Access Management" },
  { abbr:"IDS", full:"Intrusion Detection System" },
  { abbr:"IPS", full:"Intrusion Prevention System" },
  { abbr:"IR", full:"Incident Response" },
  { abbr:"IRP", full:"Incident Response Plan" },
  { abbr:"IS", full:"Information Security" },
  { abbr:"ISACA", full:"Information Systems Audit and Control Association" },
  { abbr:"ISC²", full:"International Information System Security Certification Consortium" },
  { abbr:"ISMS", full:"Information Security Management System" },
  { abbr:"ISO", full:"International Organization for Standardization" },
  { abbr:"IT", full:"Information Technology" },
  { abbr:"ITIL", full:"Information Technology Infrastructure Library" },
  { abbr:"KGI", full:"Key Goal Indicator" },
  { abbr:"KPI", full:"Key Performance Indicator" },
  { abbr:"KRI", full:"Key Risk Indicator" },
  { abbr:"MFA", full:"Multi-Factor Authentication" },
  { abbr:"MOU", full:"Memorandum of Understanding" },
  { abbr:"MTBF", full:"Mean Time Between Failures" },
  { abbr:"MTD", full:"Maximum Tolerable Downtime" },
  { abbr:"MTTD", full:"Mean Time to Detect" },
  { abbr:"MTTR", full:"Mean Time to Respond/Recover" },
  { abbr:"NDA", full:"Non-Disclosure Agreement" },
  { abbr:"NIST", full:"National Institute of Standards and Technology" },
  { abbr:"OLA", full:"Operational Level Agreement" },
  { abbr:"PAM", full:"Privileged Access Management" },
  { abbr:"PCI DSS", full:"Payment Card Industry Data Security Standard" },
  { abbr:"PDCA", full:"Plan-Do-Check-Act" },
  { abbr:"PIV", full:"Personal Identity Verification" },
  { abbr:"PKI", full:"Public Key Infrastructure" },
  { abbr:"POA&M", full:"Plan of Action and Milestones" },
  { abbr:"PPT", full:"People, Process, Technology" },
  { abbr:"RACI", full:"Responsible, Accountable, Consulted, Informed" },
  { abbr:"RAD", full:"Risk Acceptance Documentation" },
  { abbr:"RBAC", full:"Role-Based Access Control" },
  { abbr:"RCA", full:"Root Cause Analysis" },
  { abbr:"RF", full:"Risk Factor" },
  { abbr:"RMF", full:"Risk Management Framework" },
  { abbr:"ROI", full:"Return on Investment" },
  { abbr:"ROSI", full:"Return on Security Investment" },
  { abbr:"RPO", full:"Recovery Point Objective" },
  { abbr:"RTO", full:"Recovery Time Objective" },
  { abbr:"SDLC", full:"Software Development Life Cycle" },
  { abbr:"SIEM", full:"Security Information and Event Management" },
  { abbr:"SLA", full:"Service Level Agreement" },
  { abbr:"SLE", full:"Single Loss Expectancy" },
  { abbr:"SME", full:"Subject Matter Expert" },
  { abbr:"SOAR", full:"Security Orchestration, Automation, and Response" },
  { abbr:"SOC", full:"Security Operations Center" },
  { abbr:"SOD", full:"Segregation of Duties" },
  { abbr:"SOX", full:"Sarbanes-Oxley Act" },
  { abbr:"TCO", full:"Total Cost of Ownership" },
  { abbr:"TTP", full:"Tactics, Techniques, and Procedures" },
  { abbr:"UEBA", full:"User and Entity Behavior Analytics" },
  { abbr:"VA", full:"Vulnerability Assessment" },
  { abbr:"VAPT", full:"Vulnerability Assessment and Penetration Testing" },
  { abbr:"VPN", full:"Virtual Private Network" },
  { abbr:"COSO", full:"Committee of Sponsoring Organizations of the Treadway Commission" },
  { abbr:"CMMI", full:"Capability Maturity Model Integration" },
  { abbr:"WRT", full:"Work Recovery Time" },
  { abbr:"MAO", full:"Maximum Acceptable Outage" },
  { abbr:"UC", full:"Underpinning Contract" },
  { abbr:"IGA", full:"Identity Governance and Administration" },
  { abbr:"SCIM", full:"System for Cross-domain Identity Management" },
  { abbr:"OIDC", full:"OpenID Connect" },
  { abbr:"MSSP", full:"Managed Security Service Provider" },
  { abbr:"CASB", full:"Cloud Access Security Broker" },
  { abbr:"ZTNA", full:"Zero Trust Network Access" },
  { abbr:"SASE", full:"Secure Access Service Edge" },
  { abbr:"BCM", full:"Business Continuity Management" },
  { abbr:"SoA", full:"Statement of Applicability" },
  { abbr:"TVM", full:"Threat and Vulnerability Management" },
  { abbr:"CTI", full:"Cyber Threat Intelligence" },
  { abbr:"TLP", full:"Traffic Light Protocol" },
  { abbr:"IoC", full:"Indicator of Compromise" },
  { abbr:"OSINT", full:"Open Source Intelligence" },
  { abbr:"VDP", full:"Vulnerability Disclosure Program" },
  { abbr:"CVD", full:"Coordinated Vulnerability Disclosure" },
  { abbr:"SBOM", full:"Software Bill of Materials" },
  { abbr:"IAST", full:"Interactive Application Security Testing" },
  { abbr:"RASP", full:"Runtime Application Self-Protection" },
  { abbr:"UEM", full:"Unified Endpoint Management" },
  { abbr:"ITAM", full:"IT Asset Management" },
  { abbr:"RFC", full:"Request for Change" },
  { abbr:"ROC", full:"Report on Compliance (PCI DSS)" },
  { abbr:"SAQ", full:"Self-Assessment Questionnaire (PCI DSS)" },
  { abbr:"CCM", full:"Cloud Controls Matrix (CSA)" },
  { abbr:"CAIQ", full:"Consensus Assessments Initiative Questionnaire (CSA)" },
  { abbr:"TARA", full:"Threat Assessment and Remediation Analysis" },
  { abbr:"FAIR", full:"Factor Analysis of Information Risk" },
  { abbr:"OCTAVE", full:"Operationally Critical Threat, Asset, and Vulnerability Evaluation" },
  { abbr:"RTM", full:"Requirements Traceability Matrix" },
  { abbr:"POAM", full:"Plan of Action and Milestones" },
  { abbr:"ATO", full:"Authorization to Operate" }
];
ACRONYMS_CISM.sort((a, b) => a.abbr.localeCompare(b.abbr, undefined, { sensitivity: 'base' }));
