const ACRONYMS_CISA = [
  { abbr:"ACL",     full:"Access Control List" },
  { abbr:"AIS",     full:"Automated Information System" },
  { abbr:"API",     full:"Application Programming Interface" },
  { abbr:"APT",     full:"Advanced Persistent Threat" },
  { abbr:"AUP",     full:"Acceptable Use Policy" },
  { abbr:"BCP",     full:"Business Continuity Plan" },
  { abbr:"BIA",     full:"Business Impact Analysis" },
  { abbr:"CAE",     full:"Chief Audit Executive" },
  { abbr:"CAPM",    full:"Capability and Process Maturity Model" },
  { abbr:"CAS",     full:"Complex Adaptive System" },
  { abbr:"CISA",    full:"Certified Information Systems Auditor" },
  { abbr:"CMMI",    full:"Capability Maturity Model Integration" },
  { abbr:"COBIT",   full:"Control Objectives for Information and Related Technologies" },
  { abbr:"COI",     full:"Conflict of Interest" },
  { abbr:"COTS",    full:"Commercial Off-the-Shelf" },
  { abbr:"CSA",     full:"Control Self-Assessment" },
  { abbr:"DRP",     full:"Disaster Recovery Plan" },
  { abbr:"EAM",     full:"Enterprise Architecture Management" },
  { abbr:"ERP",     full:"Enterprise Resource Planning" },
  { abbr:"ESA",     full:"Enterprise Security Architecture" },
  { abbr:"FISMA",   full:"Federal Information Security Management Act" },
  { abbr:"GAAP",    full:"Generally Accepted Accounting Principles" },
  { abbr:"GRC",     full:"Governance, Risk, and Compliance" },
  { abbr:"HIPAA",   full:"Health Insurance Portability and Accountability Act" },
  { abbr:"ICS",     full:"Industrial Control System" },
  { abbr:"IDS",     full:"Intrusion Detection System" },
  { abbr:"IS",      full:"Information Systems" },
  { abbr:"ISACA",   full:"Information Systems Audit and Control Association" },
  { abbr:"ISMS",    full:"Information Security Management System" },
  { abbr:"ISO",     full:"International Organization for Standardization" },
  { abbr:"ITAF",    full:"IT Assurance Framework" },
  { abbr:"ITAM",    full:"IT Asset Management" },
  { abbr:"ITGC",    full:"IT General Controls" },
  { abbr:"ITIL",    full:"Information Technology Infrastructure Library" },
  { abbr:"KPI",     full:"Key Performance Indicator" },
  { abbr:"KRI",     full:"Key Risk Indicator" },
  { abbr:"NIST",    full:"National Institute of Standards and Technology" },
  { abbr:"OLA",     full:"Operational Level Agreement" },
  { abbr:"PCAOB",   full:"Public Company Accounting Oversight Board" },
  { abbr:"PCI DSS", full:"Payment Card Industry Data Security Standard" },
  { abbr:"RACI",    full:"Responsible, Accountable, Consulted, Informed" },
  { abbr:"RBAC",    full:"Role-Based Access Control" },
  { abbr:"RFC",     full:"Request for Change" },
  { abbr:"RMF",     full:"Risk Management Framework" },
  { abbr:"ROI",     full:"Return on Investment" },
  { abbr:"RPO",     full:"Recovery Point Objective" },
  { abbr:"RTO",     full:"Recovery Time Objective" },
  { abbr:"SDLC",    full:"Software/Systems Development Life Cycle" },
  { abbr:"SIEM",    full:"Security Information and Event Management" },
  { abbr:"SLA",     full:"Service Level Agreement" },
  { abbr:"SOC",     full:"Service Organization Control (report)" },
  { abbr:"SOD",     full:"Segregation of Duties" },
  { abbr:"SOX",     full:"Sarbanes-Oxley Act" },
  { abbr:"SOP",     full:"Standard Operating Procedure" },
  { abbr:"SSO",     full:"Single Sign-On" },
  { abbr:"TCO",     full:"Total Cost of Ownership" },
  { abbr:"TOR",     full:"Terms of Reference" },
  { abbr:"UAT",     full:"User Acceptance Testing" },
  { abbr:"UPS",     full:"Uninterruptible Power Supply" },
  { abbr:"VA",      full:"Vulnerability Assessment" },
  { abbr:"WAF",     full:"Web Application Firewall" },
  { abbr:"WBS",     full:"Work Breakdown Structure" }
];
