const ACRONYMS_SECX = [
  { term:"SecurityX", definition:"CompTIA SecurityX (formerly CASP+) — advanced-level cybersecurity certification for security architects and senior engineers" },
  { term:"CASP+", definition:"CompTIA Advanced Security Practitioner — former name for CompTIA SecurityX certification" },
  { term:"CompTIA", definition:"Computing Technology Industry Association — vendor-neutral IT certification body" },
  { term:"ZTA", definition:"Zero Trust Architecture — security model requiring continuous verification for all users and devices" },
  { term:"SASE", definition:"Secure Access Service Edge — cloud-delivered convergence of networking and security capabilities" },
  { term:"ZTNA", definition:"Zero Trust Network Access — technology providing application-level access without network-level trust" },
  { term:"SD-WAN", definition:"Software-Defined Wide Area Network — WAN architecture with software-controlled management" },
  { term:"XDR", definition:"Extended Detection and Response — unified platform integrating endpoint, network, cloud, and application telemetry for detection" },
  { term:"EDR", definition:"Endpoint Detection and Response — security solution providing continuous endpoint monitoring and threat response" },
  { term:"MDR", definition:"Managed Detection and Response — outsourced service providing threat detection, investigation, and response" },
  { term:"NDR", definition:"Network Detection and Response — solution detecting threats through network traffic analysis" },
  { term:"SOAR", definition:"Security Orchestration, Automation, and Response — platform automating security workflows and incident response" },
  { term:"SIEM", definition:"Security Information and Event Management — aggregates and correlates log data from multiple sources" },
  { term:"UEBA", definition:"User and Entity Behavior Analytics — uses ML to detect anomalous behavior indicating threats" },
  { term:"TTP", definition:"Tactics, Techniques, and Procedures — categorization of adversary behavior in threat intelligence (MITRE ATT&CK)" },
  { term:"IOC", definition:"Indicator of Compromise — forensic data indicating a system may have been breached" },
  { term:"IOA", definition:"Indicator of Attack — real-time evidence suggesting an attack is in progress" },
  { term:"MITRE ATT&CK", definition:"Adversarial Tactics, Techniques, and Common Knowledge — globally-accessible knowledge base of adversary behaviors" },
  { term:"CVE", definition:"Common Vulnerabilities and Exposures — standardized identifiers for publicly known security vulnerabilities" },
  { term:"CVSS", definition:"Common Vulnerability Scoring System — framework for rating the severity of security vulnerabilities" },
  { term:"CWE", definition:"Common Weakness Enumeration — community-developed list of software and hardware weaknesses" },
  { term:"OWASP", definition:"Open Web Application Security Project — nonprofit producing web application security resources and standards" },
  { term:"BAS", definition:"Breach and Attack Simulation — automated continuous testing of security controls against real-world attack techniques" },
  { term:"CSPM", definition:"Cloud Security Posture Management — automated detection of cloud infrastructure misconfigurations" },
  { term:"CWPP", definition:"Cloud Workload Protection Platform — security controls for cloud-native workloads and containers" },
  { term:"CNAPP", definition:"Cloud-Native Application Protection Platform — unified cloud security covering CSPM, CWPP, and CIEM" },
  { term:"CIEM", definition:"Cloud Infrastructure Entitlement Management — manages and reduces excessive permissions in cloud environments" },
  { term:"IaC", definition:"Infrastructure as Code — managing and provisioning infrastructure through machine-readable configuration files" },
  { term:"DevSecOps", definition:"Development, Security, and Operations — integrating security practices throughout the software development lifecycle" },
  { term:"SBOM", definition:"Software Bill of Materials — formal record of components in a software product for supply chain security" },
  { term:"SCA", definition:"Software Composition Analysis — identifies open-source components and their known vulnerabilities in applications" },
  { term:"DAST", definition:"Dynamic Application Security Testing — testing running applications for vulnerabilities by simulating attacks" },
  { term:"SAST", definition:"Static Application Security Testing — analyzing source code for vulnerabilities without executing the program" },
  { term:"IAST", definition:"Interactive Application Security Testing — combines DAST and SAST techniques within running applications" },
  { term:"PKI", definition:"Public Key Infrastructure — systems and policies for managing digital certificates and public-key encryption" },
  { term:"HSM", definition:"Hardware Security Module — dedicated hardware for secure cryptographic key management" },
  { term:"PQC", definition:"Post-Quantum Cryptography — cryptographic algorithms resistant to quantum computer attacks" },
  { term:"TLS", definition:"Transport Layer Security — protocol providing encrypted communications between systems" },
  { term:"mTLS", definition:"Mutual TLS — both parties authenticate to each other using certificates during TLS handshake" },
  { term:"PAM", definition:"Privileged Access Management — controls, monitors, and audits the use of privileged accounts" },
  { term:"RBAC", definition:"Role-Based Access Control — granting access based on user roles rather than individuals" },
  { term:"ABAC", definition:"Attribute-Based Access Control — policies based on attributes of users, resources, and environment" },
  { term:"DLP", definition:"Data Loss Prevention — technology preventing unauthorized movement or exfiltration of sensitive data" },
  { term:"CASB", definition:"Cloud Access Security Broker — security enforcement point between users and cloud service providers" },
  { term:"WAF", definition:"Web Application Firewall — filters and monitors HTTP traffic to protect web applications" },
  { term:"MFA", definition:"Multi-Factor Authentication — requiring multiple verification factors for authentication" },
  { term:"FIDO2", definition:"Fast Identity Online 2 — open standard for phishing-resistant passwordless authentication" },
  { term:"API", definition:"Application Programming Interface — defined interface for software component communication" },
  { term:"NIST CSF", definition:"NIST Cybersecurity Framework — risk-based framework for managing cybersecurity" },
  { term:"ISO 27001", definition:"International standard for Information Security Management Systems (ISMS)" },
  { term:"GRC", definition:"Governance, Risk, and Compliance — integrated approach managing organizational risk and compliance" }
];
