const GLOSSARY_CPENT = [
  { term:"Penetration Testing", definition:"An authorized simulated cyberattack against a computer system, network, or application to evaluate security defenses and identify exploitable vulnerabilities before real attackers do." },
  { term:"Rules of Engagement", definition:"A written agreement between the penetration tester and client defining the scope, permitted activities, time windows, out-of-scope systems, escalation contacts, and legal authorization for the test." },
  { term:"Reconnaissance", definition:"The information-gathering phase of a penetration test. Passive recon uses public sources without touching the target; active recon directly interacts with target systems." },
  { term:"Footprinting", definition:"Systematically gathering information about a target organization including network ranges, domain names, employee details, and technology stack before active testing begins." },
  { term:"Scanning", definition:"Using network tools to discover live hosts, open ports, running services, and OS versions on target systems. Forms the technical map used for subsequent exploitation." },
  { term:"Enumeration", definition:"Actively querying target systems to extract detailed information including usernames, shares, services, and configuration details that can be used to identify attack vectors." },
  { term:"Vulnerability Assessment", definition:"Identifying and classifying security weaknesses in a system. Unlike penetration testing, vulnerability assessment does not attempt to exploit findings." },
  { term:"Exploitation", definition:"Using identified vulnerabilities to gain unauthorized access to a system, demonstrating real-world impact. Controlled, documented, and within agreed scope during penetration tests." },
  { term:"Privilege Escalation", definition:"After gaining initial access, techniques for acquiring higher-level privileges (admin/root) on a compromised system, enabling broader access and impact demonstration." },
  { term:"Lateral Movement", definition:"Techniques for moving through a network from an initial foothold to reach additional systems, particularly high-value targets like domain controllers." },
  { term:"Persistence", definition:"Techniques for maintaining access to compromised systems across reboots, password changes, or incident response activities — demonstrates how real attackers maintain footholds." },
  { term:"Post-Exploitation", definition:"Actions taken after gaining access to a system: privilege escalation, lateral movement, data exfiltration simulation, and persistence mechanisms." },
  { term:"Pivoting", definition:"Using a compromised system as a relay point to reach otherwise inaccessible network segments, extending the penetration test into internal or segregated networks." },
  { term:"Exfiltration", definition:"Simulating an attacker's ability to extract sensitive data from a compromised environment, demonstrating the potential impact of a real breach." },
  { term:"Payload", definition:"Code or data delivered through exploitation that performs the attacker's desired action on a target system, such as establishing a reverse shell or executing commands." },
  { term:"Shell", definition:"Command-line interface on a compromised system. A bind shell listens on the target; a reverse shell connects back to the attacker, bypassing firewalls." },
  { term:"Bind Shell", definition:"A compromised system opens a port and listens for incoming connections from the attacker. Less common due to firewall restrictions on inbound connections." },
  { term:"Reverse Shell", definition:"A compromised system connects outbound to the attacker's machine. Preferred method as most firewalls allow outbound connections." },
  { term:"Social Engineering", definition:"Manipulating people through psychological tactics to divulge confidential information or perform actions that compromise security. Includes phishing, pretexting, and vishing." },
  { term:"Phishing", definition:"Fraudulent emails impersonating legitimate entities to trick recipients into revealing credentials, clicking malicious links, or opening malware attachments." },
  { term:"Spear Phishing", definition:"Highly targeted phishing using personalized content and context specific to an individual or organization, dramatically increasing success rates over generic phishing." },
  { term:"Password Attack", definition:"Attempts to recover passwords through brute force, dictionary attacks, password spraying, or credential stuffing from breach databases." },
  { term:"Pass-the-Hash", definition:"Authentication attack using captured NTLM password hashes directly without needing to crack them, allowing lateral movement in Windows environments." },
  { term:"Kerberoasting", definition:"An Active Directory attack requesting service tickets and cracking them offline to recover service account passwords — highly effective against weak passwords." },
  { term:"Active Directory", definition:"Microsoft's directory service providing authentication and authorization in Windows domains. Compromising AD is typically the ultimate objective in Windows network engagements." },
  { term:"Domain Controller", definition:"Server managing Active Directory — the highest-value target in Windows network penetration tests, as its compromise grants access to all domain resources." },
  { term:"Wireless Penetration Testing", definition:"Testing wireless networks for vulnerabilities including weak encryption (WEP/WPA2-TKIP), rogue access points, evil twin attacks, and client-side vulnerabilities." },
  { term:"Web Application Penetration Testing", definition:"Systematic testing of web applications for vulnerabilities including OWASP Top 10 issues: injection, broken authentication, XSS, IDOR, security misconfiguration, and more." },
  { term:"IoT Penetration Testing", definition:"Testing internet-connected devices for vulnerabilities including insecure firmware, default credentials, unencrypted communications, and insecure update mechanisms." },
  { term:"Pentest Report", definition:"The formal deliverable of a penetration test documenting methodology, findings, evidence, risk ratings, and prioritized recommendations for remediation." },
  { term:"Scoping", definition:"The pre-engagement process of determining which systems, networks, and applications are in-scope for testing. Proper scoping prevents legal issues and ensures the test aligns with client objectives." },
  { term:"PTES", definition:"The Penetration Testing Execution Standard, a framework defining seven phases: pre-engagement, intelligence gathering, threat modeling, vulnerability analysis, exploitation, post-exploitation, and reporting." },
  { term:"OSSTMM", definition:"The Open Source Security Testing Methodology Manual, a peer-reviewed methodology that quantifies operational security through repeatable, measurable tests across multiple channels." },
  { term:"NIST SP 800-115", definition:"A NIST technical guide to information security testing and assessment, outlining planning, discovery, attack, and reporting phases for security assessments." },
  { term:"OSINT", definition:"Open Source Intelligence, the collection of publicly available information about a target from search engines, social media, WHOIS, and public records to support reconnaissance." },
  { term:"Passive Reconnaissance", definition:"Gathering target information without directly interacting with its systems, such as using WHOIS, DNS records, or public databases, to avoid detection." },
  { term:"Active Reconnaissance", definition:"Directly probing a target's systems through scanning, enumeration, or banner grabbing to gather detailed information, at higher risk of detection." },
  { term:"SYN Scan", definition:"A stealthy Nmap TCP scan (-sS) that sends SYN packets and analyzes responses without completing the three-way handshake, also called a half-open scan." },
  { term:"TCP Connect Scan", definition:"An Nmap scan (-sT) that completes the full TCP three-way handshake to identify open ports. It is reliable but easily logged by the target." },
  { term:"UDP Scan", definition:"An Nmap scan (-sU) that probes UDP ports, useful for finding services like DNS, SNMP, and DHCP, though slow due to lack of connection acknowledgments." },
  { term:"Idle Scan", definition:"A stealthy Nmap scan (-sI) that spoofs a zombie host's IP to map open ports without revealing the attacker's true address, exploiting predictable IP ID sequences." },
  { term:"Banner Grabbing", definition:"Connecting to a service to capture its response banner, revealing software names and versions that help identify potential vulnerabilities." },
  { term:"Service Enumeration", definition:"The process of identifying running services, versions, and configurations on open ports to map the attack surface of a target host." },
  { term:"SMB Enumeration", definition:"Extracting information from the Server Message Block protocol, such as shares, users, and policies, often using tools like enum4linux or smbclient." },
  { term:"SNMP Enumeration", definition:"Querying the Simple Network Management Protocol using community strings to extract device configurations, routing tables, and user data via tools like snmpwalk." },
  { term:"DNS Enumeration", definition:"Discovering DNS records, subdomains, and zone transfer data to map a target's infrastructure, using tools like dig, nslookup, and dnsrecon." },
  { term:"Zone Transfer", definition:"A DNS operation (AXFR) that copies an entire zone's records between servers. Misconfigured servers allowing it can leak an organization's full DNS map." },
  { term:"Firewall Evasion", definition:"Techniques to bypass firewall filtering, such as fragmentation, source port manipulation, decoys, or using allowed ports, to reach protected hosts." },
  { term:"IDS Evasion", definition:"Methods to avoid detection by intrusion detection systems, including packet fragmentation, encoding, timing changes, and obfuscation of attack signatures." },
  { term:"Packet Fragmentation", definition:"Splitting attack payloads across multiple IP fragments to evade signature-based detection, using Nmap's -f flag or custom crafting tools." },
  { term:"OWASP Top 10", definition:"A regularly updated list of the ten most critical web application security risks, serving as an awareness baseline for developers and penetration testers." },
  { term:"SQL Injection", definition:"An attack that inserts malicious SQL into application input to manipulate database queries, enabling data theft, authentication bypass, or command execution." },
  { term:"Blind SQL Injection", definition:"A SQLi variant where the application returns no direct error or data, so the attacker infers results through boolean conditions or time delays." },
  { term:"Cross-Site Scripting", definition:"An attack (XSS) that injects malicious scripts into web pages viewed by others, allowing session theft, defacement, or redirection to malicious sites." },
  { term:"Stored XSS", definition:"A persistent cross-site scripting attack where the malicious script is saved on the server and served to every user who views the affected page." },
  { term:"Reflected XSS", definition:"A non-persistent cross-site scripting attack where injected script is immediately reflected back in the server's response, typically via a crafted link." },
  { term:"CSRF", definition:"Cross-Site Request Forgery, an attack that tricks an authenticated user's browser into submitting unwanted requests, performing actions without their consent." },
  { term:"SSRF", definition:"Server-Side Request Forgery, where an attacker coerces a server into making requests to unintended internal or external resources, often reaching internal services." },
  { term:"IDOR", definition:"Insecure Direct Object Reference, an access-control flaw where manipulating a parameter grants access to unauthorized objects like other users' records." },
  { term:"Directory Traversal", definition:"An attack that uses sequences like ../ to access files outside the web root, potentially exposing configuration files, credentials, or system data." },
  { term:"sqlmap", definition:"An open-source tool that automates the detection and exploitation of SQL injection flaws, supporting database fingerprinting, data extraction, and shell access." },
  { term:"Burp Suite", definition:"An integrated web application security testing platform providing an intercepting proxy, scanner, repeater, and intruder for manual and automated testing." },
  { term:"Web Shell", definition:"A malicious script uploaded to a web server that gives an attacker remote command execution and persistent access through a browser or client." },
  { term:"Command Injection", definition:"An attack that passes attacker-controlled input to a system shell, allowing arbitrary operating system commands to run on the vulnerable server." },
  { term:"File Upload Vulnerability", definition:"A flaw allowing attackers to upload malicious files, such as web shells, due to insufficient validation of file type, extension, or content." },
  { term:"XXE", definition:"XML External Entity injection, where a weakly configured XML parser processes external entity references, enabling file disclosure, SSRF, or denial of service." },
  { term:"WPA2 Attack", definition:"Exploiting weaknesses in WPA2-secured wireless networks, commonly by capturing the four-way handshake and cracking the pre-shared key offline." },
  { term:"WPA3 Attack", definition:"Targeting WPA3 networks through methods like Dragonblood downgrade and side-channel attacks against the Simultaneous Authentication of Equals handshake." },
  { term:"aircrack-ng", definition:"A wireless security suite for capturing packets, injecting frames, and cracking WEP and WPA/WPA2 pre-shared keys using captured handshakes." },
  { term:"Evil Twin", definition:"A rogue access point that impersonates a legitimate wireless network to lure clients into connecting, enabling credential capture and traffic interception." },
  { term:"Deauthentication Attack", definition:"Sending spoofed deauth frames to disconnect wireless clients from an access point, often to force a handshake capture or facilitate an evil twin." },
  { term:"WPS Attack", definition:"Exploiting Wi-Fi Protected Setup, particularly its weak PIN mechanism, using tools like Reaver to brute-force the PIN and recover the network passphrase." },
  { term:"Firmware Analysis", definition:"Extracting and examining device firmware to find hardcoded credentials, insecure functions, and vulnerabilities, using tools like binwalk and firmware-mod-kit." },
  { term:"Modbus", definition:"A widely used industrial serial and TCP protocol for communicating with PLCs and controllers. It lacks authentication, making ICS environments vulnerable." },
  { term:"ICS/SCADA", definition:"Industrial Control Systems and Supervisory Control and Data Acquisition environments that monitor and control physical processes, often using legacy insecure protocols." },
  { term:"PLC", definition:"A Programmable Logic Controller, a ruggedized industrial computer controlling machinery and processes. Compromise can cause physical damage or process disruption." },
  { term:"IoT Enumeration", definition:"Identifying and profiling Internet of Things devices, their services, firmware versions, and default credentials to assess the attack surface." },
  { term:"Buffer Overflow", definition:"A memory-corruption flaw where writing beyond a buffer's boundary overwrites adjacent memory, potentially overwriting return addresses to hijack execution." },
  { term:"Stack Overflow", definition:"A buffer overflow on the call stack that overwrites the saved return address, letting an attacker redirect execution to injected shellcode or gadgets." },
  { term:"Return-Oriented Programming", definition:"An exploitation technique (ROP) that chains short instruction sequences ending in return, called gadgets, to bypass non-executable memory protections." },
  { term:"NOP Sled", definition:"A sequence of no-operation instructions placed before shellcode so an imprecise jump still slides execution into the payload during exploitation." },
  { term:"Shellcode", definition:"A compact set of machine-code instructions injected during exploitation, typically to spawn a shell or establish a reverse connection to the attacker." },
  { term:"DEP", definition:"Data Execution Prevention, a memory protection that marks regions non-executable to stop injected code from running, often bypassed with ROP techniques." },
  { term:"ASLR", definition:"Address Space Layout Randomization, a defense that randomizes memory addresses of code and data to make exploitation harder by hiding predictable locations." },
  { term:"Pass-the-Ticket", definition:"An attack that reuses stolen or forged Kerberos tickets to authenticate as a user, including Golden and Silver ticket techniques in Active Directory." },
  { term:"Golden Ticket", definition:"A forged Kerberos TGT created with the KRBTGT account hash, granting an attacker persistent domain-wide access as any user, including domain admins." },
  { term:"BloodHound", definition:"A tool that maps Active Directory relationships using graph theory to reveal attack paths, privilege escalation routes, and misconfigurations." },
  { term:"Proxychains", definition:"A tool that forces TCP connections from applications through proxy servers such as SOCKS or HTTP, commonly used to route tools through a pivot host." },
  { term:"Port Forwarding", definition:"Redirecting network traffic from one host and port to another, used during pivoting to tunnel access to services on internal networks." },
  { term:"SSH Tunneling", definition:"Encapsulating traffic within an SSH connection to bypass restrictions or reach internal hosts, supporting local, remote, and dynamic forwarding modes." },
  { term:"AV/EDR Evasion", definition:"Techniques to bypass antivirus and endpoint detection and response tools, including obfuscation, encryption, in-memory execution, and payload encoding." },
  { term:"Mimikatz", definition:"A post-exploitation tool that extracts plaintext passwords, hashes, and Kerberos tickets from Windows memory, enabling credential theft and ticket attacks." },
  { term:"LLMNR Poisoning", definition:"An attack that responds to Link-Local Multicast Name Resolution queries to capture NTLM hashes, often using Responder for credential harvesting." },
  { term:"Executive Summary", definition:"The high-level, non-technical section of a penetration test report that summarizes findings, risk, and business impact for management and stakeholders." }
];
GLOSSARY_CPENT.sort((a, b) => a.term.localeCompare(b.term, undefined, { sensitivity: 'base' }));
