const GLOSSARY_CCZT = [
  { term:"Zero Trust", definition:"A security strategy based on 'never trust, always verify.' No user, device, or workload is trusted by default; every access request is authenticated, authorized, and continuously validated regardless of network location." },
  { term:"Zero Trust Architecture (ZTA)", definition:"An enterprise security architecture that applies zero trust principles to component relationships, workflow planning, and access policies, as defined in NIST SP 800-207." },
  { term:"Protect Surface", definition:"The critical Data, Applications, Assets, and Services (DAAS) that an organization must defend. Zero trust shrinks the focus to the protect surface rather than the ever-expanding attack surface." },
  { term:"Attack Surface", definition:"The total set of points where an attacker could attempt to enter or extract data. Zero trust reduces exposure by moving controls close to the protect surface." },
  { term:"Microsegmentation", definition:"Dividing a network into small, isolated segments (down to individual workloads) so that access between them is individually controlled, limiting lateral movement." },
  { term:"Policy Enforcement Point (PEP)", definition:"The component that enables, monitors, and terminates connections between a subject and a resource, enforcing the decision made by the policy decision point." },
  { term:"Policy Decision Point (PDP)", definition:"The logical component that decides whether to grant access, composed of the policy engine and policy administrator." },
  { term:"Policy Engine (PE)", definition:"The part of the PDP that makes the ultimate access decision by evaluating the trust algorithm against policy, identity, device posture, and context." },
  { term:"Policy Administrator (PA)", definition:"The part of the PDP that establishes or shuts down the communication path between subject and resource and issues session credentials based on the policy engine's decision." },
  { term:"Trust Algorithm", definition:"The process the policy engine uses to grant, deny, or revoke access to a resource, weighing inputs such as identity, device health, behavior, and threat intelligence." },
  { term:"Software-Defined Perimeter (SDP)", definition:"An approach that hides infrastructure and creates dynamic, one-to-one encrypted connections between authenticated users and the specific resources they are authorized to access." },
  { term:"Zero Trust Network Access (ZTNA)", definition:"A technology that provides secure remote access to applications based on identity and context, granting access to specific apps rather than the whole network." },
  { term:"Least Privilege", definition:"Granting subjects only the minimum access necessary to perform their function, for the minimum time needed. A core zero trust principle." },
  { term:"Continuous Verification", definition:"Repeatedly re-evaluating trust throughout a session rather than only at initial login, revoking access when risk signals change." },
  { term:"Implicit Trust Zone", definition:"An area where entities are trusted once inside (e.g., a traditional flat internal network). Zero trust aims to eliminate implicit trust zones." },
  { term:"NIST SP 800-207", definition:"The foundational NIST publication defining Zero Trust Architecture, its logical components (PE, PA, PEP), tenets, and deployment models." },
  { term:"Zero Trust Maturity Model", definition:"CISA's model describing progression across pillars (Identity, Devices, Networks, Applications & Workloads, Data) from traditional to optimal zero trust." },
  { term:"Assume Breach", definition:"A mindset that presumes attackers are already present, driving segmentation, least privilege, and continuous monitoring to limit blast radius." },
  { term:"Lateral Movement", definition:"An attacker's technique of moving through a network from an initial foothold to reach higher-value targets. Microsegmentation and least privilege constrain it." },
  { term:"Device Posture", definition:"The security state of a device (patch level, encryption, EDR presence, compliance) evaluated as part of an access decision." },
  { term:"Context-Aware Access", definition:"Access decisions that factor in dynamic context such as location, time, device health, and behavior, not just credentials." },
  { term:"Conditional Access", definition:"Policies that allow, block, or step-up authentication for a request based on conditions like risk level, device compliance, or location." },
  { term:"Just-In-Time Access", definition:"Granting privileged access only for the moment it is needed and revoking it afterward, reducing standing privilege." },
  { term:"Secure Access Service Edge (SASE)", definition:"A cloud-delivered model converging networking (SD-WAN) and security (SWG, CASB, ZTNA, FWaaS) to enforce zero trust access from the edge." },
  { term:"Security Service Edge (SSE)", definition:"The security half of SASE — the converged cloud-delivered security services (SWG, CASB, ZTNA) without the networking component." },
  { term:"Segmentation Gateway", definition:"A control point (often a next-generation firewall) placed close to the protect surface that enforces granular access policy between segments." },
  { term:"Kipling Method", definition:"A policy-writing approach using Who, What, When, Where, Why, and How to define granular zero trust access rules for the protect surface." },
  { term:"Identity-Centric Security", definition:"Making verified identity the primary control plane for access decisions, rather than network location or perimeter." },
  { term:"Trust Broker", definition:"An intermediary that authenticates subjects and brokers secure, policy-based connections to resources without exposing the network." },
  { term:"Continuous Diagnostics and Mitigation (CDM)", definition:"A program providing ongoing asset, identity, and configuration data used to inform zero trust policy decisions." },
];
GLOSSARY_CCZT.sort((a, b) => a.term.localeCompare(b.term, undefined, { sensitivity: 'base' }));
