const GLOSSARY_SECX = [
  { term:"Security Architecture", definition:"The set of design principles, guidelines, and models directing how security is structured and implemented across an enterprise to meet business and risk objectives." },
  { term:"Zero Trust", definition:"A security strategy based on 'never trust, always verify' — no implicit trust is granted to any user, device, or network location; all access must be explicitly verified." },
  { term:"Threat Intelligence", definition:"Evidence-based knowledge about existing or emerging threats that can be used to inform security decisions, including context, mechanisms, indicators, and actionable advice." },
  { term:"Threat Modeling", definition:"A structured process for identifying potential threats to a system during design, analyzing their likelihood and impact, and determining appropriate mitigations." },
  { term:"Attack Surface", definition:"The total set of exploitable vulnerabilities, entry points, and exposed components that an attacker could use to compromise a system or organization." },
  { term:"Lateral Movement", definition:"Techniques attackers use to progressively move through a network after gaining initial access, seeking to expand privileges and reach target assets." },
  { term:"Persistence", definition:"Techniques adversaries use to maintain access to systems across interruptions such as restarts, credential changes, or other disruptions." },
  { term:"Defense in Depth", definition:"A layered security strategy where multiple independent controls protect assets so that failure of one layer does not compromise overall security." },
  { term:"Supply Chain Security", definition:"Security measures addressing risks introduced through third-party software, hardware, or services integrated into an organization's systems." },
  { term:"Secure Software Development", definition:"Integrating security requirements, design review, testing, and verification throughout the software development lifecycle to produce resilient applications." },
  { term:"Infrastructure as Code", definition:"Managing infrastructure through machine-readable configuration files rather than manual processes, enabling consistent, auditable, and version-controlled deployments." },
  { term:"Container Security", definition:"Security controls for containerized workloads including image scanning, runtime protection, network policies, and least-privilege configurations." },
  { term:"Cloud Security Posture Management", definition:"Automated tools continuously monitoring cloud infrastructure configurations and comparing them against security best practices and compliance requirements." },
  { term:"Microsegmentation", definition:"Fine-grained network segmentation creating security zones at the workload or application level, minimizing the blast radius of a successful breach." },
  { term:"Deception Technology", definition:"Security controls including honeypots and honey tokens that lure attackers into fake environments, detecting intrusions and gathering threat intelligence." },
  { term:"Breach and Attack Simulation", definition:"Automated, continuous simulation of attacker tactics and techniques against real production environments to validate security control effectiveness." },
  { term:"Extended Detection and Response", definition:"Unified security platform integrating telemetry from endpoints, networks, cloud, and applications into a single detection and response capability." },
  { term:"Security Orchestration", definition:"The automated coordination of multiple security tools and processes to reduce manual effort, accelerate response, and ensure consistent handling of security events." },
  { term:"Resilience", definition:"An organization's ability to anticipate, withstand, recover from, and adapt to adverse conditions, including cyberattacks, without critical business function failure." },
  { term:"Data Classification", definition:"Organizing data into categories based on sensitivity and business value, determining appropriate handling, protection, and retention requirements for each category." },
  { term:"Cryptographic Agility", definition:"The ability of a system to switch between cryptographic algorithms quickly when a current algorithm is deprecated or broken, without major architectural changes." },
  { term:"Post-Quantum Cryptography", definition:"Cryptographic algorithms designed to remain secure against attacks from quantum computers, addressing the threat to current RSA and ECC-based systems." },
  { term:"Identity-Centric Security", definition:"An architectural approach treating verified identity as the primary security perimeter, replacing or augmenting traditional network-based perimeter controls." },
  { term:"Privileged Access Management", definition:"Solutions and processes controlling, monitoring, and auditing the use of privileged accounts to prevent credential abuse and limit blast radius from compromise." },
  { term:"Security Metrics", definition:"Quantifiable measures used to track the effectiveness of security controls, demonstrate risk reduction, and communicate security posture to leadership." },
  { term:"Risk-Informed Architecture", definition:"Security design decisions made based on analysis of actual threats, business impact, and risk tolerance rather than blanket compliance requirements." },
  { term:"Secure Design Principles", definition:"Foundational guidelines for building secure systems: least privilege, fail-secure, defense in depth, economy of mechanism, and complete mediation." },
  { term:"API Security", definition:"Controls protecting application programming interfaces from attacks including injection, authentication bypass, broken object-level authorization, and excessive data exposure." },
  { term:"MITRE ATT&CK", definition:"A globally accessible knowledge base of adversary tactics, techniques, and procedures based on real-world observations, used to improve threat detection and response." },
  { term:"Red Team", definition:"A dedicated group authorized to simulate real adversary attacks against an organization to test defenses, identify gaps, and improve security posture." }
];
