const GLOSSARY_CRISC = [
  { term:"Risk", definition:"The probability that a threat will exploit a vulnerability, resulting in harm to an asset. In CRISC, risk is expressed as the combination of likelihood and impact." },
  { term:"Threat", definition:"Any potential event or action that could cause harm to an organization's assets. Threats can be natural, accidental, or deliberate in origin." },
  { term:"Vulnerability", definition:"A weakness in a system, process, or control that could be exploited by a threat to cause harm." },
  { term:"Risk Appetite", definition:"The amount and type of risk an organization is willing to accept in pursuit of its objectives. Defined by the board and senior management." },
  { term:"Risk Tolerance", definition:"The acceptable deviation from the organization's risk appetite — the operational boundaries within which risk can vary." },
  { term:"Inherent Risk", definition:"The risk that exists before any controls are applied. Represents the raw exposure level without mitigation." },
  { term:"Residual Risk", definition:"The risk remaining after controls have been applied. Organizations must accept, transfer, or further reduce residual risk." },
  { term:"Control", definition:"A safeguard or countermeasure used to reduce the likelihood or impact of a risk. Controls can be preventive, detective, or corrective." },
  { term:"Risk Register", definition:"A document recording identified risks, their assessment results, assigned owners, and treatment plans. Central artifact of risk management." },
  { term:"Risk Owner", definition:"The individual or entity accountable for managing a specific risk, ensuring treatment plans are implemented and effective." },
  { term:"Risk Treatment", definition:"The process of selecting and implementing options to address risk. Options include avoidance, mitigation, transfer, and acceptance." },
  { term:"Risk Avoidance", definition:"A risk response that eliminates the risk entirely by deciding not to engage in the activity that creates it." },
  { term:"Risk Mitigation", definition:"A risk response that reduces the likelihood or impact of a risk through controls, process changes, or other measures." },
  { term:"Risk Transfer", definition:"A risk response that shifts financial consequences to a third party, typically through insurance or contractual arrangements." },
  { term:"Risk Acceptance", definition:"A deliberate decision to accept the consequences of a risk without taking action, when the cost of mitigation exceeds the benefit." },
  { term:"Control Effectiveness", definition:"The degree to which a control achieves its intended objective of reducing risk likelihood or impact." },
  { term:"Control Deficiency", definition:"A gap or weakness in a control that prevents it from fully achieving its risk reduction objective." },
  { term:"Business Impact Analysis", definition:"A process that identifies critical business functions, the minimum resources required to sustain them, and the impact of their disruption over time." },
  { term:"Risk Assessment", definition:"The overall process of risk identification, analysis, and evaluation. Produces a prioritized list of risks requiring treatment." },
  { term:"Quantitative Risk Analysis", definition:"Risk analysis using numerical values and probability estimates to produce monetary risk exposure figures (ALE, SLE)." },
  { term:"Qualitative Risk Analysis", definition:"Risk analysis using descriptive categories (high/medium/low) to rank risks when precise numerical data is unavailable." },
  { term:"Risk Scenario", definition:"A narrative describing a specific risk event: the threat actor, threat event, vulnerability exploited, and potential business impact." },
  { term:"Control Framework", definition:"A structured set of controls organized to manage specific risk areas. Examples include COBIT, NIST CSF, ISO 27001 Annex A." },
  { term:"Governance", definition:"The system of rules, practices, and processes by which an organization is directed and controlled, including risk oversight structures." },
  { term:"IT Risk Management", definition:"The discipline of identifying, assessing, and managing risks arising from the use of information technology in business operations." },
  { term:"Third-Party Risk", definition:"Risk arising from reliance on external vendors, suppliers, or service providers who have access to or process organizational data." },
  { term:"Operational Risk", definition:"Risk of loss from inadequate or failed internal processes, people, systems, or external events — distinct from strategic or financial risk." },
  { term:"Compliance Risk", definition:"Risk of legal or regulatory sanctions, financial penalties, or reputational damage from failing to comply with applicable laws and regulations." },
  { term:"Reputational Risk", definition:"Risk of damage to an organization's brand, public standing, or stakeholder trust resulting from adverse events or poor decisions." },
  { term:"COBIT", definition:"Control Objectives for Information and Related Technologies — ISACA's governance framework aligning IT processes with business objectives and risk management." },
  { term:"Risk Culture", definition:"The shared values, beliefs, and behaviors within an organization that shape how risk is identified, discussed, and managed." },
  { term:"Lines of Defense", definition:"A risk governance model: 1st line (operations), 2nd line (risk/compliance functions), 3rd line (internal audit)." },
  { term:"Key Risk Indicator", definition:"A forward-looking metric that signals when risk exposure is increasing toward or beyond acceptable thresholds, enabling proactive management." },
  { term:"Audit Trail", definition:"A chronological record of system activities that provides evidence for reconstructing and examining events — critical for risk management accountability." },
  { term:"Change Management", definition:"Formal process for controlling modifications to IT systems to prevent unauthorized changes that could introduce new risks." },
  { term:"Patch Management", definition:"Systematic process for acquiring, testing, and deploying software updates to address vulnerabilities and reduce technical risk." }
];
