const GLOSSARY_CPENT = [
  { term:"Penetration Testing", definition:"An authorized simulated cyberattack against a computer system, network, or application to evaluate security defenses and identify exploitable vulnerabilities before real attackers do." },
  { term:"Rules of Engagement", definition:"A written agreement between the penetration tester and client defining the scope, permitted activities, time windows, out-of-scope systems, escalation contacts, and legal authorization for the test." },
  { term:"Reconnaissance", definition:"The information-gathering phase of a penetration test. Passive recon uses public sources without touching the target; active recon directly interacts with target systems." },
  { term:"Footprinting", definition:"Systematically gathering information about a target organization including network ranges, domain names, employee details, and technology stack before active testing begins." },
  { term:"Scanning", definition:"Using network tools to discover live hosts, open ports, running services, and OS versions on target systems. Forms the technical map used for subsequent exploitation." },
  { term:"Enumeration", definition:"Actively querying target systems to extract detailed information including usernames, shares, services, and configuration details that can be used to identify attack vectors." },
  { term:"Vulnerability Assessment", definition:"Identifying and classifying security weaknesses in a system. Unlike penetration testing, vulnerability assessment does not attempt to exploit findings." },
  { term:"Exploitation", definition:"Using identified vulnerabilities to gain unauthorized access to a system, demonstrating real-world impact. Controlled, documented, and within agreed scope during penetration tests." },
  { term:"Privilege Escalation", definition:"After gaining initial access, techniques for acquiring higher-level privileges (admin/root) on a compromised system, enabling broader access and impact demonstration." },
  { term:"Lateral Movement", definition:"Techniques for moving through a network from an initial foothold to reach additional systems, particularly high-value targets like domain controllers." },
  { term:"Persistence", definition:"Techniques for maintaining access to compromised systems across reboots, password changes, or incident response activities — demonstrates how real attackers maintain footholds." },
  { term:"Post-Exploitation", definition:"Actions taken after gaining access to a system: privilege escalation, lateral movement, data exfiltration simulation, and persistence mechanisms." },
  { term:"Pivoting", definition:"Using a compromised system as a relay point to reach otherwise inaccessible network segments, extending the penetration test into internal or segregated networks." },
  { term:"Exfiltration", definition:"Simulating an attacker's ability to extract sensitive data from a compromised environment, demonstrating the potential impact of a real breach." },
  { term:"Payload", definition:"Code or data delivered through exploitation that performs the attacker's desired action on a target system, such as establishing a reverse shell or executing commands." },
  { term:"Shell", definition:"Command-line interface on a compromised system. A bind shell listens on the target; a reverse shell connects back to the attacker, bypassing firewalls." },
  { term:"Bind Shell", definition:"A compromised system opens a port and listens for incoming connections from the attacker. Less common due to firewall restrictions on inbound connections." },
  { term:"Reverse Shell", definition:"A compromised system connects outbound to the attacker's machine. Preferred method as most firewalls allow outbound connections." },
  { term:"Social Engineering", definition:"Manipulating people through psychological tactics to divulge confidential information or perform actions that compromise security. Includes phishing, pretexting, and vishing." },
  { term:"Phishing", definition:"Fraudulent emails impersonating legitimate entities to trick recipients into revealing credentials, clicking malicious links, or opening malware attachments." },
  { term:"Spear Phishing", definition:"Highly targeted phishing using personalized content and context specific to an individual or organization, dramatically increasing success rates over generic phishing." },
  { term:"Password Attack", definition:"Attempts to recover passwords through brute force, dictionary attacks, password spraying, or credential stuffing from breach databases." },
  { term:"Pass-the-Hash", definition:"Authentication attack using captured NTLM password hashes directly without needing to crack them, allowing lateral movement in Windows environments." },
  { term:"Kerberoasting", definition:"An Active Directory attack requesting service tickets and cracking them offline to recover service account passwords — highly effective against weak passwords." },
  { term:"Active Directory", definition:"Microsoft's directory service providing authentication and authorization in Windows domains. Compromising AD is typically the ultimate objective in Windows network engagements." },
  { term:"Domain Controller", definition:"Server managing Active Directory — the highest-value target in Windows network penetration tests, as its compromise grants access to all domain resources." },
  { term:"Wireless Penetration Testing", definition:"Testing wireless networks for vulnerabilities including weak encryption (WEP/WPA2-TKIP), rogue access points, evil twin attacks, and client-side vulnerabilities." },
  { term:"Web Application Penetration Testing", definition:"Systematic testing of web applications for vulnerabilities including OWASP Top 10 issues: injection, broken authentication, XSS, IDOR, security misconfiguration, and more." },
  { term:"IoT Penetration Testing", definition:"Testing internet-connected devices for vulnerabilities including insecure firmware, default credentials, unencrypted communications, and insecure update mechanisms." },
  { term:"Pentest Report", definition:"The formal deliverable of a penetration test documenting methodology, findings, evidence, risk ratings, and prioritized recommendations for remediation." }
];
