const GLOSSARY_ECIH = [
  { term:"Incident", definition:"Any event that violates or threatens to violate an organization's security policies, acceptable use policies, or standard security practices." },
  { term:"Security Event", definition:"An observable occurrence in a system or network. Not all security events are incidents — events become incidents when they negatively impact confidentiality, integrity, or availability." },
  { term:"Incident Response", definition:"An organized approach to addressing and managing the aftermath of a security breach or attack. The goal is to handle the situation in a way that limits damage, reduces recovery time, and minimizes costs." },
  { term:"Incident Response Plan", definition:"A documented set of procedures for detecting, containing, eradicating, and recovering from cybersecurity incidents. Must be tested regularly through exercises." },
  { term:"PICERL Model", definition:"Preparation, Identification, Containment, Eradication, Recovery, Lessons Learned — a widely used framework for structuring the incident response lifecycle." },
  { term:"Preparation", definition:"The incident response phase establishing capabilities before incidents occur: policies, procedures, training, tools, and communication channels." },
  { term:"Identification", definition:"The incident response phase detecting and confirming that an incident has occurred, determining its scope, and classifying its severity." },
  { term:"Containment", definition:"The incident response phase isolating affected systems to prevent incident spread while preserving evidence. Can be short-term (immediate isolation) or long-term (network segmentation)." },
  { term:"Eradication", definition:"The incident response phase removing the root cause of the incident — malware, unauthorized accounts, or exploited vulnerabilities — from all affected systems." },
  { term:"Recovery", definition:"The incident response phase restoring affected systems to normal operation, verifying they are functioning correctly, and monitoring for any signs of recurrence." },
  { term:"Lessons Learned", definition:"The final incident response phase conducting a post-incident review to identify what happened, what was done, what worked, what failed, and how to improve future response." },
  { term:"Triage", definition:"Rapid assessment of a security event to determine its severity, scope, and required response priority, enabling efficient allocation of incident response resources." },
  { term:"Escalation", definition:"The process of notifying higher-level personnel, management, or specialized teams when an incident exceeds the current responder's authority or expertise." },
  { term:"Indicators of Compromise", definition:"Forensic data — IP addresses, domain names, file hashes, registry keys — that signal a system has been compromised. Used to detect infections across an environment." },
  { term:"Threat Intelligence", definition:"Actionable information about adversaries including their tactics, techniques, motivations, and targets, used to improve detection, response, and prevention capabilities." },
  { term:"Root Cause Analysis", definition:"A structured investigation process determining the fundamental cause of an incident rather than just treating symptoms, preventing recurrence." },
  { term:"Forensic Preservation", definition:"Steps taken during incident response to preserve digital evidence in an unaltered state for later investigation or legal proceedings, including memory capture and disk imaging." },
  { term:"Malware Incident", definition:"A security incident caused by malicious software including viruses, worms, ransomware, spyware, or trojans compromising system integrity, confidentiality, or availability." },
  { term:"Ransomware", definition:"Malware encrypting victim's data and demanding payment for the decryption key. Response requires isolation, backup recovery, and decision-making on ransom payment policy." },
  { term:"Phishing", definition:"Social engineering attack using fraudulent emails to trick recipients into revealing credentials, clicking malicious links, or downloading malware." },
  { term:"Insider Threat", definition:"A security risk originating from current or former employees, contractors, or partners with authorized access who misuse that access intentionally or unintentionally." },
  { term:"DDoS Attack", definition:"Distributed Denial of Service — coordinated attack overwhelming a target with traffic from many sources, disrupting legitimate access. Requires detection, traffic scrubbing, and ISP coordination." },
  { term:"Network Security Incident", definition:"An incident affecting network infrastructure or communications, including unauthorized access, traffic interception, denial of service, or routing manipulation." },
  { term:"Cloud Incident", definition:"A security incident occurring in cloud environments, complicated by shared responsibility models, multi-tenancy, limited visibility, and provider-controlled infrastructure." },
  { term:"Web Application Incident", definition:"Compromise of web-facing applications through attacks such as SQL injection, XSS, CSRF, or authentication bypass, requiring application-layer investigation and patching." },
  { term:"Playbook", definition:"A documented, step-by-step procedure for responding to a specific type of security incident, ensuring consistent, efficient response regardless of which analyst handles it." },
  { term:"Mean Time to Detect", definition:"The average time from when an incident begins to when it is detected. A key metric for measuring the effectiveness of security monitoring capabilities." },
  { term:"Mean Time to Respond", definition:"The average time from incident detection to containment. Measures the speed and effectiveness of the incident response process." },
  { term:"Tabletop Exercise", definition:"A discussion-based simulation where stakeholders walk through a hypothetical incident scenario to test the incident response plan without actually activating response procedures." },
  { term:"Cyber Kill Chain", definition:"A model describing the stages of a cyberattack: Reconnaissance, Weaponization, Delivery, Exploitation, Installation, Command & Control, Actions on Objectives. Used to identify where to interrupt attacks." }
];
