const GLOSSARY_ISSAP = [
  { term:"Security Architecture", definition:"A set of design principles, guidelines, and models that direct the design and implementation of security controls across an enterprise to meet business objectives." },
  { term:"SABSA", definition:"Sherwood Applied Business Security Architecture — a layered enterprise security architecture framework that starts from business context and derives security requirements at each architectural layer." },
  { term:"Zero Trust", definition:"A security paradigm based on 'never trust, always verify' — no implicit trust is granted based on network location; every access request must be explicitly authenticated and authorized." },
  { term:"Defense in Depth", definition:"A security strategy employing multiple independent layers of controls so that if one fails, others continue to provide protection. No single control is relied upon exclusively." },
  { term:"Least Privilege", definition:"The principle that subjects should be granted only the minimum access rights necessary to perform their legitimate functions, and no more." },
  { term:"Separation of Duties", definition:"An architectural control that divides critical tasks across multiple people or roles so no single individual can complete a sensitive process alone, reducing fraud and error risk." },
  { term:"Economy of Mechanism", definition:"The security design principle stating that security mechanisms should be kept as simple as possible — complexity increases the attack surface and makes verification harder." },
  { term:"Fail-Secure", definition:"The design principle that when a security control fails, it should default to a denied/closed state rather than permitting access. Also known as fail-closed or fail-safe." },
  { term:"Open Design", definition:"The security principle that the security of a mechanism should not depend on the secrecy of its design, only on the secrecy of keys or other secret values." },
  { term:"Complete Mediation", definition:"Every access to every resource must be checked against the access control policy — no caching of permissions that might become stale." },
  { term:"Microsegmentation", definition:"Network architecture technique creating granular security zones down to individual workloads, restricting east-west lateral movement between segments." },
  { term:"Security Domain", definition:"A set of resources, users, and processes sharing the same security policy and trust level. Boundaries between domains require access controls." },
  { term:"Trust Boundary", definition:"A point in an architecture where data crosses between components with different trust levels, requiring validation, authentication, or re-authorization." },
  { term:"Federated Identity", definition:"An arrangement allowing users to authenticate once with a home identity provider and access resources at multiple service providers without re-authenticating." },
  { term:"Public Key Infrastructure", definition:"The complete set of hardware, software, people, policies, and procedures needed to create, manage, distribute, use, store, and revoke digital certificates." },
  { term:"Certificate Authority", definition:"A trusted third party that issues digital certificates binding a public key to a verified identity, forming the foundation of PKI trust." },
  { term:"Key Ceremony", definition:"A formal, audited procedure for generating or managing cryptographic keys, especially root CA keys, conducted with multiple witnesses to ensure integrity." },
  { term:"Hardware Security Module", definition:"A physical computing device providing secure generation, storage, and management of cryptographic keys in a tamper-resistant enclosure." },
  { term:"Post-Quantum Cryptography", definition:"Cryptographic algorithms designed to resist attacks from quantum computers, including lattice-based algorithms such as CRYSTALS-Kyber and CRYSTALS-Dilithium standardized by NIST." },
  { term:"Authenticated Encryption", definition:"Encryption providing both confidentiality and integrity/authenticity in a single operation. AES-GCM is the primary example used in TLS 1.3." },
  { term:"Security Operations Center", definition:"A centralized team and facility providing continuous monitoring, detection, analysis, and coordinated response to cybersecurity events." },
  { term:"Security Orchestration", definition:"The automated coordination of multiple security tools and processes to streamline detection and response workflows, reducing manual analyst effort." },
  { term:"Gap Analysis", definition:"A comparison of the current security posture against a target architecture, identifying deficiencies and producing a prioritized remediation roadmap." },
  { term:"Architecture Review Board", definition:"A governance body responsible for reviewing and approving architectural decisions to ensure alignment with standards, principles, and business requirements." },
  { term:"Threat Modeling", definition:"A structured analysis process identifying potential threats to a system, their attack vectors, and appropriate countermeasures during design." },
  { term:"Attack Surface", definition:"The sum of all possible points where an attacker could attempt to enter or extract data from an environment. Reducing attack surface is a key architectural objective." },
  { term:"Secure by Design", definition:"An approach where security requirements are built into systems from the earliest design stages rather than added as an afterthought." },
  { term:"Network Segmentation", definition:"Dividing a network into isolated zones to contain breaches, limit lateral movement, and enforce different security policies for different asset groups." },
  { term:"SASE", definition:"Secure Access Service Edge — a cloud-delivered architecture converging network services (SD-WAN) and security services (SWG, CASB, ZTNA) into a single platform." },
  { term:"Business-Driven Security", definition:"The principle that security architecture decisions must be grounded in business objectives, risk appetite, and operational requirements rather than technical preferences." },
  { term:"Security Posture", definition:"The overall cybersecurity strength of an organization, encompassing its people, processes, technology, and governance as measured against threats and requirements." },
  { term:"Crown Jewels", definition:"An organization's most critical and sensitive assets whose compromise would have the most severe business impact. Architecture should prioritize their protection." },
  { term:"Risk-Based Architecture", definition:"An approach to security architecture where control decisions are driven by risk analysis rather than prescriptive checklists, proportionate to actual threat exposure." }
];
