// ── CISSP Questions (IDs 30001–30074) ─────────────────────────────────────────
const QUESTIONS_CISSP = [

// ─── DOMAIN 1: Security and Risk Management ───────────────────────────────────
{id:30001,domain:1,level:1,question:"The CIA triad in information security stands for:",options:["A. Cyber Intelligence and Analytics","B. Confidentiality, Integrity, and Availability","C. Compliance, Identity, and Authorization","D. Control, Infrastructure, and Architecture"],correct:1,explanation:"CIA is the foundation of information security: Confidentiality (only authorized parties access data), Integrity (data is accurate and unmodified), Availability (systems accessible when needed by authorized users)."},
{id:30002,domain:1,level:1,question:"Which of the following BEST describes 'data integrity'?",options:["A. Ensuring data is accessible only to authorized users","B. Ensuring data remains accurate, complete, and unmodified except through authorized processes","C. Encrypting data to prevent unauthorized disclosure during transmission","D. Ensuring data systems maintain 99.9% uptime availability"],correct:1,explanation:"Integrity ensures data is accurate and has not been tampered with. It is protected through checksums, hashes, digital signatures, input validation, access controls, and audit logging."},
{id:30003,domain:1,level:1,question:"Legal liability for an organization's failure to protect information is PRIMARILY based on:",options:["A. Due process rights of employees","B. Sovereign immunity principles","C. Due care and due diligence obligations","D. Respondeat superior doctrine"],correct:2,explanation:"Due care requires taking reasonable steps to protect assets (the 'prudent person' standard). Due diligence requires verifying that protections are working continuously. Both form the foundation for security negligence liability."},
{id:30004,domain:1,level:1,question:"Which standard applies MOST directly to organizations that process payment card data?",options:["A. HIPAA (Health Insurance Portability and Accountability Act)","B. SOX (Sarbanes-Oxley Act)","C. PCI DSS (Payment Card Industry Data Security Standard)","D. FISMA (Federal Information Security Modernization Act)"],correct:2,explanation:"PCI DSS applies to any organization that stores, processes, or transmits cardholder data. It specifies technical and operational security controls required to protect payment card information."},
{id:30005,domain:1,level:2,question:"'Non-repudiation' in information security means:",options:["A. The ability to restore data to a known good state after corruption","B. Ensuring data is not modified during transmission over a network","C. Proving that an action occurred and the actor cannot later deny it","D. Preventing unauthorized users from accessing a system or resource"],correct:2,explanation:"Non-repudiation prevents a party from denying an action they performed. Digital signatures provide non-repudiation. It is critical for legal evidence, audit trails, and transaction accountability."},
{id:30006,domain:1,level:2,question:"The 'Annualized Loss Expectancy' (ALE) is calculated as:",options:["A. Asset Value multiplied by Threat Frequency","B. Single Loss Expectancy (SLE) multiplied by Annualized Rate of Occurrence (ARO)","C. Total organizational risk minus the acceptable risk threshold","D. Maximum tolerable downtime multiplied by hourly cost of outage"],correct:1,explanation:"ALE = SLE × ARO. SLE = Asset Value × Exposure Factor. ALE represents expected annual financial loss from a threat, enabling cost-benefit analysis: controls are justified when their cost < ALE reduction."},
{id:30007,domain:1,level:2,question:"Which framework organizes cybersecurity activities into: Identify, Protect, Detect, Respond, Recover?",options:["A. ISO 9001 (Quality Management Systems)","B. NIST Cybersecurity Framework (CSF)","C. ITIL (IT Infrastructure Library)","D. PMBOK (Project Management Body of Knowledge)"],correct:1,explanation:"The NIST CSF provides a common language for managing cybersecurity risk through five functions: Identify, Protect, Detect, Respond, and Recover. It is flexible and applicable across industries and organization sizes."},
{id:30008,domain:1,level:2,question:"What is the MAIN purpose of threat modeling?",options:["A. To train developers in secure coding practices","B. To identify potential threats early in system design and develop mitigating controls","C. To monitor production systems for active threats in real time","D. To measure the maturity of the organization's threat intelligence program"],correct:1,explanation:"Threat modeling (STRIDE, PASTA, LINDDUN) identifies what could go wrong in a system during design, who might cause harm, and what controls mitigate those threats. Early identification is the most cost-effective approach."},
{id:30009,domain:1,level:3,question:"When a risk treatment cost exceeds the potential loss, the MOST appropriate action is:",options:["A. Immediately eliminate the business activity creating the risk","B. Formally accept the risk after documenting the decision and obtaining management approval","C. Implement the control regardless because compliance may require it","D. Transfer the risk through cyber insurance without management review"],correct:1,explanation:"Risk acceptance is appropriate when mitigation cost > potential loss, provided the decision is made consciously by authorized management with full information and documented approval. Undocumented, default risk acceptance is not acceptable governance."},
{id:30010,domain:1,level:3,question:"The 'principle of privacy by design' means:",options:["A. Privacy controls are implemented after system deployment in response to complaints","B. Privacy protections are integrated into system architecture from the beginning of design","C. Privacy features are optional add-ons that users can enable if desired","D. Privacy compliance is outsourced to a third-party privacy vendor"],correct:1,explanation:"Privacy by design (Ann Cavoukian) embeds privacy protections proactively into system architecture and business practices from the start, rather than retrofitting after deployment. GDPR's Article 25 codifies this principle."},

// ─── DOMAIN 2: Asset Security ─────────────────────────────────────────────────
{id:30011,domain:2,level:1,question:"Who is responsible for defining the classification level of data assets?",options:["A. The IT security team and CISO","B. The data owner — the business function responsible for the data","C. External auditors reviewing the data classification scheme","D. The IT custodian who manages the systems storing the data"],correct:1,explanation:"The data owner (usually a business manager) is responsible for classifying data based on its sensitivity and value. IT implements technical controls; the business owner makes classification and access policy decisions."},
{id:30012,domain:2,level:1,question:"What is 'data remanence'?",options:["A. Data that is replicated across multiple geographically distributed storage systems","B. Residual data that persists on storage media after deletion and may be recoverable","C. The defined retention period for data under applicable regulatory requirements","D. Data that remains encrypted even after the encryption key has been destroyed"],correct:1,explanation:"Data remanence is residual data remaining on storage media after deletion. Secure sanitization methods (cryptographic erase, degaussing, physical destruction) are required to prevent unauthorized recovery of sensitive data."},
{id:30013,domain:2,level:2,question:"What is 'data sovereignty'?",options:["A. An organization's exclusive legal ownership of all data it creates and processes","B. The principle that data is subject to the laws of the jurisdiction where it is stored","C. The individual's right to control how their personal data is used","D. A data owner's authority to grant or revoke access to data assets"],correct:1,explanation:"Data sovereignty means data stored in a country is subject to that country's laws, including government access requirements. This drives decisions about cloud data residency and can create compliance conflicts across jurisdictions."},
{id:30014,domain:2,level:2,question:"The difference between a 'data owner' and 'data custodian' is:",options:["A. They hold identical responsibilities with different titles","B. Data owner sets classification and access policy; data custodian implements and maintains technical controls","C. Data owner manages backup procedures; data custodian manages user access rights","D. Data custodian governs data quality; data owner manages security controls"],correct:1,explanation:"Data owner: business manager who sets classification, access policies, and usage rules. Data custodian: IT function that implements technical controls (backups, encryption, access systems) to protect the data as directed by the owner."},
{id:30015,domain:2,level:2,question:"What is the purpose of a data retention policy?",options:["A. To ensure all organizational data is retained permanently for potential legal use","B. To define how long data should be kept and when and how it must be securely destroyed","C. To establish the backup frequency and off-site storage schedule","D. To classify data according to applicable regulatory requirements"],correct:1,explanation:"Retention policies balance business needs, legal hold obligations, and regulatory requirements against privacy and storage costs. They define retention periods per data type and ensure secure destruction when retention expires."},
{id:30016,domain:2,level:3,question:"Which data sanitization method provides the HIGHEST assurance for highly classified storage media?",options:["A. Standard file deletion followed by empty recycle bin","B. Department of Defense (DoD) 5220.22-M multi-pass overwrite","C. Physical destruction: shredding, degaussing, or incineration","D. Full-disk encryption followed by key deletion"],correct:2,explanation:"Physical destruction provides the highest assurance that data cannot be recovered from storage media. Multi-pass overwrite has limitations with modern SSDs and flash storage. For highly classified data, physical destruction is the only certain method."},
{id:30017,domain:2,level:3,question:"Under GDPR, when an organization collects personal data for marketing, they MUST ensure:",options:["A. The data is stored exclusively in EU member state data centers","B. They have a lawful basis for processing and data subjects can exercise their rights","C. All personal data used for marketing is encrypted with AES-256 minimum","D. Only anonymized or pseudonymized data is used for any marketing activity"],correct:1,explanation:"GDPR requires a lawful basis for each processing purpose (consent, legitimate interest, contract, etc.) and grants individuals rights: access, rectification, erasure, portability, restriction, and objection. Both legal and technical compliance is required."},
{id:30018,domain:2,level:3,question:"'Scoping and tailoring' of security control baselines means:",options:["A. Reducing the number of security team members responsible for each control","B. Selecting controls from a standard baseline and adjusting them to fit the organization's specific environment and risks","C. Building a completely custom security framework from scratch","D. Limiting security controls to only those explicitly required by regulations"],correct:1,explanation:"Organizations start with a baseline (NIST SP 800-53, CIS Controls, ISO 27001 Annex A) and tailor it: excluding non-applicable controls, adding organization-specific ones, and adjusting parameters to match their environment and risk profile."},

// ─── DOMAIN 3: Security Architecture and Engineering ─────────────────────────
{id:30019,domain:3,level:1,question:"The Bell-LaPadula security model is PRIMARILY designed to protect:",options:["A. Data integrity from unauthorized modification","B. System availability from denial of service attacks","C. Data confidentiality through mandatory access control rules","D. Non-repudiation of user transactions"],correct:2,explanation:"Bell-LaPadula enforces confidentiality with two rules: 'no read up' (subjects cannot read data at higher classification) and 'no write down' (subjects cannot write to lower classification), preventing information leakage downward."},
{id:30020,domain:3,level:1,question:"The Biba integrity model enforces:",options:["A. Data confidentiality through mandatory clearance levels","B. Data integrity through 'no write up, no read down' rules","C. System availability through redundancy and failover mechanisms","D. Access control through role-based permission assignments"],correct:1,explanation:"Biba addresses integrity: 'no write up' (don't corrupt higher integrity data with lower integrity data) and 'no read down' (don't be contaminated by reading lower integrity data). It is the integrity complement to Bell-LaPadula."},
{id:30021,domain:3,level:2,question:"The security principle that 'security should not depend on the secrecy of the design, only on the secrecy of keys' is known as:",options:["A. The principle of least privilege","B. Defense in depth","C. Kerckhoffs's principle (open design)","D. The principle of complete mediation"],correct:2,explanation:"Kerckhoffs's principle: a cryptosystem should be secure even if everything about the system, except the key, is publicly known. Security through obscurity (hiding the algorithm) is not a reliable security strategy."},
{id:30022,domain:3,level:2,question:"Which cryptography property ensures that compromise of a long-term key does not expose past encrypted sessions?",options:["A. End-to-end encryption with AES-256","B. Perfect Forward Secrecy (PFS) using ephemeral key exchange","C. Public key infrastructure with certificate pinning","D. Key escrow with a trusted third-party holder"],correct:1,explanation:"PFS uses ephemeral Diffie-Hellman key exchange to generate unique session keys. If a long-term private key is later compromised, past sessions encrypted with ephemeral keys cannot be decrypted by the attacker."},
{id:30023,domain:3,level:2,question:"What is a Certificate Authority (CA) in a Public Key Infrastructure (PKI)?",options:["A. An auditing body that certifies information security professionals","B. A trusted entity that issues and manages digital certificates binding public keys to identities","C. A hardware device that stores and protects private keys","D. A protocol for securely exchanging public keys between parties"],correct:1,explanation:"A CA is a trusted third party that issues digital certificates binding a public key to an identity. Browsers and operating systems contain trusted root CAs, enabling TLS, digital signatures, and secure authentication."},
{id:30024,domain:3,level:2,question:"What is the 'trusted computing base' (TCB)?",options:["A. All trusted hardware components located in a secure data center","B. The set of hardware, firmware, and software components critical to enforcing a system's security policy","C. The list of trusted third-party vendors and cloud service providers","D. The cryptographic foundation layer of a secure computing system"],correct:1,explanation:"The TCB is everything that must be trusted for the system to enforce its security policy. It should be minimized (smaller attack surface) and verifiable. Compromise of the TCB means security policy cannot be enforced."},
{id:30025,domain:3,level:3,question:"'Defense in depth' is BEST described as:",options:["A. Concentrating all security investment at the network perimeter for maximum effectiveness","B. Implementing multiple, overlapping, independent layers of security so no single failure compromises security","C. Increasing the mathematical depth of cryptographic algorithms used","D. Deploying security controls deep within the operating system kernel"],correct:1,explanation:"Defense in depth layers controls across physical, network, host, application, and data tiers. If an attacker bypasses one layer, others remain. No single control is assumed infallible — redundancy provides resilience."},
{id:30026,domain:3,level:3,question:"In cloud security, a 'secure enclave' (e.g., Intel SGX) provides:",options:["A. Physical isolation of cloud servers from external networks","B. Hardware-based trusted execution environment protecting code and data from the OS and hypervisor","C. Network-level isolation between cloud tenants on shared infrastructure","D. A physically secure room in the data center for hardware storage and maintenance"],correct:1,explanation:"Secure enclaves provide hardware-isolated execution environments where code and data are protected even from the host OS, hypervisor, and cloud provider. This enables confidential computing in shared cloud environments."},
{id:30027,domain:3,level:3,question:"What does 'complete mediation' mean as a security design principle?",options:["A. All security disputes between users and systems are resolved by a neutral third party","B. Every access to every object must be checked against the access control policy — no caching or bypassing","C. All network traffic must pass through a central mediation point for inspection","D. Security controls must be independently validated by a third-party auditor"],correct:1,explanation:"Complete mediation means every access request must be validated against current access policy — not cached from previous decisions. It prevents access control bypasses due to permission changes not being enforced on subsequent requests."},
{id:30028,domain:3,level:3,question:"The Clark-Wilson integrity model is primarily used in:",options:["A. Military classification systems requiring Bell-LaPadula confidentiality controls","B. Commercial environments enforcing transaction integrity through well-formed transactions and separation of duties","C. Healthcare systems requiring HIPAA data protection compliance","D. Cloud environments requiring multi-tenant data isolation"],correct:1,explanation:"Clark-Wilson addresses commercial integrity: transactions must be well-formed (follow correct business procedures), and separation of duties prevents unauthorized modifications. It is used in banking, accounting, and commercial transaction systems."},

// ─── DOMAIN 4: Communication and Network Security ─────────────────────────────
{id:30029,domain:4,level:1,question:"At which OSI layer does IPSec operate?",options:["A. Layer 2 — Data Link","B. Layer 3 — Network","C. Layer 4 — Transport","D. Layer 7 — Application"],correct:1,explanation:"IPSec operates at the Network layer (Layer 3), protecting IP packets. Tunnel mode protects entire IP packets for VPNs. Transport mode protects only the payload between hosts. Both provide encryption and authentication."},
{id:30030,domain:4,level:1,question:"TLS (Transport Layer Security) protects against:",options:["A. Only passive eavesdropping attacks on network traffic","B. Eavesdropping, tampering, and impersonation (man-in-the-middle) attacks","C. Only server identity spoofing attacks","D. Denial of service and flood attacks on web servers"],correct:1,explanation:"TLS provides confidentiality (encryption), integrity (MAC), and authentication (certificates). It defends against passive eavesdropping, active MITM, and session replay attacks."},
{id:30031,domain:4,level:1,question:"A 'DMZ' in network architecture is:",options:["A. A network segment for development and testing systems","B. A semi-trusted network segment hosting public-facing servers, separated from internal networks","C. A wireless guest network segment isolated from corporate systems","D. A redundant network path between primary and secondary data centers"],correct:1,explanation:"A DMZ (Demilitarized Zone) hosts public-facing services (web, email, DNS) between the internet and internal network. External users reach DMZ servers without gaining direct access to internal systems."},
{id:30032,domain:4,level:2,question:"A 'stateful firewall' differs from a packet-filter firewall in that it:",options:["A. Inspects application-layer content including HTTP and SMTP payloads","B. Tracks the state of network connections and allows only packets matching established sessions","C. Uses geographic IP blocking to filter traffic from high-risk countries","D. Employs machine learning to detect previously unknown attack patterns"],correct:1,explanation:"A stateful firewall maintains a connection state table and allows only packets that match an established, legitimate session. This is more effective than packet filtering, which evaluates each packet independently."},
{id:30033,domain:4,level:2,question:"Which wireless security protocol is MOST secure?",options:["A. WEP (Wired Equivalent Privacy) — original 802.11 security","B. WPA (Wi-Fi Protected Access) — first generation replacement","C. WPA2 with TKIP — Wi-Fi Protected Access 2","D. WPA3 with SAE (Simultaneous Authentication of Equals)"],correct:3,explanation:"WPA3 with SAE provides the strongest security: protection against offline dictionary attacks, forward secrecy, and 192-bit encryption in WPA3-Enterprise mode. WEP is completely broken; WPA2-TKIP has known weaknesses."},
{id:30034,domain:4,level:2,question:"What is the PRIMARY security advantage of using VLANs (Virtual LANs)?",options:["A. VLANs improve overall network throughput and reduce latency","B. VLANs logically segment networks to limit broadcast domains and control traffic between segments","C. VLANs automatically encrypt traffic between network segments","D. VLANs simplify network administration by centralizing management"],correct:1,explanation:"VLANs provide logical network segmentation without physical separation. Traffic between VLANs must pass through a router or firewall where security policies can be enforced. This limits lateral movement after compromise."},
{id:30035,domain:4,level:2,question:"Which protocol should ALWAYS replace Telnet for secure remote administration?",options:["A. FTP (File Transfer Protocol)","B. HTTP (Hypertext Transfer Protocol)","C. SSH (Secure Shell)","D. SNMP v1 (Simple Network Management Protocol)"],correct:2,explanation:"Telnet transmits all data including credentials in plaintext. SSH provides encrypted, authenticated remote access and must replace Telnet on all managed devices. Telnet should be disabled by default."},
{id:30036,domain:4,level:3,question:"A 'man-in-the-middle' (MITM) attack is BEST described as:",options:["A. An attacker overwhelming a server with connection requests","B. An attacker secretly intercepting and potentially altering communications between two parties","C. An attacker exploiting a buffer overflow vulnerability to gain privileged access","D. An attacker using social engineering to obtain a user's credentials"],correct:1,explanation:"In a MITM attack, the attacker positions themselves between communicating parties, intercepting and potentially altering messages. TLS with proper certificate validation and certificate pinning defend against MITM attacks."},
{id:30037,domain:4,level:3,question:"What does 'DNS poisoning' (cache poisoning) accomplish?",options:["A. A DoS attack that overwhelms DNS servers with recursive queries","B. Injecting false DNS records into a resolver's cache to redirect users to attacker-controlled sites","C. Monitoring DNS queries to profile user browsing behavior","D. Encrypting DNS queries to protect user privacy from eavesdroppers"],correct:1,explanation:"DNS poisoning injects malicious entries into a DNS resolver's cache. Users requesting a legitimate domain receive a fraudulent IP address and are redirected to attacker sites for phishing or malware delivery. DNSSEC prevents this."},
{id:30038,domain:4,level:3,question:"'Network access control' (NAC) primarily provides:",options:["A. Bandwidth throttling and quality of service for network traffic","B. Pre-admission verification of device compliance before granting network access","C. Encryption of all traffic between network segments","D. Centralized logging of all network connections and traffic flows"],correct:1,explanation:"NAC enforces security policy on devices before granting network access: checking OS patching level, AV status, configuration compliance, and identity. Non-compliant devices are quarantined or given limited access."},

// ─── DOMAIN 5: Identity and Access Management (IAM) ──────────────────────────
{id:30039,domain:5,level:1,question:"Multi-factor authentication (MFA) requires:",options:["A. Using two different passwords for the same account","B. Authentication using two or more factors from different categories","C. Two separate login steps for every system accessed","D. Approval by two different administrators for privileged access"],correct:1,explanation:"MFA requires factors from at least two categories: something you know (password, PIN), something you have (token, smart card, authenticator app), something you are (biometric). Two factors from the same category do not qualify as MFA."},
{id:30040,domain:5,level:1,question:"What is federated identity management?",options:["A. Sharing user credentials across multiple internal systems within one organization","B. A system where a user's identity from one organization is trusted and accepted by another organization","C. A centralized credential database storing all user passwords for an enterprise","D. Government-issued digital identity certificates for authentication"],correct:1,explanation:"Federated identity (using SAML, OAuth 2.0, OpenID Connect) allows a user's identity established by an Identity Provider (IdP) to be trusted by Service Providers in other domains, enabling cross-organizational SSO."},
{id:30041,domain:5,level:1,question:"The 'principle of least privilege' means:",options:["A. Granting users only the minimum access rights required for their assigned job function","B. Restricting all system access to security administrators only","C. Using the simplest authentication method to reduce management complexity","D. Minimizing the number of administrators managing critical systems"],correct:0,explanation:"Least privilege limits user access to only what is necessary for their specific duties. This reduces the blast radius of compromised accounts, limits insider threat damage, and supports auditable access control."},
{id:30042,domain:5,level:2,question:"What is Single Sign-On (SSO)?",options:["A. Using one password for all systems in the organization","B. Authenticating once to an Identity Provider and accessing multiple systems without re-authentication","C. A backup authentication mechanism when primary authentication fails","D. An automated password reset system for forgotten credentials"],correct:1,explanation:"SSO authenticates users once at the Identity Provider and creates a session token accepted by multiple Service Providers. It reduces password fatigue and centralizes authentication for better security management."},
{id:30043,domain:5,level:2,question:"In Role-Based Access Control (RBAC), access to resources is determined by:",options:["A. The user's department, seniority, and management approval history","B. Individually assigned permissions directly attached to each user account","C. The classification level of the resource relative to the user's clearance","D. The roles assigned to the user, where roles define permitted operations on resources"],correct:3,explanation:"RBAC assigns users to roles (e.g., 'Finance Analyst,' 'System Administrator') and roles define what actions are permitted. Role management is far more scalable than individual permission management at enterprise scale."},
{id:30044,domain:5,level:2,question:"What is 'just-in-time' (JIT) privileged access?",options:["A. Permanently granting privileged access at the time of a user's request","B. Providing temporary, time-limited privileged access when needed and automatically revoking it after use","C. Requiring MFA at the exact moment of accessing privileged resources","D. Ordering hardware tokens just before privileged access is provisioned"],correct:1,explanation:"JIT access (implemented by PAM solutions) grants elevated privileges only for the duration of a specific task, then automatically revokes them. This dramatically reduces the standing privilege attack surface."},
{id:30045,domain:5,level:2,question:"A user transfers to a new department with different access requirements. What control is REQUIRED?",options:["A. Grant additional access to support both the old and new roles temporarily","B. Perform access review and remove access no longer required, then grant new role-appropriate access","C. Wait for the annual access recertification cycle to update the user's access rights","D. Allow the user to retain old access for 90 days during transition"],correct:1,explanation:"When users change roles, old access must be promptly revoked and only new role-appropriate access granted. Delayed revocation leads to 'access creep' (accumulated privileges), violating least privilege."},
{id:30046,domain:5,level:3,question:"What is a 'Privileged Access Workstation' (PAW)?",options:["A. A high-performance workstation assigned to system administrators","B. A hardened, dedicated workstation used exclusively for privileged administrative tasks","C. A shared IT department workstation with elevated hardware specifications","D. Any workstation that connects to privileged network segments"],correct:1,explanation:"A PAW is a dedicated, hardened device used only for privileged tasks (domain admin, firewall management). It eliminates risky activities (email, web browsing) from privileged sessions, reducing the attack surface dramatically."},
{id:30047,domain:5,level:3,question:"Biometric authentication is classified as which authentication factor?",options:["A. Something you know — a memorized secret","B. Something you have — a physical possession","C. Something you are — an inherent characteristic","D. Something you do — a behavioral pattern"],correct:2,explanation:"Biometrics (fingerprint, iris scan, facial recognition, voice print) are 'something you are' — inherence factors. They cannot be forgotten but raise privacy concerns and cannot be changed if compromised."},
{id:30048,domain:5,level:3,question:"What is the PRIMARY risk of 'privilege creep' in an enterprise IAM environment?",options:["A. Increased helpdesk workload from complex access request processes","B. Users accumulating more access than needed, increasing breach impact and insider threat risk","C. System performance degradation from overly complex access control policies","D. Difficulty in conducting timely access recertification reviews"],correct:1,explanation:"Privilege creep occurs when users gradually accumulate access rights over time without timely revocation of old access. Excessive rights increase the damage potential if an account is compromised or misused."},

// ─── DOMAIN 6: Security Assessment and Testing ────────────────────────────────
{id:30049,domain:6,level:1,question:"The key difference between a vulnerability assessment and a penetration test is:",options:["A. They are the same activity described at different levels of depth","B. Vulnerability assessment identifies weaknesses; penetration test exploits them to demonstrate actual impact","C. Vulnerability assessment is performed externally; penetration test is internal only","D. Penetration test is fully automated; vulnerability assessment is manual"],correct:1,explanation:"Vulnerability scanning/assessment catalogs weaknesses. Penetration testing actively exploits vulnerabilities to demonstrate realistic impact and attack paths. Pen tests provide more actionable risk information."},
{id:30050,domain:6,level:1,question:"A 'black box' penetration test means:",options:["A. Testing only internal systems with no external network connectivity","B. The tester has no prior knowledge of the target environment (simulates an external attacker)","C. The test uses only automated scanning tools without manual analysis","D. The test targets only the database and storage layers"],correct:1,explanation:"Black box simulates an external attacker: the tester has no insider knowledge. White box provides full system access and knowledge. Gray box provides partial knowledge. Each models different attack scenarios."},
{id:30051,domain:6,level:2,question:"What is 'Static Application Security Testing' (SAST)?",options:["A. Testing application security by simulating attacks against the running application","B. Analyzing application source code or binaries for vulnerabilities without executing the code","C. Monitoring application security behavior in production environments","D. Testing application security in a static (non-production) test environment"],correct:1,explanation:"SAST (white-box testing) analyzes source code or compiled binaries without execution, identifying vulnerabilities like injection flaws, buffer overflows, and hardcoded credentials early in the SDLC."},
{id:30052,domain:6,level:2,question:"What does a Security Operations Center (SOC) primarily do?",options:["A. Develops and tests security software and tools for the organization","B. Monitors, detects, analyzes, and responds to security events in real time","C. Manages user access rights and identity lifecycle processes","D. Conducts annual security compliance audits and assessments"],correct:1,explanation:"A SOC provides 24/7 monitoring of security events (via SIEM, EDR, network monitoring), triages alerts, investigates incidents, and coordinates response. It is the organization's hub for security operations."},
{id:30053,domain:6,level:2,question:"A 'red team' exercise is BEST described as:",options:["A. A team that monitors security alerts and responds to incidents in the SOC","B. An authorized simulation of adversarial attack techniques to test organizational detection and response","C. A group that formally reviews and assesses security policies and procedures","D. A team that conducts recurring automated vulnerability scans of the environment"],correct:1,explanation:"Red teams simulate advanced persistent threats using realistic attack techniques (social engineering, physical intrusion, zero-day exploitation) to test whether the organization's defenses (blue team) can detect and respond effectively."},
{id:30054,domain:6,level:3,question:"'Dynamic Application Security Testing' (DAST) differs from SAST in that:",options:["A. DAST tests only production applications; SAST tests only development code","B. DAST tests running applications by sending inputs and observing responses; SAST analyzes static code","C. DAST is performed by developers; SAST is performed by security teams","D. DAST uses machine learning models; SAST uses traditional rule-based analysis"],correct:1,explanation:"DAST (black-box testing) tests the running application by submitting inputs and analyzing responses. It finds runtime vulnerabilities (authentication bypasses, injection flaws) invisible in static code analysis."},
{id:30055,domain:6,level:3,question:"What is a 'bug bounty program'?",options:["A. An internal reward program for IT staff who identify and fix software defects","B. A program rewarding external security researchers who responsibly disclose discovered vulnerabilities","C. An internal quality assurance testing methodology for development teams","D. A government incentive program for critical infrastructure vulnerability disclosure"],correct:1,explanation:"Bug bounty programs invite external security researchers to find and responsibly disclose vulnerabilities, offering rewards for valid findings. They leverage the broader security community to find vulnerabilities internal teams miss."},
{id:30056,domain:6,level:3,question:"What is the PRIMARY benefit of continuous security monitoring over periodic assessments?",options:["A. Continuous monitoring is significantly less expensive than annual assessments","B. It detects configuration changes, new vulnerabilities, and threats in near real-time rather than point-in-time","C. Continuous monitoring eliminates the need for manual security review and testing","D. It satisfies all regulatory requirements for security assessment documentation"],correct:1,explanation:"Continuous monitoring detects security posture changes (new vulnerabilities, configuration drift, anomalous behavior) as they occur. Point-in-time assessments may miss changes occurring between assessment cycles."},

// ─── DOMAIN 7: Security Operations ───────────────────────────────────────────
{id:30057,domain:7,level:1,question:"The FIRST action upon discovering a potentially compromised system should be:",options:["A. Format and reinstall the operating system to eliminate the threat","B. Isolate the system from the network while preserving volatile evidence and notifying the IR team","C. Run antivirus software immediately to identify and remove all malware","D. Shut down the system completely to stop all malicious activity"],correct:1,explanation:"Containment while preserving evidence is critical. Hasty remediation destroys volatile evidence (RAM contents, active connections). Proper sequence: isolate, preserve evidence, then escalate and investigate."},
{id:30058,domain:7,level:1,question:"What is 'digital forensics'?",options:["A. Digital analysis of organizational security policies and procedures","B. The collection, preservation, analysis, and presentation of digital evidence in a legally sound manner","C. Automated malware scanning and removal on digital systems","D. Digital monitoring of employee activity for human resources investigations"],correct:1,explanation:"Digital forensics applies scientific methods to recover and analyze digital evidence. Chain of custody, evidence integrity (hash verification), and documented procedures ensure evidence is admissible in legal proceedings."},
{id:30059,domain:7,level:2,question:"A SIEM system primarily provides:",options:["A. Firewall, IPS, and network access control capabilities","B. Real-time aggregation, correlation, and alerting on security events from multiple sources","C. Endpoint detection and response capabilities for workstations","D. Identity provisioning and access management services"],correct:1,explanation:"SIEM (Security Information and Event Management) collects logs from across the environment, correlates events to identify threat patterns, generates alerts for SOC analysts, and supports incident investigation."},
{id:30060,domain:7,level:2,question:"'Data Loss Prevention' (DLP) technology is PRIMARILY designed to:",options:["A. Prevent sensitive data from being corrupted or modified by malware","B. Detect and prevent unauthorized transmission of sensitive data outside the organization","C. Encrypt sensitive data at rest and in transit automatically","D. Back up sensitive data to prevent accidental deletion or loss"],correct:1,explanation:"DLP monitors and controls data movement across channels (email, web upload, USB, cloud) to prevent sensitive data (PII, IP, financial data) from leaving the organization without authorization, enforcing data handling policies."},
{id:30061,domain:7,level:2,question:"Which type of malware maintains hidden, persistent privileged access to a compromised system?",options:["A. Ransomware — encrypts data and demands payment for decryption","B. Rootkit — modifies OS to hide presence and maintain persistent privileged access","C. Keylogger — records keystrokes to capture credentials and sensitive input","D. Adware — displays unwanted advertisements to generate revenue"],correct:1,explanation:"A rootkit modifies the OS, bootloader, or firmware to hide the attacker's presence while maintaining persistent privileged access. Rootkits subvert security tools by hiding malicious processes, files, and connections."},
{id:30062,domain:7,level:2,question:"What is the PRIMARY purpose of 'patch management'?",options:["A. Upgrading hardware infrastructure to improve system performance","B. Maintaining an inventory of all software versions across the environment","C. Timely testing and deploying security updates to remediate known vulnerabilities","D. Managing software license compliance and renewal schedules"],correct:2,explanation:"Patch management reduces vulnerability exposure by ensuring systems receive security updates promptly. Key steps: inventory, assess patch criticality, test in non-production, deploy to production, verify, and document."},
{id:30063,domain:7,level:3,question:"What is 'configuration management' in security operations?",options:["A. Managing and rotating passwords and credentials for all system accounts","B. Establishing and maintaining documented, secure baseline configurations for all systems","C. Tracking and approving proposed changes to IT systems and services","D. Maintaining an inventory of all software licenses and hardware assets"],correct:1,explanation:"Configuration management establishes hardened secure baselines, tracks deviations from those baselines, and returns systems to known secure states. Tools like CIS Benchmarks and SCAP automate compliance verification."},
{id:30064,domain:7,level:3,question:"The PRIMARY benefit of deploying 'honeypots' in a security operations program is:",options:["A. They actively block malicious traffic before it reaches production systems","B. They attract attackers, provide early detection, and gather threat intelligence while protecting real assets","C. They provide encrypted alternate communication channels during security incidents","D. They replace traditional security monitoring with more realistic threat detection"],correct:1,explanation:"Honeypots deceive attackers with fake, instrumented resources. Any interaction signals a real threat (early detection). They gather intelligence on attacker TTPs and waste attacker time on decoys rather than real targets."},
{id:30065,domain:7,level:3,question:"In a zero-trust security operations model, access decisions must be based on:",options:["A. The network segment from which the request originates (internal vs. external)","B. Identity verification, device health assessment, contextual risk, and least privilege — never implicit trust","C. The time of day and geographic location of the access request","D. Historical access patterns and behavioral analytics alone"],correct:1,explanation:"Zero trust principle: 'never trust, always verify.' Every request must be authenticated, authorized against policy, and the device assessed for compliance, regardless of network location. No implicit trust is granted."},
{id:30066,domain:7,level:3,question:"Which incident response phase involves analyzing root cause and documenting recommendations to prevent recurrence?",options:["A. Preparation — developing IR plans and team capabilities before incidents occur","B. Containment — stopping the incident from spreading further","C. Eradication — removing the threat from the environment","D. Post-incident activity — lessons learned, root cause analysis, and process improvement"],correct:3,explanation:"Post-incident activity (NIST SP 800-61) focuses on: what happened, root cause analysis, what was done well, what needs improvement, and updating plans and controls to prevent recurrence. It drives continuous IR improvement."},

// ─── DOMAIN 8: Software Development Security ──────────────────────────────────
{id:30067,domain:8,level:1,question:"The MOST cost-effective time to address security in the software development lifecycle is:",options:["A. During user acceptance testing before production deployment","B. During the production deployment and monitoring phase","C. During the requirements and design phase (shift left)","D. After the first security incident is discovered in production"],correct:2,explanation:"'Shift left': fixing security in requirements/design is the cheapest (10x cheaper than in development, 100x cheaper than in production). Security by design is far more effective and economical than reactive security."},
{id:30068,domain:8,level:1,question:"SQL injection is classified under which OWASP Top 10 category?",options:["A. Broken Authentication","B. Injection","C. Security Misconfiguration","D. Sensitive Data Exposure"],correct:1,explanation:"SQL injection is the prototypical injection attack — malicious SQL code in user input is executed by the database engine. Parameterized queries/prepared statements are the primary defense. Injection consistently ranks in OWASP Top 10."},
{id:30069,domain:8,level:2,question:"What is 'input validation' and why is it a critical security control?",options:["A. Verifying that user passwords meet defined complexity requirements","B. Verifying all user-supplied input conforms to expected type, format, and range before processing","C. Validating digital signatures on software before installation","D. Ensuring required input fields are not submitted empty"],correct:1,explanation:"Input validation prevents injection attacks (SQL, XSS, command injection, LDAP injection) by rejecting malformed or malicious input. Server-side validation is mandatory; client-side validation alone is bypassed easily."},
{id:30070,domain:8,level:2,question:"What is 'DevSecOps'?",options:["A. A dedicated security operations center embedded within development organizations","B. Integrating security practices, tools, and mindset throughout the DevOps CI/CD pipeline","C. A team of security engineers assigned as full-time members of development squads","D. A security audit methodology specifically designed for DevOps environments"],correct:1,explanation:"DevSecOps embeds security into every CI/CD phase: security requirements in planning, SAST/DAST/SCA in the pipeline, container scanning, secrets detection, and IaC security scanning. Security becomes 'code' — automated and continuous."},
{id:30071,domain:8,level:2,question:"Cross-site scripting (XSS) attacks target:",options:["A. Database servers directly through network connections","B. Network infrastructure between the client browser and web server","C. End users' browsers by injecting malicious scripts into web pages","D. Authentication systems to bypass the login mechanism"],correct:2,explanation:"XSS injects malicious scripts into web pages viewed by other users. The browser executes scripts in the context of the trusted site, enabling session theft, credential harvesting, and malicious redirects. Output encoding is the primary defense."},
{id:30072,domain:8,level:3,question:"The security principle of 'fail-safe defaults' means:",options:["A. Systems should fail to a fully operational state to maintain business availability","B. Security mechanisms default to deny access when they fail, rather than defaulting to permit","C. Application code should automatically create backups when processing failures occur","D. Error handling should hide detailed error messages from end users"],correct:1,explanation:"Fail-safe defaults: when a control or system fails, the default state must be secure (deny access). 'Fail open' (granting access on failure) creates critical vulnerabilities. All authentication and authorization systems must fail closed."},
{id:30073,domain:8,level:3,question:"What is the PRIMARY purpose of a 'software bill of materials' (SBOM)?",options:["A. To document the financial cost of all software components used in an application","B. To provide a comprehensive inventory of all components and dependencies in software for vulnerability and supply chain risk management","C. To list all software licenses in use to ensure compliance","D. To document the testing coverage achieved during security testing"],correct:1,explanation:"An SBOM (like SPDX, CycloneDX) is a formal inventory of all software components, libraries, and dependencies. It enables rapid identification of vulnerable components (e.g., Log4j) and supports software supply chain security risk management."},
{id:30074,domain:8,level:3,question:"What distinguishes 'security regression testing' from standard functional regression testing?",options:["A. Security regression testing uses different tools than functional testing","B. Security regression testing specifically verifies that new changes haven't introduced vulnerabilities or broken security controls","C. Security regression testing is performed only after major version releases","D. Security regression testing is performed by a different team than functional testing"],correct:1,explanation:"Security regression testing verifies that code changes haven't introduced new security vulnerabilities or removed existing security controls. It runs as part of the CI/CD pipeline to maintain security posture as code evolves."}
];

const DOMAIN_NAMES_CISSP = {
  1: "Security & Risk Management",
  2: "Asset Security",
  3: "Security Architecture & Engineering",
  4: "Communication & Network Security",
  5: "Identity & Access Management",
  6: "Security Assessment & Testing",
  7: "Security Operations",
  8: "Software Development Security"
};
