const QUESTIONS_CCZT = [
  { id:60001, domain:1, level:1, question:"Which principle is the foundational tenet of Zero Trust?", options:["Trust is granted permanently once a device joins the corporate network perimeter","Trust is assigned based on the seniority of the requesting user account","Internal network traffic is inherently trustworthy and exempt from inspection","Never trust, always verify — no implicit trust is granted based on network location"], correct:3, explanation:"Zero Trust rejects implicit trust based on network position; every access request is authenticated, authorized, and continuously validated regardless of where it originates." },
  { id:60002, domain:1, level:1, question:"In Zero Trust terminology, what does the 'implicit trust zone' refer to?", options:["The area behind a policy enforcement point where requests are trusted after a single check","The encrypted tunnel established between two authenticated endpoints during a session","A regulatory boundary defining which jurisdictions may process sensitive data","The set of cloud regions a provider guarantees within its availability commitments"], correct:0, explanation:"An implicit trust zone is the region beyond a policy enforcement point where traffic is no longer individually validated; Zero Trust aims to shrink these zones to the smallest practical size." },
  { id:60003, domain:1, level:2, question:"How does Zero Trust fundamentally differ from traditional perimeter-based security?", options:["It relies on stronger firewalls positioned at a hardened and well-monitored network edge","It shifts the control focus from network location to identity, device, and continuous context","It encrypts all internal traffic so the perimeter firewall no longer needs to inspect packets","It consolidates all security controls into a single appliance at the data center boundary"], correct:1, explanation:"Traditional models trust everything inside the perimeter; Zero Trust removes location-based trust and makes access decisions on identity, device posture, and real-time context for every request." },
  { id:60004, domain:1, level:2, question:"What is the security benefit of reducing implicit trust zones in a Zero Trust design?", options:["It increases raw network throughput by removing inspection overhead between internal hosts","It eliminates the need for endpoint protection because the network itself becomes trusted","It limits lateral movement by forcing more access requests through policy enforcement points","It allows administrators to share a single privileged account across the operations team"], correct:2, explanation:"Smaller trust zones mean more decisions are individually evaluated, constraining an attacker's ability to move laterally after compromising one asset." },
  { id:60005, domain:1, level:1, question:"Which of the following is a core Zero Trust assumption about the network?", options:["The external network is the only place from which threats can realistically originate","The internal network is fully controlled and therefore safe from compromise","The internal network is a hostile environment that may already contain attackers","The network can be secured permanently once segmentation has been deployed once"], correct:2, explanation:"Zero Trust assumes the network is always potentially compromised ('assume breach'), so no traffic is trusted simply for being internal." },
  { id:60006, domain:2, level:1, question:"Which NIST publication defines the formal Zero Trust Architecture reference model?", options:["NIST SP 800-53, the catalog of security and privacy controls for federal systems","NIST SP 800-207, which establishes Zero Trust Architecture concepts and components","NIST SP 800-171, covering protection of controlled unclassified information","NIST Cybersecurity Framework, which organizes outcomes into five core functions"], correct:1, explanation:"NIST SP 800-207 is the authoritative reference defining Zero Trust Architecture, its logical components, and deployment approaches." },
  { id:60007, domain:2, level:2, question:"In the NIST SP 800-207 model, what are the two logical halves of the policy decision engine?", options:["The policy engine and the policy administrator, together forming the policy decision point","The policy enforcement point and the policy information point working in tandem","The control plane gateway and the data plane proxy that filters all session traffic","The identity provider and the device management system that share authentication state"], correct:0, explanation:"The Policy Decision Point comprises the Policy Engine (makes the access decision) and the Policy Administrator (establishes or terminates the session), working with the Policy Enforcement Point." },
  { id:60008, domain:2, level:2, question:"What is the role of the Policy Enforcement Point (PEP) in a Zero Trust Architecture?", options:["It stores the authoritative policy rules that all access decisions are evaluated against","It enables, monitors, and terminates connections between a subject and an enterprise resource","It generates the cryptographic keys used to encrypt every session across the enterprise","It maintains the historical log archive used by auditors during compliance reviews"], correct:1, explanation:"The PEP is responsible for enabling, monitoring, and eventually terminating the connection between subject and resource, acting on decisions made by the policy decision point." },
  { id:60009, domain:2, level:2, question:"According to NIST SP 800-207, which inputs feed the policy engine's trust algorithm?", options:["Only the user's password strength and the time elapsed since their last login event","Exclusively the source IP address and the destination port of the requested connection","Identity, device health, asset state, behavioral analytics, and threat intelligence signals","The organizational chart and the requesting employee's documented job title alone"], correct:2, explanation:"The trust algorithm weighs many inputs — subject identity, device posture, resource sensitivity, behavioral patterns, and threat intelligence — to reach a per-request access decision." },
  { id:60010, domain:2, level:3, question:"An organization wants its Zero Trust deployment to evaluate not just who is requesting access but whether the requesting device is patched and free of malware. Which NIST SP 800-207 component most directly supplies this input?", options:["The data access policy repository that lists which roles may reach which resources","The enterprise certificate authority that issues identity credentials to authorized users","The continuous diagnostics and mitigation (CDM) system reporting device posture to the policy engine","The network segmentation gateway that isolates production from development traffic"], correct:2, explanation:"The CDM system supplies real-time asset and device health information to the policy engine, enabling posture-aware access decisions — a key 800-207 data source." },
  { id:60011, domain:3, level:1, question:"What problem does a Software-Defined Perimeter (SDP) primarily address?", options:["It hides infrastructure from unauthorized users by making resources invisible until authenticated","It reduces cloud storage costs by compressing data before it leaves the enterprise","It accelerates application performance by caching content closer to end users","It replaces the need for any identity provider by trusting validated device certificates"], correct:0, explanation:"SDP conceals network resources so they are 'dark' to unauthorized parties; only after a user and device are authenticated and authorized is a connection allowed, dramatically reducing the attack surface." },
  { id:60012, domain:3, level:2, question:"In the SDP architecture, what is the function of the SDP controller?", options:["It forwards application data packets between the client and the protected backend host","It performs deep packet inspection on outbound traffic to detect data exfiltration","It stores the encrypted backups of all protected resources for disaster recovery","It authenticates clients, evaluates policy, and instructs gateways which connections to accept"], correct:3, explanation:"The SDP controller is the brain: it authenticates and authorizes hosts, evaluates policy, and tells the accepting hosts (gateways) which connections to permit — it does not carry the data itself." },
  { id:60013, domain:3, level:2, question:"What is 'Single Packet Authorization' (SPA) in the context of SDP?", options:["A method of compressing authorization tokens into one packet to save network bandwidth","A single sign-on protocol that authorizes a user across all applications in one request","A lightweight pre-authentication packet that lets a service stay hidden until a valid client proves itself","A packet-loss recovery technique used to keep SDP sessions alive over unreliable or congested network links"], correct:2, explanation:"SPA requires a client to send a cryptographically valid packet before any service port responds, keeping the service invisible to port scanners and unauthorized clients (default-drop)." },
  { id:60014, domain:3, level:2, question:"How does SDP implement the Zero Trust principle of 'least privilege' for network access?", options:["It grants each authenticated user a broad VPN tunnel into the entire corporate subnet","It creates dynamic, one-to-one encrypted connections only to the specific resources a user is authorized for","It assigns every device a static IP address that is permanently allowed through the firewall","It relies on network admins to manually approve each connection request as it arrives"], correct:1, explanation:"SDP builds per-session, individualized connections to only the resources the subject is entitled to access, rather than exposing a broad network segment." },
  { id:60015, domain:3, level:3, question:"A company replaces its traditional VPN with an SDP solution. Which security improvement is the MOST significant result of this change?", options:["Users no longer need to authenticate because the SDP gateway trusts the device certificate","The organization can eliminate its identity provider since SDP handles all authorization","All internal traffic is automatically exempted from inspection to improve connection speed","Internet-facing services become unreachable to unauthenticated scanners, shrinking the attack surface"], correct:3, explanation:"Unlike a VPN that exposes a network entry point, SDP makes resources invisible until authentication and authorization succeed, removing the externally reachable attack surface that VPN concentrators present." },
  { id:60016, domain:4, level:1, question:"What is typically the recommended FIRST step when planning a Zero Trust initiative?", options:["Identify and inventory the protect surface — critical data, assets, applications, and services","Purchase a comprehensive Zero Trust platform from a single vendor before any analysis","Immediately decommission all existing VPNs and firewalls across the enterprise","Grant every employee administrative access so migration is not blocked by permissions"], correct:0, explanation:"Zero Trust planning begins by defining the 'protect surface' — the critical data, assets, applications, and services (DAAS) — because controls are built around what matters most, not the entire network." },
  { id:60017, domain:4, level:2, question:"Why is mapping transaction flows important during Zero Trust planning?", options:["It documents how traffic moves between resources so policies can be placed accurately","It calculates the total network bandwidth required to support future business growth","It identifies which employees deserve promotions based on their system usage volume","It determines the depreciation schedule for aging network hardware assets"], correct:0, explanation:"Understanding how data and requests actually flow between users, applications, and services is essential to placing policy enforcement points correctly and defining effective microsegmentation." },
  { id:60018, domain:4, level:2, question:"Which organizational factor is MOST critical to the success of a Zero Trust program?", options:["Complete replacement of the workforce with security-certified personnel","A single firewall vendor standardized across every office location worldwide","The largest possible security budget allocated entirely to new tooling purchases","Executive sponsorship and a clear governance model with defined accountability"], correct:3, explanation:"Zero Trust is a strategic, cross-functional transformation; without executive sponsorship and governance defining accountability, technical efforts stall and fragment." },
  { id:60019, domain:4, level:3, question:"An organization has limited resources and cannot apply Zero Trust everywhere at once. What is the MOST appropriate strategy?", options:["Apply Zero Trust uniformly and thinly across all systems to show broad early coverage","Focus exclusively on perimeter firewalls since they protect the most users at once","Wait until the budget allows a complete enterprise-wide rollout before starting anything","Prioritize the highest-value protect surfaces first and expand iteratively from proven wins"], correct:3, explanation:"Zero Trust is best adopted incrementally — securing the most critical protect surfaces first, demonstrating value, and expanding maturity over time rather than attempting everything simultaneously." },
  { id:60020, domain:4, level:2, question:"How should a Zero Trust strategy treat existing legacy systems that cannot support modern authentication?", options:["Wrap them with compensating controls such as proxies, microsegmentation, and enhanced monitoring","Exclude them permanently from the program since they cannot be modernized at all","Immediately disconnect them from the network regardless of business impact","Grant them blanket trust so they continue operating without any added friction"], correct:0, explanation:"Legacy systems that cannot natively enforce Zero Trust are protected by surrounding them with compensating controls — gateways, segmentation, and monitoring — while migration is planned." },
  { id:60021, domain:5, level:1, question:"What is microsegmentation in a Zero Trust implementation?", options:["Dividing the network into fine-grained zones so policy controls traffic between individual workloads","Splitting large files into smaller encrypted segments before transmitting them across the WAN","Separating the security team into specialized micro-teams for each technology domain","Breaking long user sessions into short segments to force frequent re-authentication"], correct:0, explanation:"Microsegmentation creates granular boundaries — often down to individual workloads — so east-west traffic must pass policy checks, sharply limiting lateral movement." },
  { id:60022, domain:5, level:2, question:"Which capability is essential for enforcing continuous authentication in a Zero Trust deployment?", options:["A one-time login at the start of each day that grants access until the user logs out","Ongoing evaluation of session risk signals, re-validating trust as context changes","A shared service account that all applications use to avoid repeated login prompts","A static allow-list of IP addresses that are permanently trusted once registered"], correct:1, explanation:"Zero Trust treats trust as dynamic; sessions are continuously evaluated against changing risk signals (device posture, location, behavior), prompting re-authentication or termination when risk rises." },
  { id:60023, domain:5, level:2, question:"What role does strong identity and access management (IAM) play in Zero Trust implementation?", options:["It is optional once the network has been fully segmented into secure zones","It replaces the need for device posture checks because identity alone proves trust","It only matters for external users, since internal users are already trusted by default","It serves as the primary control plane through which access decisions are made and enforced"], correct:3, explanation:"In Zero Trust, identity becomes the central control plane; robust IAM with strong authentication and least-privilege authorization underpins virtually every access decision." },
  { id:60024, domain:5, level:3, question:"During Zero Trust implementation, security alerts spike because many legitimate actions are now individually evaluated and logged. What is the MOST appropriate response?", options:["Disable the newly added logging to reduce the noise and restore the alert volume seen before the deployment","Tune policies and detections using the new visibility, refining baselines to separate signal from noise","Roll back the Zero Trust deployment because it generates too many alerts to manage","Accept every alert as a true positive and investigate each one individually forever"], correct:1, explanation:"The increased visibility is a feature, not a fault; teams should use it to establish accurate baselines and tune policies and detections so genuine threats stand out from normal activity." },
  { id:60025, domain:5, level:2, question:"Which metric BEST indicates progress in maturing a Zero Trust implementation over time?", options:["The total number of firewalls deployed across all of the organization's data centers","The raw volume of network traffic flowing through the corporate backbone each month","The reduction in implicit trust zones and the proportion of access decisions made per-request","The number of vendors whose Zero Trust products have been purchased and installed"], correct:2, explanation:"Zero Trust maturity is measured by how much implicit trust has been eliminated — shrinking trust zones and increasing the share of dynamically evaluated, per-request access decisions." }
];

const DOMAIN_NAMES_CCZT = {
  "1": "Zero Trust Fundamentals & Principles",
  "2": "Zero Trust Architecture (NIST SP 800-207)",
  "3": "Software-Defined Perimeter (SDP)",
  "4": "Zero Trust Planning & Strategy",
  "5": "Zero Trust Implementation & Operations"
};

if (typeof window !== 'undefined') {
  window.QUESTIONS_CCZT = QUESTIONS_CCZT;
  window.DOMAIN_NAMES_CCZT = DOMAIN_NAMES_CCZT;
}
