// ── CISM Questions (IDs 10001–10040) ──────────────────────────────────────────
const QUESTIONS_CISM = [

// ─── DOMAIN 1: Information Security Governance ────────────────────────────────
{id:10001,domain:1,level:1,question:"Who holds ULTIMATE responsibility for information security governance in an organization?",options:["A. The Chief Information Security Officer (CISO)","B. The IT security department","C. The board of directors","D. External auditors"],correct:2,explanation:"The board of directors holds ultimate responsibility for organizational governance, including information security governance. They set risk appetite, approve strategy, and ensure adequate resources are allocated."},
{id:10002,domain:1,level:1,question:"What is the PRIMARY objective of information security governance?",options:["A. To prevent all security incidents from occurring","B. To align information security with business objectives and ensure value delivery while managing risk","C. To ensure compliance with all applicable regulations","D. To deploy the most advanced security technologies available"],correct:1,explanation:"Information security governance ensures security activities align with business objectives, deliver value, manage risk appropriately, optimize resources, and deliver measurable performance."},
{id:10003,domain:1,level:1,question:"An information security steering committee is BEST described as:",options:["A. A group of security engineers who design technical controls","B. A cross-functional committee providing strategic oversight and direction for the IS program","C. An external advisory board conducting compliance reviews","D. The incident response team leadership"],correct:1,explanation:"The IS steering committee includes senior business leaders, IT, legal, and risk functions to provide strategic oversight, approve IS strategy, set priorities, and align security investments with business goals."},
{id:10004,domain:1,level:1,question:"What is the MAIN purpose of an information security policy?",options:["A. To provide step-by-step technical instructions for system hardening","B. To define management's high-level intent and direction for information security","C. To document all historical security incidents","D. To train employees on specific security threats"],correct:1,explanation:"An IS policy expresses senior management's intent and commitment to security at a high level. Standards provide requirements, procedures provide instructions, and guidelines provide recommendations — all subordinate to policy."},
{id:10005,domain:1,level:1,question:"What does 'risk appetite' represent in security governance?",options:["A. The total cost of all implemented security controls","B. The amount and type of risk the organization is willing to accept in pursuing its objectives","C. The number of risks that can be mitigated per budget cycle","D. The organization's annual security budget allocation"],correct:1,explanation:"Risk appetite is the level of risk an organization will accept in pursuit of its goals. It guides decisions on risk treatment options and security resource allocation across the enterprise."},
{id:10006,domain:1,level:2,question:"When developing an IS strategy, the FIRST step should be:",options:["A. Select the security tools and technologies to deploy","B. Conduct a gap analysis against security best practices","C. Understand the current business strategy and organizational objectives","D. Hire additional security personnel"],correct:2,explanation:"IS strategy must support business strategy. Understanding business objectives first ensures security investments and priorities are aligned with what the organization needs to achieve, not just technical best practices."},
{id:10007,domain:1,level:2,question:"Which metric BEST measures information security governance effectiveness?",options:["A. Number of firewall rules currently in place","B. Total number of security incidents per quarter","C. Percentage of critical business processes with mapped and tested security controls","D. Number of security certifications held by the security team"],correct:2,explanation:"Governance effectiveness is best measured by how well security supports business objectives. Mapping controls to business processes and measuring their effectiveness demonstrates strategic alignment."},
{id:10008,domain:1,level:2,question:"Which of the following is a key indicator that information security governance is INEFFECTIVE?",options:["A. The information security budget is increasing annually","B. Security decisions are made primarily on technical merit without business context","C. The CISO reports directly to senior executive leadership","D. Regular security awareness training is conducted for all employees"],correct:1,explanation:"When security decisions lack business context, governance is failing. Effective governance ensures security investments are prioritized based on business risk and objectives, not only technical factors."},
{id:10009,domain:1,level:2,question:"The relationship between information security governance and IT governance is BEST described as:",options:["A. They are identical and interchangeable concepts","B. Information security governance is a subset of IT governance","C. IT governance is a subset of information security governance","D. They are completely separate and unrelated frameworks"],correct:1,explanation:"IT governance addresses IT's overall use to achieve business value. Information security governance is a component of IT governance focused specifically on managing information security risk and assurance."},
{id:10010,domain:1,level:3,question:"An organization's board is reviewing the IS program. Which metric MOST effectively demonstrates the program's business value?",options:["A. Number of security tools deployed during the year","B. Percentage reduction in residual risk for top business risks after control implementation","C. Number of vulnerabilities patched during the year","D. Security team headcount compared to industry benchmarks"],correct:1,explanation:"Demonstrating risk reduction tied to specific business risks shows the board that security investments are protecting what matters. Metrics must connect security outcomes to business risk language the board understands."},

// ─── DOMAIN 2: Information Risk Management ────────────────────────────────────
{id:10011,domain:2,level:1,question:"In information risk management, 'threat' is BEST defined as:",options:["A. A weakness in a system that could be exploited","B. A potential cause of an unwanted incident that could harm an asset","C. The probability that an incident will occur","D. The financial loss resulting from a security incident"],correct:1,explanation:"A threat is a potential cause of harm. Threats exploit vulnerabilities to impact assets. Distinguishing threats, vulnerabilities, and impacts is foundational to risk assessment."},
{id:10012,domain:2,level:1,question:"Which risk treatment option is exemplified by purchasing cyber insurance?",options:["A. Risk reduction (mitigation)","B. Risk avoidance","C. Risk acceptance","D. Risk transfer"],correct:3,explanation:"Risk transfer shifts the financial impact to a third party, typically through insurance or contractual agreements. It doesn't eliminate the underlying risk but reduces the organization's financial exposure."},
{id:10013,domain:2,level:1,question:"What is 'residual risk'?",options:["A. Risk that exists before any controls are applied (inherent risk)","B. Risk that remains after controls have been implemented","C. Risk that cannot be identified or quantified","D. Risk explicitly accepted and formally documented by management"],correct:1,explanation:"Residual risk = Inherent risk minus the effect of implemented controls. Management must determine whether residual risk falls within the organization's risk appetite after control implementation."},
{id:10014,domain:2,level:1,question:"Which is the FIRST step in a structured risk management process?",options:["A. Risk treatment planning","B. Risk monitoring and reporting","C. Risk identification and assessment","D. Risk communication to stakeholders"],correct:2,explanation:"You cannot manage risks you haven't identified. Risk identification and assessment must come first to understand what risks exist, their likelihood, and potential business impact before treatment options can be evaluated."},
{id:10015,domain:2,level:2,question:"The BEST way to determine which risks to prioritize for treatment is to:",options:["A. Address all high-likelihood risks first regardless of impact","B. Address all high-impact risks first regardless of likelihood","C. Evaluate and rank risks based on both likelihood and potential business impact","D. Prioritize risks with the lowest cost of remediation first"],correct:2,explanation:"Risk = Likelihood × Impact. Both factors must be considered. A low-likelihood, catastrophic-impact risk may warrant more attention than a high-likelihood, low-impact risk. Risk ratings guide prioritization."},
{id:10016,domain:2,level:2,question:"A business impact analysis (BIA) primarily helps an organization to:",options:["A. Identify all technical vulnerabilities in IT systems","B. Understand the business consequences of disruptions and establish recovery priorities","C. Calculate the annual loss expectancy from cyber attacks","D. Determine which employees require security awareness training"],correct:1,explanation:"BIA identifies critical business processes, their dependencies, and the impact of disruption over time (financial, reputational, regulatory). It establishes RTOs and RPOs and guides BC/DR prioritization."},
{id:10017,domain:2,level:2,question:"'Quantitative risk analysis' differs from 'qualitative risk analysis' in that it:",options:["A. Uses subjective ratings (high/medium/low) rather than numbers","B. Assigns numeric values to calculate financial exposure metrics such as ALE","C. Is less structured and more dependent on expert judgment","D. Is only applicable to financial and operational risks, not cybersecurity"],correct:1,explanation:"Quantitative analysis uses financial metrics: Asset Value, Exposure Factor, Single Loss Expectancy (SLE), Annualized Rate of Occurrence (ARO), and Annualized Loss Expectancy (ALE = SLE × ARO). It supports cost-benefit analysis of controls."},
{id:10018,domain:2,level:2,question:"Why is third-party risk management important?",options:["A. Vendors are legally required to share all security audit reports","B. An organization's risk exposure extends beyond its boundaries to include vendors and partners","C. Third-party relationships eliminate the organization's compliance obligations","D. Only third parties are subject to data protection regulations"],correct:1,explanation:"Organizations inherit risk from their supply chain. A vendor breach can expose customer data, disrupt services, and violate regulations. Effective third-party risk management extends the security program beyond organizational boundaries."},
{id:10019,domain:2,level:2,question:"What is the key output of a completed risk assessment?",options:["A. A list of approved security technologies to purchase","B. A risk register documenting identified risks, ratings, owners, and treatment decisions","C. The security architecture design for the next fiscal year","D. A compliance checklist aligned to applicable regulations"],correct:1,explanation:"The risk register is the primary output of risk assessment. It documents all identified risks with likelihood/impact ratings, risk owners, treatment decisions, and residual risk levels."},
{id:10020,domain:2,level:3,question:"When a risk level exceeds the organization's stated risk appetite, the BEST initial response is:",options:["A. Immediately cease the business activity associated with the risk","B. Document the risk and monitor it without taking action","C. Evaluate risk treatment options and implement the most appropriate control(s)","D. Escalate the risk directly to regulators for guidance"],correct:2,explanation:"When risk exceeds appetite, the risk owner must evaluate treatment options (reduce, transfer, avoid, or formally accept with executive approval). Simply monitoring or accepting unreviewed risk violates governance responsibilities."},

// ─── DOMAIN 3: Information Security Program Development and Management ────────
{id:10021,domain:3,level:1,question:"What is the PRIMARY purpose of a security control framework such as ISO 27001 or NIST CSF?",options:["A. To serve as a mandatory legal compliance checklist for all organizations","B. To provide a structured, repeatable approach for implementing and managing security controls","C. To replace the organization's information security policy","D. To benchmark the organization's spending against industry peers"],correct:1,explanation:"Control frameworks provide systematic, proven guidance for selecting, implementing, and assessing security controls aligned to business risk. They enable consistent, auditable, and repeatable security programs."},
{id:10022,domain:3,level:1,question:"Which type of control does a firewall BEST represent?",options:["A. Corrective control","B. Detective control","C. Preventive control","D. Compensating control"],correct:2,explanation:"A firewall prevents unauthorized access by blocking disallowed traffic before it reaches systems. Preventive controls stop incidents from occurring. Detective controls identify incidents; corrective controls restore after incidents."},
{id:10023,domain:3,level:1,question:"Security awareness training is MOST effective when it is:",options:["A. Conducted once at employee onboarding and never repeated","B. Focused exclusively on technical security staff","C. Role-based, regularly reinforced, and measured for behavioral change","D. Delivered as a single mandatory annual compliance video"],correct:2,explanation:"Effective awareness programs are tailored to job-specific risks, reinforced through repeated exposure (phishing simulations, lunch-and-learns), and measured by behavioral metrics (phishing click rates, incident reports)."},
{id:10024,domain:3,level:2,question:"A security program's maturity level is BEST assessed using:",options:["A. The total number of security incidents in the past year","B. The total information security budget as a percentage of IT spending","C. A structured maturity model such as CMMI or the NIST CSF maturity tiers","D. The total number of security staff relative to total employees"],correct:2,explanation:"Maturity models provide structured criteria for assessing how consistently and effectively security capabilities are implemented, from ad hoc/reactive (level 1) to optimized/continuous improvement (level 5)."},
{id:10025,domain:3,level:2,question:"The principle of separation of duties in information security PRIMARILY serves to:",options:["A. Ensure compliance with segregation requirements in financial regulations","B. Prevent any single individual from having sufficient access to commit fraud or cause significant harm undetected","C. Distribute security workload more evenly among team members","D. Improve operational efficiency by specializing roles"],correct:1,explanation:"Separation of duties requires multiple people for critical transactions or sensitive access. It limits potential damage from a compromised or malicious insider and reduces fraud risk."},
{id:10026,domain:3,level:2,question:"When building a security metrics program, the MOST useful metrics are those that:",options:["A. Demonstrate compliance with all applicable regulatory standards","B. Show the highest volume of threats blocked by security controls","C. Are actionable, linked to business risk, and support management decision-making","D. Require the least technical expertise to collect and report"],correct:2,explanation:"Effective metrics drive decisions. They should measure outcomes that matter to the business (risk reduction, control effectiveness) and enable management to make informed investment and prioritization decisions."},
{id:10027,domain:3,level:2,question:"An organization has a limited security budget. The FIRST action should be:",options:["A. Deploy multi-factor authentication on all systems immediately","B. Conduct a risk assessment to identify and prioritize the highest risks","C. Hire additional security personnel before other investments","D. Deploy an enterprise SIEM platform for visibility"],correct:1,explanation:"Limited resources must be targeted at the highest risks first. A risk assessment identifies the most critical vulnerabilities and threats, enabling informed, prioritized security investment decisions."},
{id:10028,domain:3,level:2,question:"What BEST describes a 'compensating control'?",options:["A. A primary control that prevents a specific security threat","B. An alternative control used when the preferred primary control cannot be implemented","C. An automated control that corrects security misconfigurations","D. An additional control layered on top of existing controls for defense in depth"],correct:1,explanation:"Compensating controls provide alternative protection when the recommended primary control is not feasible due to technical or operational constraints. They must provide equivalent or greater protection than the control they replace."},
{id:10029,domain:3,level:3,question:"The PRIMARY purpose of a security architecture is to:",options:["A. Document all currently deployed security tools and technologies","B. Provide a holistic blueprint integrating controls to protect against identified risks while supporting business objectives","C. Satisfy the documentation requirements of a security compliance audit","D. Define the organization's IT network topology and infrastructure design"],correct:1,explanation:"Security architecture provides a coherent design that integrates controls, processes, and technologies to address identified risks. It ensures consistency and completeness rather than ad-hoc control deployment."},
{id:10030,domain:3,level:3,question:"Due care in information security BEST means:",options:["A. Documenting all security decisions for future audit trail purposes","B. Taking reasonable, prudent steps to protect information assets as a competent person would","C. Immediately reporting all security incidents to law enforcement agencies","D. Purchasing and deploying the latest available security technology"],correct:1,explanation:"Due care is exercising reasonable and prudent security measures — the 'prudent person' standard. Organizations that fail to exercise due care can face legal liability for damages resulting from security incidents."},

// ─── DOMAIN 4: Information Security Incident Management ──────────────────────
{id:10031,domain:4,level:1,question:"What is the FIRST priority when an information security incident is detected?",options:["A. Notify law enforcement and regulatory authorities","B. Eradicate the threat from all affected systems","C. Identify and contain the incident to prevent further damage","D. Restore all affected systems to full operation"],correct:2,explanation:"Containment is the first priority — stopping the spread and limiting immediate damage. Full investigation, eradication, and recovery follow after the scope is understood. Notifications occur based on regulatory timelines."},
{id:10032,domain:4,level:1,question:"What is the PRIMARY purpose of an Incident Response Plan (IRP)?",options:["A. To eliminate all future security incidents through proactive controls","B. To ensure a timely, organized, and effective response that minimizes damage","C. To document lessons learned from historical security incidents","D. To satisfy mandatory security incident reporting requirements"],correct:1,explanation:"An IRP provides a pre-defined, structured process for detecting, containing, analyzing, and recovering from incidents. It reduces response time, limits damage, and ensures consistent, repeatable handling."},
{id:10033,domain:4,level:1,question:"During incident response, 'chain of custody' is important because:",options:["A. It tracks the financial costs incurred during incident response activities","B. It ensures digital evidence is collected and preserved in a manner admissible in legal proceedings","C. It documents all external communications with affected customers and partners","D. It speeds up the overall incident recovery and restoration process"],correct:1,explanation:"Chain of custody documents the handling of evidence from collection through presentation. Proper maintenance ensures digital evidence retains its integrity and remains legally defensible and admissible."},
{id:10034,domain:4,level:2,question:"The PRIMARY measure of an incident response program's effectiveness is:",options:["A. The total number of security incidents detected per year","B. The total cost of incident response tools and personnel","C. Mean time to detect (MTTD) and mean time to respond (MTTR)","D. The number of full-time staff assigned to the CSIRT"],correct:2,explanation:"MTTD measures detection speed; MTTR measures resolution speed. Together they quantify IR program performance. Reducing both minimizes the window of exposure and the business impact of security incidents."},
{id:10035,domain:4,level:2,question:"The PRIMARY purpose of a post-incident review (lessons learned) is:",options:["A. To assign individual accountability and blame for the incident","B. To satisfy regulatory post-incident reporting obligations","C. To identify improvements that prevent recurrence and enhance future response capabilities","D. To calculate and document the total financial impact of the incident"],correct:2,explanation:"Post-incident reviews focus on constructive improvement: what happened, why, what worked well, and what changes are needed. The goal is continuous improvement of controls and response capabilities, not blame."},
{id:10036,domain:4,level:2,question:"What is the key difference between business continuity (BCP) and disaster recovery (DRP)?",options:["A. BCP focuses on data recovery while DRP focuses on restoring business processes","B. BCP maintains critical business functions during a disruption; DRP focuses on IT system restoration after a disaster","C. BCP is driven by regulatory requirements while DRP is driven by risk assessment","D. They are different names for the same planning discipline"],correct:1,explanation:"BCP addresses maintaining essential business functions during any disruption (not just technical). DRP is a subset focused specifically on recovering IT infrastructure and systems. BCP has a broader organizational scope."},
{id:10037,domain:4,level:2,question:"Which type of BCP/DR test is the MOST comprehensive but also the MOST disruptive?",options:["A. Tabletop exercise (discussion-based walk-through)","B. Walk-through (checklist) test","C. Parallel test (running backup systems alongside production)","D. Full interruption test (actually cutting over to backup systems)"],correct:3,explanation:"A full interruption test cuts production over to backup systems, fully testing recovery procedures under real conditions. It provides the most realistic validation but carries significant operational risk and business disruption."},
{id:10038,domain:4,level:2,question:"An organization has experienced a data breach. What is the MOST important consideration for external communications?",options:["A. Immediately issue a public announcement to all customers before the scope is known","B. Follow a pre-defined plan coordinating legal, PR, and management while meeting regulatory notification timelines","C. Delay all external communications until the investigation is fully complete","D. Communicate only through the organization's website without direct notification to affected parties"],correct:1,explanation:"Breach communications require careful coordination: meeting regulatory notification timelines (e.g., GDPR 72 hours), obtaining legal counsel, messaging consistency, and balancing transparency with operational security."},
{id:10039,domain:4,level:3,question:"A key component that MUST be included in an incident classification scheme is:",options:["A. The financial budget allocated for each incident severity level","B. The names of all current CSIRT team members","C. Severity levels with defined criteria and corresponding response procedures and escalation paths","D. A list of all approved incident response vendors and their contact information"],correct:2,explanation:"Classification schemes must define severity levels (Critical/High/Medium/Low) with clear, objective criteria for assignment, appropriate escalation procedures, notification requirements, and response time targets."},
{id:10040,domain:4,level:3,question:"When establishing a Computer Security Incident Response Team (CSIRT), the MOST critical factor for effectiveness is:",options:["A. Ensuring all CSIRT members hold CISSP or CISM certifications","B. Having clearly defined roles, authority, communication channels, and 24/7 availability","C. Purchasing advanced forensic tools before the first incident","D. Co-locating all CSIRT members in a single physical security operations center"],correct:1,explanation:"CSIRT effectiveness depends on preparation: clearly defined roles and responsibilities, proper authority to act, pre-established communication and escalation paths, documented procedures, and tested readiness — not just tools or certifications."}
];

const DOMAIN_NAMES_CISM = {
  1: "Information Security Governance",
  2: "Information Risk Management",
  3: "IS Program Development & Management",
  4: "IS Incident Management"
};
