// ── CISA Questions (IDs 20001–20050) ──────────────────────────────────────────
const QUESTIONS_CISA = [

// ─── DOMAIN 1: Information System Auditing Process ────────────────────────────
{id:20001,domain:1,level:1,question:"What is the PRIMARY purpose of an IS audit charter?",options:["A. To document audit findings and management responses","B. To formally define the IS audit function's authority, responsibilities, and accountability","C. To schedule the annual audit calendar and resource plan","D. To list all audit tools and testing techniques approved for use"],correct:1,explanation:"The audit charter defines the IS audit function's mandate, granting it authority to access systems, personnel, and information, and establishing accountability to senior management or the audit committee."},
{id:20002,domain:1,level:1,question:"According to ISACA auditing standards, 'audit evidence' must be:",options:["A. Gathered exclusively from electronic system-generated reports","B. Sufficient, reliable, relevant, and useful to support audit conclusions","C. Obtained primarily through management interviews and self-assessments","D. Limited to evidence that management has explicitly approved for review"],correct:1,explanation:"ISACA standards require evidence to be sufficient (quantity), reliable (trustworthy source), relevant (related to the objective), and useful (supports conclusions). Evidence quality directly affects audit conclusion validity."},
{id:20003,domain:1,level:1,question:"What is 'statistical sampling' in IS auditing?",options:["A. Using the same sample size for every audit engagement","B. Selecting only the highest-value or highest-risk items for testing","C. Using probability theory to select a representative sample and draw conclusions about the population","D. Testing every item that exceeds a defined materiality threshold"],correct:2,explanation:"Statistical sampling applies probability theory to select items, enabling auditors to draw statistically valid conclusions about the entire population with a defined confidence level and margin of error."},
{id:20004,domain:1,level:1,question:"The PRIMARY purpose of maintaining IS audit working papers is to:",options:["A. Provide documentation for client billing and engagement management","B. Support audit conclusions, provide evidence of work performed, and enable quality review","C. Document all communications between the auditor and management","D. Record the technical specifications of all IT systems reviewed"],correct:1,explanation:"Working papers are the auditor's record of work performed, evidence obtained, and conclusions reached. They support the audit report, facilitate quality review, and provide the basis for follow-up audits."},
{id:20005,domain:1,level:2,question:"An IS auditor discovers a significant control weakness during fieldwork. The FIRST step should be:",options:["A. Immediately report it to the appropriate regulatory authority","B. Include it in the final report without discussing it with management first","C. Communicate the finding to the appropriate level of management for factual verification and response","D. Discontinue the audit and escalate to the audit committee"],correct:2,explanation:"IS auditors should communicate significant findings to management during fieldwork for factual accuracy verification and to obtain management's response/planned actions. This follows ISACA standards on due professional care."},
{id:20006,domain:1,level:2,question:"'Independence' in IS auditing BEST means:",options:["A. The auditor has no prior IT experience that could bias their judgment","B. The auditor has no role in designing, operating, or managing the systems being audited","C. The auditor reports directly to the IT department they are auditing","D. The auditor performs work in a different geographic location from the organization"],correct:1,explanation:"Independence requires auditors to have no relationship — design, operational, or management — with the systems or processes being audited that could impair objectivity or the appearance of objectivity."},
{id:20007,domain:1,level:2,question:"When an IS auditor finds a required preventive control is absent, the BEST approach is to:",options:["A. Immediately declare a control failure in the audit report","B. Inform only the system administrator and close the finding","C. Assess whether compensating controls exist that adequately mitigate the risk","D. Escalate the finding directly to the board of directors"],correct:2,explanation:"The absence of one control doesn't mean risk is unmitigated. The auditor must assess whether compensating controls (alternative measures) provide equivalent protection before concluding a material control deficiency exists."},
{id:20008,domain:1,level:2,question:"The PRIMARY objective of a post-audit follow-up is to:",options:["A. Identify additional findings not covered in the original audit scope","B. Verify that management has implemented agreed-upon corrective actions","C. Re-perform all testing from the original audit with the same scope","D. Evaluate the audit team's performance during the engagement"],correct:1,explanation:"Follow-up audits verify whether management has implemented the corrective actions from the original audit. This closes the audit loop and demonstrates the function adds value by driving measurable improvement."},
{id:20009,domain:1,level:3,question:"In IS audit planning, which factor is MOST important for determining audit scope?",options:["A. Availability of audit team members and their individual skill sets","B. Results of a risk assessment identifying the areas of highest organizational risk","C. Requests from management for specific areas to be audited","D. The areas that were not covered in the previous year's audit plan"],correct:1,explanation:"Audit scope should be risk-driven. A risk assessment identifies the highest-risk areas deserving audit attention. Resource allocation guided by risk maximizes audit value and ensures critical areas receive appropriate coverage."},
{id:20010,domain:1,level:3,question:"An IS auditor reviewing a company's IT risk management framework should PRIMARILY assess:",options:["A. Whether the framework uses a recognized standard such as COBIT or NIST","B. Whether the framework is effectively identifying, assessing, and treating IT risks aligned to business objectives","C. Whether IT management formally approves all identified risks annually","D. Whether the risk framework documentation has been updated within the last 12 months"],correct:1,explanation:"Framework effectiveness — not just its existence or documentation currency — is the primary concern. The auditor must assess whether the framework actually identifies and addresses real IT risks in a way that protects business objectives."},

// ─── DOMAIN 2: Governance and Management of IT ────────────────────────────────
{id:20011,domain:2,level:1,question:"The COBIT framework is BEST described as:",options:["A. A technical standard for configuring and hardening IT security controls","B. A comprehensive framework for the governance and management of enterprise IT","C. A project management methodology for IT system implementations","D. An IS audit standard published and maintained by ISACA"],correct:1,explanation:"COBIT (Control Objectives for Information and Related Technologies) provides a comprehensive framework for IT governance and management, aligning IT goals with business objectives through defined processes and controls."},
{id:20012,domain:2,level:1,question:"IT governance is PRIMARILY the responsibility of:",options:["A. The CIO and senior IT management team","B. The IS audit function and external auditors","C. The board of directors and senior executive management","D. The IT steering committee and department heads"],correct:2,explanation:"IT governance is a board and executive management responsibility. They set direction, establish accountability, delegate authority to management, and monitor IT performance against business objectives."},
{id:20013,domain:2,level:1,question:"What is the PRIMARY role of an IT steering committee?",options:["A. To approve day-to-day IT expenditures and purchase orders","B. To manage routine IT operational issues and service desk escalations","C. To provide strategic oversight and prioritize IT investments aligned with business goals","D. To investigate and review all IT-related security incidents"],correct:2,explanation:"The IT steering committee bridges business and IT strategy. It prioritizes IT investments, approves major initiatives, monitors IT performance, and ensures IT delivers business value."},
{id:20014,domain:2,level:2,question:"A 'maturity model' for IT governance measures:",options:["A. The age and obsolescence level of IT infrastructure and systems","B. The degree of process capability, consistency, and optimization achieved in IT governance practices","C. The return on investment of IT governance program initiatives","D. Employee knowledge and awareness of IT governance policies"],correct:1,explanation:"Maturity models assess how consistently and effectively IT processes are performed, from ad hoc/reactive (level 1) to continuously optimized (level 5). Higher maturity indicates more reliable, predictable outcomes."},
{id:20015,domain:2,level:2,question:"An IS auditor reviewing IT governance should PRIMARILY focus on:",options:["A. Detailed technical configurations of IT systems and security tools","B. Whether IT activities and investments are aligned with and supporting business objectives","C. Whether IT staff hold appropriate technical certifications","D. Compliance with international technical standards and industry benchmarks"],correct:1,explanation:"IT governance auditing focuses on strategic alignment, value delivery, risk management, resource optimization, and performance measurement. Technical implementation details are secondary to governance effectiveness."},
{id:20016,domain:2,level:2,question:"Which is a KEY risk indicator of IT governance failure?",options:["A. The security budget is growing faster than the IT budget overall","B. IT investments consistently fail to deliver expected business value or create unacceptable risks","C. IT projects are delivered on time but slightly over budget","D. IT policies are reviewed and updated on an annual cycle"],correct:1,explanation:"IT governance failures result in strategic misalignment, wasted investment, unmanaged risks, and missed opportunities. Projects that don't deliver value or create new risks indicate the governance framework is not working."},
{id:20017,domain:2,level:2,question:"A company's IT strategy should be MOST directly derived from:",options:["A. The IT department's technical capability and technology roadmap","B. The overall business strategy and organizational objectives","C. Industry peer benchmarks for IT spending and capabilities","D. Regulatory and technology compliance requirements"],correct:1,explanation:"IT strategy exists to enable business strategy. It must be derived from business objectives to ensure IT capabilities support organizational goals rather than pursuing technology for its own sake."},
{id:20018,domain:2,level:3,question:"When reviewing IT resource management, an IS auditor should verify that:",options:["A. IT has the lowest possible headcount relative to industry benchmarks","B. All IT staff possess vendor certifications for the technologies they manage","C. IT resources (people, technology, information) are optimized to deliver on the IT strategy","D. IT budget allocations are consistent with the previous three years of spending"],correct:2,explanation:"IT resource management ensures that people, infrastructure, information, and applications are acquired, developed, and deployed efficiently to support the IT strategy and ultimately the business strategy."},
{id:20019,domain:2,level:3,question:"IT policies and procedures PRIMARILY serve to:",options:["A. Provide technical configuration instructions for system administrators","B. Establish management's direction, accountability, and standardized practices across IT activities","C. Replace the need for employee security training and awareness programs","D. Satisfy the documentation requirements of external regulatory bodies"],correct:1,explanation:"IT policies express management's direction and commitment. Procedures operationalize policies into consistent, accountable practices. Together they establish standards, reduce variation, and support compliance and risk management."},
{id:20020,domain:2,level:3,question:"What distinguishes 'IT governance' from 'IT management'?",options:["A. IT governance focuses on day-to-day operations; IT management focuses on long-term strategy","B. IT governance sets direction and ensures accountability; IT management plans and executes activities to achieve direction","C. IT governance is an external regulatory requirement; IT management is an internal function","D. There is no meaningful distinction between governance and management"],correct:1,explanation:"Governance = direction-setting, oversight, and accountability (board/executive level). Management = planning, executing, and monitoring activities to implement the direction given by governance. Both are essential and complementary."},

// ─── DOMAIN 3: IS Acquisition, Development and Implementation ─────────────────
{id:20021,domain:3,level:1,question:"What is the PRIMARY benefit of involving an IS auditor early in the Systems Development Lifecycle (SDLC)?",options:["A. To reduce overall project development costs","B. To assist the development team in designing application features","C. To ensure security and control requirements are built in from the beginning","D. To manage project schedule and milestone completion"],correct:2,explanation:"Early IS auditor involvement ensures controls are designed into systems from the requirements phase (security by design). Retrofitting security after development is significantly more expensive and less effective."},
{id:20022,domain:3,level:1,question:"A key control in change management processes is:",options:["A. Allowing developers to test their own code changes directly in production","B. Requiring all changes to be tested in a non-production environment prior to deployment","C. Implementing emergency changes immediately without documentation","D. Restricting all system changes to a single quarterly maintenance window"],correct:1,explanation:"Change management requires non-production testing before production deployment to identify defects and security issues. Segregation of duties between development, testing, and production access is equally critical."},
{id:20023,domain:3,level:1,question:"What is the purpose of User Acceptance Testing (UAT)?",options:["A. To test system performance under peak expected load conditions","B. To have business users verify the system meets requirements before go-live","C. To identify security vulnerabilities in the application code","D. To test disaster recovery and business continuity procedures"],correct:1,explanation:"UAT is the final functional test where business users confirm the system does what they require before production deployment. It validates business requirements from the user perspective."},
{id:20024,domain:3,level:2,question:"Separation of duties in application development MEANS:",options:["A. Developers and testers must work in physically separate locations","B. No single person should be able to develop, test, approve, AND deploy code to production","C. Each developer is assigned to work on only one application module","D. Development and production environments must use different naming conventions"],correct:1,explanation:"Separation of duties prevents unauthorized changes by requiring different individuals to develop, test, approve, and deploy changes. This limits fraud potential and ensures multi-party review at each stage."},
{id:20025,domain:3,level:2,question:"In a post-implementation review, IS auditors are PRIMARILY concerned with:",options:["A. Whether the system employed the most current technology available","B. Whether the project was delivered within the original timeline and budget","C. Whether implemented controls are functioning effectively and business benefits have been realized","D. Whether developers adhered to the organization's coding standards"],correct:2,explanation:"Post-implementation reviews assess whether the system meets business objectives, whether controls work as designed, and whether expected benefits (efficiency, risk reduction) have actually been achieved."},
{id:20026,domain:3,level:2,question:"What is 'system regression testing'?",options:["A. Testing to verify a system performs adequately under expected workloads","B. Testing to ensure new changes haven't broken existing system functionality","C. Testing performed at the end of a system's operational lifecycle","D. Testing to confirm the system meets all regulatory compliance requirements"],correct:1,explanation:"Regression testing verifies that changes haven't adversely affected existing functionality. It is critical for maintaining system stability when enhancements, patches, or fixes are applied."},
{id:20027,domain:3,level:2,question:"Which is a key risk of an inadequate change management process?",options:["A. Security controls that are implemented too aggressively restrict business operations","B. Unauthorized or untested changes introduce errors or vulnerabilities into production systems","C. System documentation becomes excessively detailed and difficult to maintain","D. System changes take longer to implement, reducing business agility"],correct:1,explanation:"Without rigorous change management, unauthorized changes can introduce vulnerabilities, break functionality, or create compliance violations. Lack of testing and approval controls is a primary source of IT operational risk."},
{id:20028,domain:3,level:3,question:"When auditing an application, an IS auditor should FIRST:",options:["A. Review the application source code line-by-line for vulnerabilities","B. Examine the application's technical architecture and infrastructure design","C. Understand the control objectives and requirements the system was designed to meet","D. Test all user access rights and privilege levels in the application"],correct:2,explanation:"Understanding what controls are required (control objectives) before testing is fundamental. Without knowing what the application should achieve, the auditor cannot meaningfully assess whether it does so effectively."},
{id:20029,domain:3,level:3,question:"What is 'parallel operation' as a system conversion strategy and what is its PRIMARY advantage?",options:["A. Running systems in two separate geographic locations for redundancy","B. Running old and new systems simultaneously to compare outputs before full cutover — safest conversion approach","C. Migrating user groups to the new system in sequential phases","D. Keeping the old system on standby for 90 days after the new system goes live"],correct:1,explanation:"Parallel operation runs both systems simultaneously, comparing outputs for consistency and correctness. It is the safest conversion strategy because discrepancies can be identified and resolved before the old system is decommissioned."},
{id:20030,domain:3,level:3,question:"An IS auditor reviewing software procurement should verify:",options:["A. That the vendor offers the most competitive pricing in the market","B. That the software uses the most current programming language","C. That the software meets security requirements, the vendor is financially stable, and contract terms protect the organization","D. That the software was developed in the same country where the organization operates"],correct:2,explanation:"Software procurement audit focuses on: security requirements compliance (including code review/testing), vendor viability (financial stability, support continuity), contractual protections (SLAs, escrow, right to audit), and license compliance."},

// ─── DOMAIN 4: IS Operations and Business Resilience ─────────────────────────
{id:20031,domain:4,level:1,question:"The difference between IT 'incident management' and 'problem management' is:",options:["A. They are the same process described at different organizational levels","B. Incident management restores service quickly; problem management finds and eliminates root causes permanently","C. Incident management is a tactical process; problem management is a long-term strategic planning process","D. Incident management is IT-focused; problem management is business continuity-focused"],correct:1,explanation:"ITIL distinguishes them: incident management focuses on restoring service as quickly as possible. Problem management identifies and eliminates root causes of recurring incidents to prevent recurrence permanently."},
{id:20032,domain:4,level:1,question:"Which backup strategy provides the FASTEST individual file restoration time?",options:["A. Incremental backup (requires full + all incremental backups)","B. Differential backup (requires full + latest differential only)","C. Full backup (all data in a single backup set)","D. Grandfather-father-son rotation scheme"],correct:2,explanation:"Full backup provides the fastest individual restore because all data is in a single backup set — no need to piece together multiple sets. Differential requires full + latest differential; incremental requires full + every increment."},
{id:20033,domain:4,level:1,question:"A Recovery Time Objective (RTO) of 4 hours means:",options:["A. Up to 4 hours of data loss is acceptable following a system failure","B. The system must be fully restored within 4 hours of a failure or disaster declaration","C. The organization has 4 hours to formally declare a disaster situation","D. Backup systems will automatically activate exactly 4 hours after a failure"],correct:1,explanation:"RTO is the maximum acceptable time to restore a system or business process. If RTO = 4 hours, recovery procedures must be designed and tested to restore service within 4 hours of a disruption."},
{id:20034,domain:4,level:2,question:"When reviewing IT operations, an IS auditor should consider which as a KEY control?",options:["A. Whether all IT staff have individual workstations and private offices","B. Whether IT operations and development functions are properly segregated","C. Whether the IT department uses only cloud-based services for flexibility","D. Whether IT staff maintain consistent working hours"],correct:1,explanation:"Segregation between IT operations and development prevents unauthorized changes to production systems, enforces change management procedures, and is a foundational internal control in IT operations."},
{id:20035,domain:4,level:2,question:"What is the MOST important consideration when establishing off-site backup storage?",options:["A. The monthly cost of the off-site storage facility","B. The proximity to the primary data center for quick retrieval","C. The geographic distance sufficient to be unaffected by the same disaster as the primary site","D. Using a third-party vendor rather than company-owned facilities"],correct:2,explanation:"Off-site backup must be geographically separated enough that a regional disaster (earthquake, flood, power outage) affecting the primary site cannot also destroy the backups. Proximity defeats the purpose of off-site storage."},
{id:20036,domain:4,level:2,question:"What does 'availability' mean as an IT operational metric?",options:["A. The percentage of time a system is operational and accessible to authorized users","B. The number of redundant backup copies maintained for critical data","C. Whether IT support staff are available around the clock","D. The number of helpdesk tickets resolved per day"],correct:0,explanation:"Availability is expressed as a percentage (e.g., 99.9% = ~8.7 hours downtime/year). It is measured against SLAs and reflects the reliability of IT services. Availability targets drive architectural decisions for redundancy."},
{id:20037,domain:4,level:2,question:"The PRIMARY purpose of IT capacity management is:",options:["A. To ensure all IT staffing positions are continuously filled","B. To ensure IT infrastructure meets current and forecasted business demand without over-provisioning","C. To manage IT project budgets and capital expenditure approvals","D. To control the number and frequency of IT changes implemented"],correct:1,explanation:"Capacity management ensures compute, storage, and network resources meet current workloads and anticipated growth, optimizing costs while preventing performance degradation from under-provisioning."},
{id:20038,domain:4,level:3,question:"When reviewing a disaster recovery plan, an IS auditor is MOST concerned with:",options:["A. Whether the plan is documented using a formally approved template","B. Whether the plan has been tested and results demonstrate it meets defined RTOs and RPOs","C. The total capital cost of implementing the disaster recovery infrastructure","D. Whether all IT systems are included in the plan regardless of business criticality"],correct:1,explanation:"Documentation alone is insufficient. The auditor must verify that the plan is regularly tested (tabletop, parallel, full interruption) and that test results confirm recovery objectives can be achieved in real scenarios."},
{id:20039,domain:4,level:3,question:"An IS auditor reviewing patch management should verify:",options:["A. That all patches are installed within 24 hours of vendor release regardless of risk level","B. That there is a documented process for assessing patch criticality, testing in non-production, and timely deployment","C. That only the most recent security patches are applied, with older patches removed","D. That patch management is fully automated with no manual oversight"],correct:1,explanation:"Effective patch management requires: risk-based assessment (not all patches are equal), testing in non-production before production deployment, documented timelines based on severity, and verification of successful deployment."},
{id:20040,domain:4,level:3,question:"Which monitoring tool is MOST useful for detecting unauthorized access attempts to IT systems?",options:["A. Network performance monitoring dashboard","B. Audit trail and system log review with alert generation","C. IT capacity planning and forecasting tools","D. Configuration management database (CMDB)"],correct:1,explanation:"System logs and audit trails record authentication attempts, privilege changes, and system events. Automated review with alert generation on anomalies is essential for detecting unauthorized access in a timely manner."},

// ─── DOMAIN 5: Protection of Information Assets ───────────────────────────────
{id:20041,domain:5,level:1,question:"What is the PRIMARY purpose of access control in protecting information assets?",options:["A. To technically prevent 100% of unauthorized access attempts","B. To ensure only authorized individuals can access resources based on business need and granted permissions","C. To monitor and log all user activity across the network","D. To prevent employees from sharing or disclosing passwords to colleagues"],correct:1,explanation:"Access control grants or denies access to resources based on identity, authorization, and business need. The goal is appropriate, auditable access — not absolute prevention, which would also prevent legitimate use."},
{id:20042,domain:5,level:1,question:"Which access control model is MOST appropriate for a highly classified government environment?",options:["A. Discretionary Access Control (DAC)","B. Role-Based Access Control (RBAC)","C. Mandatory Access Control (MAC)","D. Attribute-Based Access Control (ABAC)"],correct:2,explanation:"MAC assigns clearance levels to subjects and classification labels to objects. Access is system-enforced based on policy, not user discretion. It is used where strict enforcement of data sensitivity classifications is required."},
{id:20043,domain:5,level:1,question:"What is the PRIMARY purpose of data classification?",options:["A. To organize data for efficient retrieval and storage management","B. To determine the appropriate level of protection for data based on its sensitivity and business value","C. To meet data retention schedule requirements under applicable regulations","D. To standardize file naming conventions across the organization"],correct:1,explanation:"Data classification identifies sensitivity levels (public, internal, confidential, restricted), enabling proportionate and appropriate security controls based on the actual risk and value of the data."},
{id:20044,domain:5,level:2,question:"When reviewing logical access controls, an IS auditor should PRIMARILY verify:",options:["A. That all users have administrative rights to perform their duties efficiently","B. That access rights follow least privilege and are reviewed regularly, especially after role changes","C. That users share accounts to simplify system administration and reduce costs","D. That all access logs are automatically purged after 30 days to manage storage"],correct:1,explanation:"Least privilege and regular access reviews (especially after organizational changes, terminations, or promotions) are foundational access control requirements. User accounts must reflect current, appropriate access."},
{id:20045,domain:5,level:2,question:"What is the STRONGEST authentication approach?",options:["A. Password with complexity requirements and expiration","B. Security question plus password combination","C. Hardware token OTP plus password (multi-factor authentication)","D. Password plus SMS verification code (multi-factor authentication)"],correct:2,explanation:"Hardware token OTP + password represents MFA combining something you have (hardware token) and something you know (password). Hardware tokens are generally more resistant to phishing than SMS codes."},
{id:20046,domain:5,level:2,question:"What is the PRIMARY security purpose of network segmentation?",options:["A. To improve overall network throughput and reduce latency","B. To limit breach scope by preventing lateral movement between network segments","C. To reduce IT network infrastructure costs through consolidation","D. To simplify network administration and reduce management overhead"],correct:1,explanation:"Network segmentation limits an attacker's lateral movement after compromising one host or segment. Security zones with appropriate controls between them are fundamental to defense in depth."},
{id:20047,domain:5,level:2,question:"An IS auditor reviewing encryption should primarily verify that:",options:["A. All files on all systems are encrypted regardless of sensitivity level","B. Sensitive data is encrypted in transit and at rest using appropriate, current algorithms","C. Encryption keys are stored with the encrypted data for operational convenience","D. Users manage their own encryption keys without centralized oversight"],correct:1,explanation:"Critical verification: sensitive data encrypted in transit (TLS) and at rest (AES-256), use of strong current algorithms, and sound key management (separation of keys from data, proper lifecycle management)."},
{id:20048,domain:5,level:3,question:"Which physical security control is MOST effective for a high-security data center?",options:["A. Security camera coverage of all entrances and server aisles","B. Uniformed security guards stationed at the main entrance","C. Layered controls: perimeter fence, badge access, mantrap, biometric authentication, CCTV with logging","D. Locked server racks with individually keyed access per rack"],correct:2,explanation:"Defense in depth for physical security uses multiple independent layers. No single control (cameras, guards, or locked racks) is sufficient. Multiple overlapping controls ensure that bypassing one still leaves others intact."},
{id:20049,domain:5,level:3,question:"During a review of endpoint security, an IS auditor should verify:",options:["A. That all endpoints use identical operating systems for management consistency","B. That endpoints have current AV/EDR, OS patching, full-disk encryption, and host-based firewall controls","C. That organizational policy prohibits employees from using any personal devices for work","D. That all endpoint devices have physical security cable locks installed"],correct:1,explanation:"Endpoint security requires multiple controls in combination: up-to-date AV/EDR for malware detection, OS and application patching, full-disk encryption (critical for lost/stolen devices), and host-based firewall."},
{id:20050,domain:5,level:3,question:"What is the MOST important control to verify during an access recertification review?",options:["A. That all passwords were changed during the review period","B. That managers have formally reviewed and approved or revoked each user's access rights","C. That the access review was completed within the scheduled timeframe","D. That all service accounts were included in the review scope"],correct:1,explanation:"The core control in access recertification is management review and attestation. Managers must actively review and confirm or revoke each access right — rubber-stamping without review defeats the purpose of recertification."}
];

const DOMAIN_NAMES_CISA = {
  1: "IS Auditing Process",
  2: "Governance & Management of IT",
  3: "IS Acquisition, Dev & Implementation",
  4: "IS Operations & Business Resilience",
  5: "Protection of Information Assets"
};
